### ISSUE TITLE
Missing file extension in download save dialog

### ISSUE THREAD

**Issue by steverandy** [electron/electron#10121]
* Electron version: 1.7.5
* Operating system: macOS 10.12.6

### Expected behavior

Save dialog should show filename with the correct extension.

### Actual behavior

Extension is missing in the filename on the save dialog window.

<img width="877" alt="screen shot 2017-07-26 at 10 51 42 pm" src="https://user-images.githubusercontent.com/525332/28627999-f425a954-7255-11e7-924e-f199d598f48a.png">

### How to reproduce

Download a file from a webview.

**Comment by zeke** [comment]
@steverandy do you have Finder configured to show extensions?

![screen shot 2017-07-26 at 2 26 26 pm](https://user-images.githubusercontent.com/2289/28644462-8a8d7c52-720e-11e7-8f41-20dc6a16112f.png)

**Comment by deltaroe** [comment]
We've run into this as well on 1.7.4 and macOS 10.12

With "Show all filename extensions" enabled the extension is added when a file is downloaded, when it's off downloaded files are stripped of their extensions and saved as a bare filename. 

Reverting to 1.6.11 resolves the issue for us

**Comment by steverandy** [comment]
@zeke I don't have the finder config enabled.

When it is enabled, it fixes the issue.
Is this behavior somewhat controlled by the Finder?

**Comment by steverandy** [comment]
I can confirm that the issue is present since v1.7.4.

**Comment by javan** [comment]
Confirmed here on macOS 10.12.6 + Electron 1.7.5 too. Curiously, it only happens in a packaged (with electron-packager in my case) .app. The file extension is present when launching the app locally with `electron .`.

**Comment by kevinsawicki** [comment]
This looks like a possible regression from https://github.com/electron/electron/pull/9610, @shubham2892 would you be able to take a look?

**Comment by juanmnl** [comment]
Same here, macOS Sierra 10.12.6, electron v1.7.5

Finder's "show all filename extensions" fixes it, but I don't expect users to have it enabled by default.

**Comment by bennyn** [comment]
Encountered the same issue with Electron 1.7.6. When Finder's "Show all filename extensions" is enabled, then files are saved as "file.txt". When the setting is disabled, files will get saved as "file" (without extension). 

This behaviour has been different in the past (with Electron 1.6). At that time files were always saved with their extension.

**Comment by bennyn** [comment]
I tried to cheat the save dialog the following way:

1. Downloading file as `Blob` using `XMLHttpRequest` (with `responseType` of `arraybuffer`)
1. Creating URL from the Blob (using `URL.createObjectURL`)
1. Creating anchor tag with `href` property set to Blob URL
1. Setting `download` property of anchor tag to fake filename
1. Triggering `click` on anchor tag

Unfortunately it still doesn't work. You can test it in your own Electron app using the following snippet from the DevConsole within Electron:

```javascript
const url = window.URL.createObjectURL(new Blob());
const anchor = document.createElement('a');
document.body.appendChild(anchor);
anchor.href = url;
anchor.download = 'file.txt';
anchor.style = 'display: none';
anchor.click();
```

Although `anchor` is set to the fixed value `file.txt`, it depends on the macOS Finder setting if the extension is shown in the save dialog or not.

**Comment by dengyaolong** [comment]
really harmful change~Many user feedback file download but  can't open cause extend name is lost. Any hack?

**Comment by javan** [comment]
We've had customers report this issue on Windows 10 as well. There's a similar OS setting: http://www.thewindowsclub.com/show-file-extensions-in-windows

**Comment by MarshallOfSound** [comment]
I just spent a fair time trying to debug this, it looks like our dialog logic is correct (still) but is not being triggered by our download manager delegates.  Will investigate more when I get a chance, at the moment my thoughts are somewhere in a Chromium update our code stopped being executed

**Comment by dengyaolong** [comment]
Now, I prompt the saveDialog and get the filename, add extend name(get by request) when no extend name set by use. Really strange, but work...

**Comment by marcoconti83** [comment]
Hey @dengyaolong, 
thanks for the suggestion on how to "hack" a solution. Could you please explain more how you do it? Any code you can share with us?

**Comment by javan** [comment]
> This looks like a possible regression from #9610

@MarshallOfSound, have you looked into that change as a possible cause?

**Comment by dengyaolong** [comment]
@marcoconti83 I upload my sample code to  https://github.com/dengyaolong/electron-downloader/blob/master/index.js

**Comment by marcoconti83** [comment]
@dengyaolong thanks!

**Comment by bennyn** [comment]
@dengyaolong With your `'will-download'` listener I am able to get the filename (plus it's extension). 🎉

However, the `'will-download'` event only triggers for after the "Save as" dialog has been shown. Is it the same for you? Because I want to fill in the filename (including extension) beforehand.

**Comment by dengyaolong** [comment]
@bennyn  I update the listener, now , you can set 'opts.dir' to set saveDir without dialog.
ps. just  call `item.setSavePath` like my code. https://github.com/dengyaolong/electron-downloader/blob/master/index.js

**Comment by poiru** [comment]
Fixed by #10469.

**Comment by BONDbATIF** [comment]
@steverandy @javan 
 I am using electron v1.8.4 in mac .Still extension issue is not fixed in mac .
Any update ?

**Comment by Sharcoux** [comment]
I'm stiill having the issue in Windows as of `    "electron-builder": "22.10.5",`
