### ISSUE TITLE
hiddenInset and vibrancy cause a invisible/low-alpha titlebar on 10.13 

### ISSUE THREAD

**Issue by gerges** [electron/electron#10521]
* Electron version: 1.7.6
* Operating system: MacOS High Sierra GM

### Expected behavior

Title bar should not be invisible

![screen shot 2017-09-14 at 11 22 04 am](https://user-images.githubusercontent.com/320654/30441406-f34fe61a-993e-11e7-8592-244e50a92bb9.png)

### Actual behavior

Title bar is invisible

### How to reproduce
```
  mainWindow = new BrowserWindow({
      vibrancy: 'light',
      titleBarStyle: 'hiddenInset',
      width: 800,
      height: 600
  })
```

```
 $ git clone git@github.com:gerges/electron-quick-start.git -b  issue/invisible-titlebar
 $ npm install
 $ npm run start
```

**Comment by gerges** [comment]
```
2017-09-14 11:21:50.732 Electron[25825:1762070] *** WARNING: Textured window <AtomNSWindow: 0x7fd0d4e75f80> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```
I think we may want to explicitly set titlebarAppearsTransparent to NO in this case?

**Comment by juliangruber** [comment]
Similar happens with `frame: false`:


![screen shot 2017-09-26 at 11 54 52](https://user-images.githubusercontent.com/10247/30854391-c221b2c2-a2b1-11e7-966a-a2fa07d34045.png)

![screen shot 2017-09-26 at 11 54 51](https://user-images.githubusercontent.com/10247/30854402-c9d95b00-a2b1-11e7-8d14-059295fa513f.png)

**Comment by mdeboer** [comment]
@gerges I get the same warning here, digging in the code now and my eye spotted this: https://github.com/electron/electron/blob/1-7-x/atom/browser/native_window_mac.mm#L922

So my guess is that adding something like this at [line 895](https://github.com/electron/electron/blob/1-7-x/atom/browser/native_window_mac.mm#L895) would fix it:
```objectivec
// Explicitely don't make titlebar transparent by default
if (base::mac::isAtLeastOS10_10()) {
  [window_ setTitlebarAppearsTransparent:NO];
}
```

But I don't know, never touched Objective C / Xcode before so don't look at me 😆

**Comment by gnattu** [comment]
It seems like the reason is not related to `setTitlebarAppearsTransparent` because you have to set this value to `true` so that the title bar will no longer cover the contents beneath it. As far as I concern, the actual reason is that Apple change the behavior of `NSFullSizeContentViewWindowMask` which was used to draw vibrancy effect under the titlebar region. Without that mask the titlebar area will also become totally transparent in an earlier version of macOS release, which is same as the behavior on High Sierra. `NSFullSizeContentViewWindowMask` is considered [deprecated](https://developer.apple.com/documentation/appkit/nsfullsizecontentviewwindowmask) by Apple in the latest 10.13 SDK, and it no longer draws vibrancy effect under the titlebar area. Apple encourages to use [contentLayoutRect](https://developer.apple.com/documentation/appkit/nswindow/1419124-contentlayoutrect?language=objc) or [contentLayoutGuide](https://developer.apple.com/documentation/appkit/nswindow/1419094-contentlayoutguide?language=objc) instead.

**Comment by gnattu** [comment]
Some good news and bad news:
I managed to make the vibrant titlebar working, as well as get the rounded corner under `webview ` back again.  But another High Sierra related bug has been located: the window controller(traffic lights) will get covered by `webview`.  Check the images below:

<img width="830" alt="screen shot 2017-10-03 at 13 32 13" src="https://user-images.githubusercontent.com/12995396/31139362-4fe5d376-a83f-11e7-8e77-183940f10b07.png">
<img width="809" alt="screen shot 2017-10-03 at 13 32 23" src="https://user-images.githubusercontent.com/12995396/31139363-4fef6648-a83f-11e7-9b33-d25f4374ee99.png">
<img width="802" alt="screen shot 2017-10-03 at 13 34 56" src="https://user-images.githubusercontent.com/12995396/31139474-adcbd1a2-a83f-11e7-84b8-2a0925283d6c.png">

I also found that the `customButtonOnHover` which does not have a titlebar at all, which means it does not affected by the low alpha titlebar issue, also have its button covered by `webview`.  I think both could be webview-related, have to dig deeper.

**Comment by mdeboer** [comment]
Making good progress there @gnattu, thank you so much!

**Comment by sallar** [comment]
@gnattu Finally someone that looks into this. Thank you.

**Comment by ImJCabus** [comment]
@gnattu I've also looked at the code but you seem to have dug deeper already so I'll put my hopes on you for this :). I noticed that toggling fullscreen once seems to solve both the transparent titleBar and rounded corners issues. I hope this hint helps you. Thanks

**Comment by sallar** [comment]
@ImJCabus Are you saying the issue has been resolved in 10.13.1?

**Comment by tborychowski** [comment]
10.13.1? but the latest beta is 1.8.2?

**Comment by ImJCabus** [comment]
@sallar No. The issue is still there. However, toggling fullscreen (green traffic lights icon) once resolves it.

**Comment by mdeboer** [comment]
@ImJCabus I can confirm this works with Atom 👍  Glad you found a workaround until it's fixed.

**Comment by sbward** [comment]
@ImJCabus Your workaround doesn't work for me, unfortunately.

**Comment by tborychowski** [comment]
@ImJCabus yes, this works in principle.
But how would you implement that in practice?
- either toggling the fullscreen programmatically - which looks weird
- or asking the user to do this manually? :-)

**Comment by ImJCabus** [comment]
@sbward Hmm. I haven't looked into this for a while now. Maybe electron had an update that killed the "workaround"?
@tborychowski Yea it's not really a workaround... With toggling fullscreen you can at least see the layout correctly while developing. However, toggling programmatically or asking the user to do so is not really feasible 😄 (1 start ratings incoming 🙈 )

**Comment by everdrone** [comment]
any update on this?

still experiencing transparent bar in macOS 10.13.2

**Comment by mdeboer** [comment]
@ImJCabus though I haven tried. I suppose if you're on a deadline and need to deliver you can always implement a look-a-like toolbar and set the real toolbar as hidden.

**Comment by archae0pteryx** [comment]
Anyone... Bueler...

**Comment by Igor10k** [comment]
Adding `transparent: true` to the `BrowserWindow` settings fixes the transparent bar bug but you'll end up with no rounded corners at the top bug that is described here https://github.com/electron/electron/issues/10522

**Comment by tommoor** [comment]
Surprised this bug isn't higher priority for a fix considering it makes both frameless and vibrant windows unusable on macOS and affects a bunch of atom themes 😔

**Comment by tommoor** [comment]
I can't fix this myself but I added a $300 bounty to the issue if it helps anyone find the time to have a go at fixing 😄 

https://www.bountysource.com/issues/49338524-hiddeninset-and-vibrancy-cause-a-invisible-low-alpha-titlebar-on-10-13

**Comment by MarshallOfSound** [comment]
Proposed fix is up 👍 https://github.com/electron/electron/pull/11886

**Comment by sallar** [comment]
@codebytere I think this issue should be re-opened: https://github.com/electron/electron/pull/11886#issuecomment-368589265
