### ISSUE TITLE
Electron doesn't open external links in latest version of Chrome

### ISSUE THREAD

**Issue by paul321** [electron/electron#10948]
* Electron version: 1.7.8
* Operating system: MacOS High Sierra

External links are not opened anymore in the latest version of Chrome, the browser launches and then closes and the icon appears in doc and then is gone.

You can try this bug by pasting the following link in Electron devtools with Chrome as default browser:

require('electron').shell.openExternal('http://google.com');

**Comment by mofux** [comment]
I don't think this has anything to do with electron (but with chrome), I have the same problem since a couple of days, and it also happens when opening an url from any other app (e.g. Mail.app).

**Comment by sachinrekhi** [comment]
I updated to the very latest version of Chrome and that appeared to resolve this issue for me.

**Comment by Geex-Renzo** [comment]
I am using the latest version for Chrome and it isn't working me yet, so in my opinion, this Issue is still valid

**Comment by JohannBlake** [comment]
I'm using Chrome 62.0.3202.94 (the latest version) and sometime over the past several days, launching a url from within Electron is causing Safari to launch. I checked my Mac preference and Chrome preferences and both are set to use Chrome as the default browser.

**Comment by paul321** [comment]
I think we can close this, it was a bug in Chrome that prevented Electron to open urls.

**Comment by JohannBlake** [comment]
What do you mean by "was a bug". I am using the current version of Chrome, so it can't be "was".

**Comment by paul321** [comment]
It was a bug few versions ago when chrome released 2 version in 2 days right now is working fine with the latest version.

**Comment by JohannBlake** [comment]
Well clearly it isn't working fine since I am reporting this issue. So please do not close this issue.

**Comment by paul321** [comment]
I think you reported something else related to default browser and Safari, this was an old issue in Chrome and it got fixed with Chrome updates and it's not related to Electron.

**Comment by JohannBlake** [comment]
The problem is clearly Electron related. Launching a url is causing Safari to launch even though Chrome is set to be my default browser. This issue only began when I updated to the latest version of Electron.

**Comment by mofux** [comment]
@JohannBlake can you please share the version of chrome you are using? Does opening an url from Mail.app also open it in Safari? Sounds like a problem local to your machine, for me this issue was fixed a couple of chrome releases back, just as stated above.

**Comment by JohannBlake** [comment]
The version of Chrome was already listed above.  62.0.3202.94

**Comment by JohannBlake** [comment]
I also just updated my MacOS to 10.13.1 (the latest). This caused the entire OS to be installed. The problem persists, so this even rules out the OS being the issue.

**Comment by paul321** [comment]
I just tested it on MacOS High Sierra with 2 versions of Electron 1.7.9 and 1.8.2 beta2 and it's working fine, there must be something wrong with your OS or settings.

**Comment by JohannBlake** [comment]
Can't be the OS as I just updated that. What version of Chrome did you test it on?

**Comment by paul321** [comment]
62.0.3202.94

**Comment by paul321** [comment]
Can you do a test on other machine?

**Comment by JohannBlake** [comment]
Unfortunately I only have my laptop. I also tried deleting the Electron cache but that didn't help either. When I update Electron from 1.6.11 to the latest version, some setting must have gotten cached somewhere that is preventing the default browser from being used. You are not seeing the issue probably because you've updated several times from 1.6.11 and the issue disappeared. But I have only updated from that older version to the latest. That is a hint that something is almost certainly wrong with Electron.

**Comment by JohannBlake** [comment]
I should also point out that in Slack I typed a url and then clicked on it. It launches the default browser correctly.

**Comment by JohannBlake** [comment]
I decided to give up pursuing this any further and was able to launch external urls with the default browser using this code:

```
const open = require('open');
open('https://www.google.com');
```

You can install this package from:
[https://www.npmjs.com/package/open](https://www.npmjs.com/package/open)

I hope you determine what the problem is because it's clearly with Electron.

**Comment by JohannBlake** [comment]
Taking one last stab at it I discovered what was causing the problem and it clearly was something that changed from the previous version of Electron.

In my main process I had the following code:

```
let win = new BrowserWindow(opts);
win.webContents.on('new-window', function(e, url) {
        e.preventDefault();
        require('electron').shell.openExternal(url);
    });
```
I can't exactly recall why I had this but I believe it was to capture any windows that got launched if the user clicked on a hyperlink in content and I wanted to avoid opening up an internal window. I wanted the external browser used instead.

However, in my app I have links that you can click on that are meant to open up in an external browser. In various render processes I had the following:

```
var shell = require('electron')["shell"];
shell["openExternal"](url);
```

This is the typical way of launching the default browser and as stated, this always worked until I updated to the latest version of the Electron.

When I commented out the code in the main process, the problem was fixed. Something in Electron's behaviour has changed. This also explains why you were not seeing it because you probably did not have the code in the main module I was using.

**Comment by JLarky** [comment]
Updating to chrome 63 solves the issue.

**Comment by JLarky** [comment]
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=777863 (still not fixed)
workaround is to restart chrome
In order to see that this is chrome/os bug, not electron bug, just go in terminal and run `open "http://google.com"` it will have the same issue as electron has at the same time.
