### ISSUE TITLE
issue with live media audio.

### ISSUE THREAD

**Issue by ColinMoulds** [electron/electron#11112]
* Electron version: 1.7.9
* Operating system: windows10

### Expected behaviour
for instance, i mirrored a mixer.com stream link from which I expect it to play as usual on chrome.

### Actual behaviour

the stream loop loads and PowerShell outputs the error
[8044:1113/231153.491:ERROR:rtpreceiver.cc(59)] AudioRtpReceiver::OnSetVolume: No audio channel exists.

not sure if there is some code I am missing to do this (i just started using electron).

### How to reproduce

  $ git clone https://github.com/ColinMoulds/KillerSquad-Dekstop-App.git
  $ npm install
  $ npm start || electron .

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by msach22** [comment]
Hi @sofianguy, just wanted to say that this issue is still reproducible with the latest version of Electron when you're using the WebRTC APIs. If you run the following code in an Electron application, you'll notice the `AudioRtpReceiver::OnSetVolume: No audio channel exists.` log in the terminal:


```
const pc1 = new RTCPeerConnection();
const pc2 = new RTCPeerConnection();

let desc = null;

let incomingStream = new MediaStream();
const incomingVideoElement = document.createElement('video');
incomingVideoElement.srcObject = incomingStream;
const isAdded = false;
pc2.ontrack = (event) => {
  incomingStream.addTrack(event.track);
  if (event.track.kind === 'video') {
    document.body.appendChild(incomingVideoElement);
    incomingVideoElement.play()
    isAdded = true;
  }
}

const noAction = () => {

};

const errorHandler = (e) => {
  console.log(e);
}

const start = async () => {
  
  pc1.onicecandidate = (event) => {
    if (event.candidate) {
      pc2.addIceCandidate(new RTCIceCandidate(event.candidate, noAction, (error) => {
        errorHandler(`PC2 adding ice candidate erorr ${error}`);
      }));
    }
  };
  
  pc2.onicecandidate = (event) => {
    if (event.candidate) {
      pc1.addIceCandidate(new RTCIceCandidate(event.candidate, noAction, (error) => {
        errorHandler(`PC1 adding ice candidate erorr ${error}`);
      }));
    }
  };

  try {
    let description = await pc1.createOffer();
    desc = description;
    pc1.setLocalDescription(description);
    pc2.setRemoteDescription(description);
    let description2 = await pc2.createAnswer();
    pc2.setLocalDescription(description2);
    pc1.setRemoteDescription(description2);
  } catch (e) {
    errorHandler(e);
  }

};

(async () => {
  stream = null;
  try {
    stream = await navigator.mediaDevices.getUserMedia({
      audio: true,
      video: true
    });
    const videoElement = document.createElement('video');
    videoElement.srcObject = stream;
    document.body.appendChild(videoElement);
    await videoElement.play()
    for (let track of stream.getTracks()) {
      pc1.addTrack(track);
    }
    await start();
  } catch (error) {
    console.log('error getting media', error);
  }
  return stream;
})()
```

**Comment by LukRaik** [comment]
I have same issue, any workarounds ?

**Comment by superddr** [comment]
I have the same issue, how can we reopen this..

**Comment by LaPhroaig10Y** [comment]
I encountered the same issue, for me it worked to switch the version of electron back to 2.0.8.
With the older version, the error is fixed. Don´t ask me why though.

**Comment by TheDigiBusiness** [comment]
We are having the same issue, can confirm that v. 2.* of electron works

**Comment by jsheffers** [comment]
Tested on version 7.1.1 (the latest as of this comment), still receiving this notice.

**Comment by nightillusions** [comment]
Still getting this error on version 8.0.1 (the latest as of this comment)

**Comment by MinhPhu0304** [comment]
Hi guys, I having the same issue on version 8.2.0  (the latest as of this comment)
Running MacOS 10.14.6

**Comment by bfamchon** [comment]
Testing on new 8.2.3, still having this issue with our webrtc based call system between web app and electron app.
Our app upgrade from V5 to V7 few month ago, I think we don't face the issue before but we're currently investigating.
We're checking on older versions too, like 5.X or 6.X to see if we got the case again.

**Comment by miladmeidanshahi** [comment]
Our app is going to failed with this bug :|

electron 9.2.0
```
281061:0811/113648.792303:ERROR:audio_rtp_receiver.cc(89)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
```

**Comment by tothbenedek** [comment]
The issue still exists in electron 11.0.1. The latest version where it worked is 5.0.13

**Comment by kalpeshims** [comment]
facing same issue in electron v9.0.5

`[14334:0227/162009.250501:ERROR:audio_rtp_receiver.cc(89)] AudioRtpReceiver::OnSetVolume: No audio channel exists.`

is there any solution without upgrading electron version ???

thanks.

**Comment by PxlLoewe** [comment]
I have the same issure with peerJS and webrtc. Loading a site in electron with `mainWindow.loadURL`. In the browser, this works but in Electron it throws there errors in the console: 

> [4712:0611/224806.608:ERROR:audio_rtp_receiver.cc(95)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
> 
> [4712:0611/224846.392:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.2.x:52325 ({653D86EF-2890-4553-8A92-A3CB302B2D3A})[4712:0611/224913.403:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.2.x:53675 ({653D86EF-2890-4553-8A92-A3CB302B2D3A})

Has anyone a solution?

**Comment by ngohuytrieu** [comment]
Hi @sofianguy, I am creating one electron on macOS, inside load URL to another domain. That domain uses WEBRTC for calling, but on macOS app I have this issue:
`AudioReceiver::OnSetVolume: No audio channel exists.`
Electron version: 7.1.1
