### ISSUE TITLE
Typing in devtools crashes app

### ISSUE THREAD

**Issue by mbroxson-qrs** [electron/electron#11375]
* Electron version: 1.8.2-beta.3
* Operating system: Windows_NT 10.0.15063

### Expected behavior

When devtools are open I should be able to type directly into the console.

### Actual behavior

When you type into the console in devtools it crashes the electron app without showing any errors.

### How to reproduce

```
git clone https://github.com/electron/electron-api-demos.git
cd electron-api-demos
npm install --save-dev electron@1.8.2-beta.3
npm install
npm start
```

When the electron window opens, go to View menu, then Toggle Developer Tools option.
Go to Console tab.
Click into the console by the > and start typing anything.

**Comment by brenca** [comment]
I think #11233 should fix this, tho I have only tested it in osr mode.

**Comment by sofianguy** [comment]
Let us know if #11233 doesn't solve your issue, we would be happy to reopen this issue.
