### ISSUE TITLE
Some emojis are not displayed properly

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#11874]
* Electron version: 1.8.2
* Operating system: macOS 10.13.3

### Expected behavior

The emoji shouldn't have the strange symbol at the end

### Actual behavior

![image](https://user-images.githubusercontent.com/884810/36032789-c654b224-0db7-11e8-8c4b-eed4282f662f.png)

### How to reproduce

Select the emoji from Ctrl+Cmd+Space menu under Mac. 
![image](https://user-images.githubusercontent.com/884810/36032853-fade3178-0db7-11e8-8cc6-cb3351fbc658.png)

**Comment by vincelwt** [comment]
This is not an Electron bug. This can be reproduced in Chrome (try here in the comments) and is a problem with how OSX outputs emojis. As a workaround you can use png images of the emojis, this will also make a better cross-platform experience.

**Comment by astoilkov** [comment]
If you put `font-family: sans-serif` on the input you are trying the problem will be fixed. However, this approach doesn't work in Electron.

**Comment by astoilkov** [comment]
As an example you can take a look at https://www.notion.so/. Their online version works correctly but the Electron Desktop version which is the same code as the online version doesn't work correctly.

**Comment by codebytere** [comment]
Closing as this has been resolved in later versions of Chrome and by extension Electron.

**Comment by iKBAHT** [comment]
> Closing as this has been resolved in later versions of Chrome and by extension Electron.

@codebytere we have that problem on Electron v3.0.3 (with Chrome 66 inside), but on Chrome 66 everything is working fine.

**Comment by felixfbecker** [comment]
I am experiencing this issue with latest Electron 4.0.1.
Setting `font-family` to `sans-serif` does not fix it.
Using png is not an option because I specifically want to use the native emoji style of the OS.
It works fine in Chrome.
