### ISSUE TITLE
memory leak with multiple open/close BrowserWindows and using affinity

### ISSUE THREAD

**Issue by westacotta** [electron/electron#12027]
* Electron version: 2.0.0-beta.1
* Operating system: Windows 7

### Expected behavior
Not leak!

### Actual behavior

Leaks memory at the closing of each new same affinity browser window

### How to reproduce

1. Create a BrowserWindow with affinity of 'test'
2. Have a way of creating and closing a child window with a basic renderer html with affinity of 'test'
3. each cycle leaks a large amount of memory

This occurs no matter what is in the renderer html.
Occurs whether or not you hook any browserwindow events
Doesn't occur if you DON'T call loadUrl. (obviously not much use)

**Comment by KochiyaOcean** [comment]
An example can be found in https://github.com/KochiyaOcean/electron-bugs/tree/affinity-memory-leak
Memory usage on startup:
![image](https://user-images.githubusercontent.com/8194131/37382654-3e64f074-2787-11e8-8109-9c0a51c8acaf.png)
About 30s later:
![image](https://user-images.githubusercontent.com/8194131/37382662-4865ec22-2787-11e8-924e-f7928a2d0cb2.png)

**Comment by Hammster** [comment]
+1 I also encountered this issue today, this also happens when i reaload via `ctrl+r` with focused devtools

**Comment by localh0rzd** [comment]
+1 encountered while using multiple `<webview>` sharing one affinity. Creating and later removing the WebView leaks memory.

**Comment by Gvozd** [comment]
+1
Also, after restarting the window, the time of file operations increases
Before rebooting around 20ms
After a reboot, it ranges from 500ms to 22 seconds

**Comment by jaehayoo** [comment]
So, Is there any update for this issue?

**Comment by Garbee** [comment]
This is not just Windows. It also affects MacOS. Since it exists here, I'd suspect it does the same on Linux. Manual testing on Linux hasn't happened yet to confirm.

**Comment by guox191** [comment]
@localh0rzd same as you, did you have any solutions?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Garbee** [comment]
The problem is still occurring on Electron 6.0.1 using the test provided by @KochiyaOcean.

**Comment by Ter01an** [comment]
Is there a way to free memory before the problem is resolved? I call a lot of windows and rest on the fact that the application crashes at some point

**Comment by ewok-janitor** [comment]
I was getting a memory leak in a similar situation (not using affinity).  Opening and closing BrowserWindows leaks "BrowserWindow" objects.  They appear to be rooted to a GC handle.  I was also getting messages in the console about "too many event listeners".

I was able to fix the "too many event listeners" by this code:
```
    this.browserWindow.on('close', (e)=>{
      app.removeAllListeners("browser-window-created")
    });
```

I do not know how to fix the GC root issue.

**Comment by Jun90925** [comment]
The problem is still occurring on Electron 8.4.0, macos. Close a BrowserWindow does not free the memory of main process.
The memory of main process will keep rising when open BrowserWindows.

**Comment by dingchaoyan1983** [comment]
any update for this issue?

**Comment by Garbee** [comment]
10.x is [planning to remove affinity](https://www.electronjs.org/docs/breaking-changes#removed-browser-window-affinity) so plan for this functionality to no longer exist shortly unless something changes with the plans.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by knownasilya** [comment]
Still an issue, even without affinity
