### ISSUE TITLE
Format selection in Save/Open dialog causes crash

### ISSUE THREAD

**Issue by teslor** [electron/electron#12230]
Electron version: 2.0.0-beta.2
Operating system: macOS 10.13.3

**Expected behavior**
In dialogs (dialog.showSaveDialog(), dialog.showOpenDialog()) Format selector should work.

**Actual behavior**
Selecting other format from the list causes app crashing. Sometimes (in open dialog) it works, but in most cases it crashes.

**How to reproduce**
Call save or open dialog with e.g. this filter - filters: [{ name: 'HTML files', extensions: ['html', 'htm']}] and try to select "html".

**Comment by codebytere** [comment]
Is there anything else I need to do to trigger the crash? Just tried to repro with 
```
const { app, dialog } = require('electron')

app.on('ready', () => {
  const showSaveDialogOptions = {
    properties: ['openFile'],
    filters: [{
      name: 'HTML files',
      extensions: ['html', 'htm']
    }]
  }

  dialog.showSaveDialog(showSaveDialogOptions, (selectedFiles) => {
    console.log(selectedFiles)
  })
})
```
and flipping back and forth between formats  i can't reproduce a crash

**Comment by teslor** [comment]
Thanks @codebytere for checking. Your code for me also works. But my code has differences.

I did some experimenting and found out that crash occurs when one of these conditions is met:
1) browserWindow is passed as first parameter to dialog function (so the dialog is attached to main window)
2) A dialog is called by ipc request (I send a message to main process from renderer process to show a dialog)

Fixing only one item doesn't help in my case.
To fix 2 I tried to send message in setTimeout function, so instead of ipc.send('save-file-dialog') I used setTimeout(() => { ipc.send('save-file-dialog') }). I don't know why but it helped. So for me the current workaround is to use setTimeout when sending ipc messages and not to pass browserWindow.
What do you think about it?

Also I have some related questions:
1) Is it possible to set main format for the dialog? I want it to be 'html', not 'htm'. On Windows it is 'html' with the same dialog parameters.
2) Selector works a bit incorrectly. When selecting new format the files that match this format stay grayed, only clicking on some file makes the files to have proper colors.

**Comment by codebytere** [comment]
hmm ok, i repro'd the crash and it dies per `lldb` with the following:
```
Process 38696 stopped
* thread #1, name = 'CrBrowserMain', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x18)
    frame #0: 0x00007fff6897de9d libobjc.A.dylib`objc_msgSend + 29
libobjc.A.dylib`objc_msgSend:
->  0x7fff6897de9d <+29>: andl   0x18(%r10), %r11d
    0x7fff6897dea1 <+33>: shlq   $0x4, %r11
    0x7fff6897dea5 <+37>: addq   0x10(%r10), %r11
    0x7fff6897dea9 <+41>: cmpq   (%r11), %rsi
Target 0: (Electron) stopped.
```

**Comment by codebytere** [comment]
This should be resolved by https://github.com/electron/electron/pull/11959.

**Comment by jonathon-love** [comment]
hi,

i'm using the current 2.0 release, and this is still an issue for me. if i run it with `lldb` as above, it gives exactly the same output.

```
Process 65892 stopped
* thread #1, name = 'CrBrowserMain', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x18)
    frame #0: 0x00007fff564cde9d libobjc.A.dylib`objc_msgSend + 29
libobjc.A.dylib`objc_msgSend:
->  0x7fff564cde9d <+29>: andl   0x18(%r10), %r11d
    0x7fff564cdea1 <+33>: shlq   $0x4, %r11
    0x7fff564cdea5 <+37>: addq   0x10(%r10), %r11
    0x7fff564cdea9 <+41>: cmpq   (%r11), %rsi
Target 0: (jamovi) stopped.
```

with thanks
