### ISSUE TITLE
Invisible menu on Linux

### ISSUE THREAD

**Issue by alespergl** [electron/electron#12275]
* Electron version: 2.0.0-beta.3
* Operating system: Ubuntu 16.04.04 LTS

### Expected behavior

App menu should be visible

### Actual behavior

App menu is invisible

### How to reproduce

- Run `electron`
- Observe that the app menu is invisible. It is still possible to open submenus.

![screenshot from 2018-03-14 17-01-18](https://user-images.githubusercontent.com/19880051/37415303-7296c25e-27ab-11e8-8284-d213c8bf5230.png)

**Comment by bpasero** [comment]
@alespergl I do not see that. Just installed a fresh Ubuntu 16.04 LTS running via Parallels on macOS:

![image](https://user-images.githubusercontent.com/900690/37421716-52d66f96-27ba-11e8-9143-6bcaf549d9b1.png)

**Comment by ckerr** [comment]
Interesting! I'm not seeing this in 17.10. I'll see if I can reproduce the behavior in 16.04 LTS.

![menu-ubuntu-17 10-radiance-theme](https://user-images.githubusercontent.com/70381/37429929-148e4790-2814-11e8-9c6f-6add5bba22fa.png)

**Comment by ckerr** [comment]
I'm seeing this behavior when running in the Adwaita-dark theme. Inspiration by @bjornharrtell's comment at https://github.com/Microsoft/vscode/issues/45542#issuecomment-373152885

**Comment by alespergl** [comment]
LibreOffice had the same issue.
https://bugs.documentfoundation.org/show_bug.cgi?id=101471

They seem to have patched it with
https://cgit.freedesktop.org/libreoffice/core/commit/?id=72eb18e520ea8165a6a20958a1551f55e5e14cab

**Comment by alexeykuzmin** [comment]
It seems like the fix has been merged to the `2-0-x` branch.

**Comment by jainsuchita** [comment]
![screenshot from 2018-11-19 16-48-59](https://user-images.githubusercontent.com/4988234/48704275-1fb51280-ec1c-11e8-88eb-3da0dbdb4d07.png)

Electron Version - 4.0.0-beta.6
Operating system: Ubuntu 18.10

Guys, I am still facing the issue.
Any update on this?

**Comment by ckerr** [comment]
According to Trish at Slack QA, this is still reproducible in both Electron 3 & 4.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by johnosbb** [comment]
Still observable on Ubuntu 16.04 running electron version 
electron --version = v8.0.1
run electron or any electron based application. No menus are shown.

**Comment by johnosbb** [comment]
I am new to Electron, but I can try to debug this on my system if someone has some suggestions on where to look initially.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
