### ISSUE TITLE
Tray icon regression

### ISSUE THREAD

**Issue by akontsevich** [electron/electron#13000]
* Electron Version: 2.0.1
* Operating System (Platform and Version): Linux openSUSE Tumbleweed
* Last known working Electron version: 1.x

**Expected Behavior**
Normal application icon ([Riot](https://github.com/vector-im/riot-web))

**Actual behavior**
Purple square in sys tray (KDE)

**To Reproduce**
- Install latest Riot version  0.15.2 with Electron 2.0.1: https://about.riot.im/downloads/
-  Run it in KDE 5

**Comment by MarshallOfSound** [comment]
Reading through the referenced issue in `riot-web` this appears to be defined but them as not a regression but the way it has always worked and:

> OK, it’s a known bug on KDE

I'm going to close this out based on that input downstream, if the resolution of the downstream issue is that Electron changed something I'll be happy to revisit this 👍

**Comment by akontsevich** [comment]
@MarshallOfSound please reopen. It is not KDE bug: it was fixed about half a year ago: https://bugs.kde.org/show_bug.cgi?id=382728. Icons works fine if [Free Desktop specifications](https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-latest.html) are used. When KDE bug was fixed icon was normal in Riot 0.14.x (Electron 1.8.7) and now purple square in Riot 0.15.x (Electron 2.0.1). So definitely a regression or non-standard tray icon usage. More info: https://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/

**Comment by MarshallOfSound** [comment]
@akontsevich The linked KDE bug was closed as `WONTFIX`, in my mind that means they have not actually fixed the issue on their end.

FWIW the major change from `1.8.x` to `2.0.x` that could affect this is the move from GTK2 to GTK3, I'd suggest raising this on that KDE ticket

**Comment by akontsevich** [comment]
@MarshallOfSound  any other GTK3 applications icons works just fine in KDE :) In some thread David Edmundson said to me he fixed some: Riot started to look fine after this.

**Comment by ckerr** [comment]
@MarshallOfSound, I think this is worth some investigation

Also, from a cursory reading this _may_ be the same as https://github.com/electron/electron/issues/12791? @akontsevich if you think so to, let's leave this closed as a duplicate and move discussion to that ticket.

**Comment by akontsevich** [comment]
@ckerr  ok, np, let's use whatever ticket if this helps to solve the issue. Left note there as well.
