### ISSUE TITLE
OOPIF webview freezes occasionally on navigation

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#14211]
* Electron Version: v3.0.0-nightly.20180818
* Operating System (Platform and Version): Windows 10 1803
* Last known working Electron version: v3.0.0-beta.5

**Expected Behavior**
webview will not be freezed

**Actual behavior**
webview freezed occasionlly on navigation

**To Reproduce**
1. clone https://github.com/KochiyaOcean/electron-bugs

2. run `electron .` using electron v3.0.0-nightly.20180818

3. run scripts below in devtools
```javascript
require('electron').remote.webContents.getAllWebContents()
```
![image](https://user-images.githubusercontent.com/8194131/44320386-bf77ce80-a47c-11e8-9371-4e89cec444db.png)
there are 3 webcontents (BrowserWindow, WebView, DevTool)

4. run scripts below in devtools
```javascript
document.querySelector('webview').addEventListener('did-finish-load', () => document.querySelector('webview').loadURL('http://dmm.com'))
document.querySelector('webview').loadURL('http://dmm.com')
```

5. webview will freeze occasionally, and call any method of webview will throw an error
![image](https://user-images.githubusercontent.com/8194131/44320462-0b2a7800-a47d-11e8-9b21-3033df0372c4.png)

6. run `require('electron').remote.webContents.getAllWebContents()` again, and there are only 2 webcontents left (webcontents of webview is removed)
![image](https://user-images.githubusercontent.com/8194131/44320488-3c0aad00-a47d-11e8-99db-634428b1198c.png)

**Additional Information**
This bug occurs easier on complex websites, such as https://amazon.com , https://ebay.com , etc.

**Comment by sofianguy** [comment]
We released `3.0.0-beta.6` today. Can you give [`3.0.0-beta.6`](https://github.com/electron/electron/releases/tag/v3.0.0-beta.6) a try and let us know if you are still running into this issue?

**Comment by KochiyaOcean** [comment]
@sofianguy It still occurs in electron@3.0.0-beta.6
![image](https://user-images.githubusercontent.com/8194131/44376067-bdbc1280-a531-11e8-9c3c-01cd68d99bc4.png)

**Comment by ckerr** [comment]
Judging from that trace, this is possibly a regression caused by the 3.0.0-beta.6 asar changes in https://github.com/electron/electron/pull/14031 https://github.com/electron/electron/pull/14118

It's unclear to me if `2-0-x` was exposed to any of these changes. From https://github.com/electron/electron/pull/14039#issuecomment-412404469 it looks like the answer is 'no' but @KochiyaOcean would it be possible for you to re-run this test in `2.0.8`? It would be best to make sure the fix lands everywhere it's needed.

**Comment by KochiyaOcean** [comment]
still not fixed in 3.0.0-beta.8

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/44926717-5bfb7400-ad8d-11e8-8394-15b0b960d5f9.png)
Before crash, `'did-start-navigation'` event of webview's webContents sends a false `frameProcessId`
(Correct value is 45 but the webContent sends 46

**Comment by KochiyaOcean** [comment]
seems to be problem of some edge case of SiteInstance.
https://github.com/electron/electron/blob/bce5bd87a8308c5eaba2057e8412bcc0a3065552/atom/browser/atom_browser_client.cc#L288

**Comment by zcbenz** [comment]
I'm reproduce this bug with Release build of Electron, for Debug build the main process will crash with:

```
[7548:0903/153202.304238:FATAL:render_frame_proxy_host.cc(257)] Check failed: frame_tree_node_->IsMainFrame(). 
0   libbase.dylib                       0x0000000111a81f0e base::debug::StackTrace::StackTrace(unsigned long) + 174
1   libbase.dylib                       0x0000000111a81f9d base::debug::StackTrace::StackTrace(unsigned long) + 29
2   libbase.dylib                       0x0000000111a81f6c base::debug::StackTrace::StackTrace() + 28
3   libbase.dylib                       0x0000000111b3b40c logging::LogMessage::~LogMessage() + 460
4   libbase.dylib                       0x0000000111b2a7f5 logging::LogMessage::~LogMessage() + 21
5   libcontent.dylib                    0x000000011c60aa71 content::RenderFrameMessageFilter::GetPluginsCallback(IPC::Message*, url::Origin const&, std::__1::vector<content::WebPluginInfo, std::__1::allocator<content::WebPluginInfo> > const&) + 11905
6   libcontent.dylib                    0x000000011c712fb1 non-virtual thunk to content::GpuFeatureCheckerImpl::OnGpuInfoUpdate() + 914433
7   libcontent.dylib                    0x000000011c712f28 non-virtual thunk to content::GpuFeatureCheckerImpl::OnGpuInfoUpdate() + 914296
8   libcontent.dylib                    0x000000011c712e95 non-virtual thunk to content::GpuFeatureCheckerImpl::OnGpuInfoUpdate() + 914149
9   libcontent.dylib                    0x000000011c60a92c content::RenderFrameMessageFilter::GetPluginsCallback(IPC::Message*, url::Origin const&, std::__1::vector<content::WebPluginInfo, std::__1::allocator<content::WebPluginInfo> > const&) + 11580
10  libcontent.dylib                    0x000000011c60a499 content::RenderFrameMessageFilter::GetPluginsCallback(IPC::Message*, url::Origin const&, std::__1::vector<content::WebPluginInfo, std::__1::allocator<content::WebPluginInfo> > const&) + 10409
11  libcontent.dylib                    0x000000011ceb34d3 content::RenderProcessHostImpl::OnMessageReceived(IPC::Message const&) + 835
```

The WebContents seems to be intentionally destroyed instead of crashed.

**Comment by zcbenz** [comment]
Stack trace when the webview's WebContents is destroyed.

```
* thread #1: tid = 0x1b53de, 0x0000000100105140 Electron Framework`atom::api::WebContents::WebContentsDestroyed(this=0x00000001078c3b10) at atom_api_web_contents.cc:1054, name = 'CrBrowserMain', queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x0000000100105140 Electron Framework`atom::api::WebContents::WebContentsDestroyed(this=0x00000001078c3b10) at atom_api_web_contents.cc:1054 [opt]
    frame #1: 0x0000000100105320 Electron Framework`non-virtual thunk to atom::api::WebContents::WebContentsDestroyed(this=<unavailable>) + 16 at atom_api_web_contents.cc:0 [opt]
    frame #2: 0x00000001006aaa71 Electron Framework`content::WebContentsImpl::~WebContentsImpl(this=0x0000000108104a00) + 2049 at web_contents_impl.cc:674 [opt]
    frame #3: 0x00000001006ab3ce Electron Framework`content::WebContentsImpl::~WebContentsImpl() [inlined] content::WebContentsImpl::~WebContentsImpl(this=0x0000000108104a00) + 14 at web_contents_impl.cc:586 [opt]
    frame #4: 0x00000001006ab3c9 Electron Framework`content::WebContentsImpl::~WebContentsImpl(this=0x0000000108104a00) + 9 at web_contents_impl.cc:586 [opt]
    frame #5: 0x00000001008c8060 Electron Framework`content::FrameTreeNode::~FrameTreeNode(this=0x0000000107b0b6b0) + 400 at frame_tree_node.cc:197 [opt]
    frame #6: 0x00000001008c607e Electron Framework`content::FrameTreeNode::RemoveChild(content::FrameTreeNode*) [inlined] content::FrameTreeNode::~FrameTreeNode() + 238 at frame_tree_node.cc:178 [opt]
    frame #7: 0x00000001008c6076 Electron Framework`content::FrameTreeNode::RemoveChild(content::FrameTreeNode*) [inlined] std::__1::default_delete<content::FrameTreeNode>::operator()(content::FrameTreeNode*) const at memory:2333 [opt]
    frame #8: 0x00000001008c6076 Electron Framework`content::FrameTreeNode::RemoveChild(content::FrameTreeNode*) [inlined] std::__1::unique_ptr<content::FrameTreeNode, std::__1::default_delete<content::FrameTreeNode> >::reset(content::FrameTreeNode*) + 5 at memory:2646 [opt]
    frame #9: 0x00000001008c6071 Electron Framework`content::FrameTreeNode::RemoveChild(this=0x0000000107a37ff0, child=0x0000000107b0b6b0) + 225 at frame_tree_node.cc:257 [opt]
    frame #10: 0x0000000100906036 Electron Framework`bool IPC::MessageT<FrameHostMsg_Detach_Meta, std::__1::tuple<>, void>::Dispatch<content::RenderFrameProxyHost, content::RenderFrameProxyHost, void, void (content::RenderFrameProxyHost::*)()>(IPC::Message const*, content::RenderFrameProxyHost*, content::RenderFrameProxyHost*, void*, void (content::RenderFrameProxyHost::*)()) [inlined] void base::DispatchToMethodImpl<content::RenderFrameProxyHost*, void (content::RenderFrameProxyHost::*)(), std::__1::tuple<> >(method=<unavailable>)(), std::__1::tuple<>&&, std::__1::integer_sequence<unsigned long>) + 24 at tuple.h:52 [opt]
    frame #11: 0x000000010090601e Electron Framework`bool IPC::MessageT<FrameHostMsg_Detach_Meta, std::__1::tuple<>, void>::Dispatch<content::RenderFrameProxyHost, content::RenderFrameProxyHost, void, void (content::RenderFrameProxyHost::*)()>(IPC::Message const*, content::RenderFrameProxyHost*, content::RenderFrameProxyHost*, void*, void (content::RenderFrameProxyHost::*)()) [inlined] void base::DispatchToMethod<content::RenderFrameProxyHost*, void (content::RenderFrameProxyHost::*)(), std::__1::tuple<> >(content::RenderFrameProxyHost* const&, void (content::RenderFrameProxyHost::*)(), std::__1::tuple<>&&) at tuple.h:60 [opt]
    frame #12: 0x000000010090601e Electron Framework`bool IPC::MessageT<FrameHostMsg_Detach_Meta, std::__1::tuple<>, void>::Dispatch<content::RenderFrameProxyHost, content::RenderFrameProxyHost, void, void (content::RenderFrameProxyHost::*)()>(IPC::Message const*, content::RenderFrameProxyHost*, content::RenderFrameProxyHost*, void*, void (content::RenderFrameProxyHost::*)()) [inlined] void IPC::DispatchToMethod<content::RenderFrameProxyHost, void (content::RenderFrameProxyHost::*)(), void, std::__1::tuple<> >(obj=<unavailable>)(), void*, std::__1::tuple<>&&) at ipc_message_templates.h:51 [opt]
    frame #13: 0x000000010090601e Electron Framework`bool IPC::MessageT<FrameHostMsg_Detach_Meta, std::__1::tuple<>, void>::Dispatch<content::RenderFrameProxyHost, content::RenderFrameProxyHost, void, void (msg=0x0000000107933dc8, obj=<unavailable>, sender=<unavailable>, parameter=<unavailable>, func=<unavailable>)()>(IPC::Message const*, content::RenderFrameProxyHost*, content::RenderFrameProxyHost*, void*, void (content::RenderFrameProxyHost::*)()) + 78 at ipc_message_templates.h:146 [opt]
    frame #14: 0x0000000100905f4e Electron Framework`content::RenderFrameProxyHost::OnMessageReceived(this=0x00000001164502b0, msg=0x0000000107933dc8) + 318 at render_frame_proxy_host.cc:150 [opt]
```

**Comment by zcbenz** [comment]
After some debugging, here is the information I know:

1. This bug only happens for pages that dynamically create and remove frames in it.
2. It happens because Chromium accidentally detached the wrong frame when reloading, Chromium should detach the old frame, but sometimes it accidentally detaches the new loaded frame.

I believe the is a bug of Chromium caused by race conditions when managing sub-frames.

**Comment by KochiyaOcean** [comment]
@zcbenz is this CL associated with this bug? https://chromium-review.googlesource.com/c/chromium/src/+/1165593

**Comment by zcbenz** [comment]
@KochiyaOcean Thanks for looking into it, but it does not seem to be related.
