### ISSUE TITLE
Broken image icon missing

### ISSUE THREAD

**Issue by c3er** [electron/electron#14426]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): Windows 10 1803, x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v.1.8.6

**Expected Behavior**

If an image could not be loaded, the browser should show an indicator icon as placeholder for the image.

**Actual behavior**

Nothing is displayed. If there is an alt text, this alt text will be displayed as plain text, without indication that this plain text belongs to an image.

**To Reproduce**

Use an `index.html` with this content:

```html
<html>
    <body>
        <img src="foo"/>
        <br/>
        <img src="foo" alt="bar"/>
    </body>
</html>
```

**Screenshots**

This screenshot shows the expected behavior in the current Chrome version 68:

![Screenshot of HTML above in current Chrome 68](https://user-images.githubusercontent.com/24460532/44962058-78c5b200-af1b-11e8-8986-c2d2346c4163.png)

Electron 2.0.8 would not show anything in the first line and only the alt text "bar" in the second line.

**Additional Information**

This bug corresponds to the fixed [Chomium issue 752103](https://bugs.chromium.org/p/chromium/issues/detail?id=752103).

**Comment by MarshallOfSound** [comment]
Hey @c3er as your discovered this is fixed in Chromium 62 which means we should have picked up the patch as part of our Chromium 63 upgrade that 66 upgrade that landed in `3.0.0`

**Comment by ManzerHa-Kore** [comment]
This issue is still there in electron version 4.1.1.   "alt" tag is not working properly and displaying broken image.
