### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by TheWebs** [electron/electron#14504]
Hi, i am trying to build electron however i keep getting the same error. I've tried the solutions mentioned in other issues but none of them work. When i run bootstrap i always get this error:

`> python ./script/bootstrap.py -v

Running in verbose mode
Your Python is using TLSv1.2, which is sufficient for building Electron.
git submodule sync --recursive
Synchronizing submodule url for 'vendor/boto'
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/crashpad'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/gyp'
Synchronizing submodule url for 'vendor/libchromiumcontent'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/boto'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/depot_tools'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/pyyaml'
Synchronizing submodule url for 'vendor/node'
Synchronizing submodule url for 'vendor/pdf_viewer'
Synchronizing submodule url for 'vendor/pdf_viewer/vendor/grit'
Synchronizing submodule url for 'vendor/requests'
git submodule update --init --recursive
error: The following untracked working tree files would be overwritten by checkout:
        .editorconfig
        .eslintignore
        .eslintrc.js
        .gitattributes
        .github/CODEOWNERS
        .github/ISSUE_TEMPLATE.md
        .github/PULL_REQUEST_TEMPLATE.md
        .gitignore
        .mailmap
        .nycrc
        .remarkrc
        AUTHORS
        BSDmakefile
        BUILD.gn
        BUILDING.md
        CHANGELOG.md
        CODE_OF_CONDUCT.md
        COLLABORATOR_GUIDE.md
        CONTRIBUTING.md
        CPP_STYLE_GUIDE.md
        GOVERNANCE.md
        LICENSE
        Makefile
        README.md
        android-configure
        benchmark/README.md
        benchmark/_benchmark_progress.js
        benchmark/_cli.R
        benchmark/_cli.js
        benchmark/_http-benchmarkers.js
        benchmark/_test-double-benchmarker.js
        benchmark/arrays/var-int.js
        benchmark/arrays/zero-float.js
        benchmark/arrays/zero-int.js
        benchmark/assert/deepequal-buffer.js
        benchmark/assert/deepequal-map.js
        benchmark/assert/deepequal-object.js
        benchmark/assert/deepequal-prims-and-objs-big-array-set.js
        benchmark/assert/deepequal-prims-and-objs-big-loop.js
        benchmark/assert/deepequal-set.js
        benchmark/assert/deepequal-typedarrays.js
        benchmark/assert/ok.js
        benchmark/assert/throws.js
        benchmark/async_hooks/gc-tracking.js
        benchmark/buffers/buffer-base64-decode-wrapped.js
        benchmark/buffers/buffer-base64-decode.js
        benchmark/buffers/buffer-base64-encode.js
        benchmark/buffers/buffer-bytelength.js
        benchmark/buffers/buffer-compare-instance-method.js
        benchmark/buffers/buffer-compare-offset.js
        benchmark/buffers/buffer-compare.js
        benchmark/buffers/buffer-concat.js
        benchmark/buffers/buffer-creation.js
        benchmark/buffers/buffer-fill.js
        benchmark/buffers/buffer-from.js
        benchmark/buffers/buffer-hex.js
        benchmark/buffers/buffer-indexof-number.js
        benchmark/buffers/buffer-indexof.js
        benchmark/buffers/buffer-iterate.js
        benchmark/buffers/buffer-normalize-encoding.js
        benchmark/buffers/buffer-read-float.js
        benchmark/buffers/buffer-read-with-byteLength.js
        benchmark/buffers/buffer-read.js
        benchmark/buffers/buffer-slice.js
        benchmark/buffers/buffer-swap.js
        benchmark/buffers/buffer-tojson.js
        benchmark/buffers/buffer-tostring.js
        benchmark/buffers/buffer-write-string.js
        benchmark/buffers/buffer-write.js
        benchmark/buffers/buffer-zero.js
        benchmark/buffers/dataview-set.js
        benchmark/child_process/child-process-exec-stdout.js
        benchmark/child_process/child-process-params.js
        benchmark/child_process/child-process-read-ipc.js
        benchmark/child_process/child-process-read.js
        benchmark/child_process/spawn-echo.js
        benchmark/cluster/echo.js
        benchmark/common.js
        benchmark/compare.R
        benchmark/compare.js
        benchmark/crypto/aes-gcm-throughput.js
        benchmark/crypto/cipher-stream.js
        benchmark/crypto/get-ciphers.js
        benchmark/crypto/hash-stream-creation.js
        benchmark/crypto/hash-stream-throughput.js
        benchmark/crypto/rsa-encrypt-decrypt-throughput.js
        benchmark/crypto/rsa-sign-verify-throughput.js
        benchmark/dgram/array-vs-concat.js
        benchmark/dgram/bind-params.js
        benchmark/dgram/multi-buffer.js
        benchmark/dgram/offset-length.js
        benchmark/dgram/single-buffer.js
        benchmark/dns/lookup.js
        benchmark/domain/domain-fn-args.js
        benchmark/es/defaultparams-bench.js
        benchmark/es/destructuring-bench.js
        benchmark/es/destructuring-object-bench.js
        benchmark/es/foreach-bench.js
        benchmark/es/map-bench.js
        benchmark/es/restparams-bench.js
        benchmark/es/spread-assign.js
        benchmark/es/spread-bench.js
        benchmark/es/string-concatenations.js
        benchmark/es/string-repeat.js
        benchmark/events/ee-add-remove.js
        benchmark/events/ee-emit.js
        benchmark/events/ee-listener-count-on-prototype.js
        benchmark/events/ee-listeners-many.js
        benchmark/events/ee-listeners.js
        benchmark/events/ee-once.js
        benchmark/fixtures/alice.html
        benchmark/fixtures/simple-http-server.js
        benchmark/fixtures/url-inputs.js
        benchmark/fs/bench-readdir.js
        benchmark/fs/bench-readdirSync.js
        benchmark/fs/bench-realpath.js
        benchmark/fs/bench-realpathSync.js
        benchmark/fs/bench-stat-promise.js
        benchmark/fs/bench-stat.js
        benchmark/fs/bench-statSync.js
        benchmark/fs/read-stream-throughput.js
        benchmark/fs/readFileSync.js
        benchmark/fs/readfile-partitioned.js
        benchmark/fs/readfile.js
        benchmark/fs/write-stream-through
Aborting
Unable to checkout '6d1bdd3ebf860ff878a1b5db4fd26fdda3932e21' in submodule path 'vendor/node'
None
Traceback (most recent call last):
`
* Node version: v8.11.2
* Windows 10 Pro

Thanks for helping!

**Comment by MarshallOfSound** [comment]
@TheWebs It looks like your `vendor/node` directory got into a bad state, if you delete it and re-run bootstrap it should fix itself.

**Comment by TheWebs** [comment]
I've done what you said and still no luck. However this time this apperared:
`fatal: cannot create directory at 'deps/npm/node_modules/libnpx/node_modules/yargs/node_modules/os-locale/node_modules/execa/node_modules/cross-spawn/node_modules/shebang-command/node_modules/shebang-regex': Filename too long
Unable to checkout '6d1bdd3ebf860ff878a1b5db4fd26fdda3932e21' in submodule path 'vendor/node'
None`
