### ISSUE TITLE
Call to `net.Socket.setTimeout(0)` has no effect in renderer in 3.0.0 - 3.0.2

### ISSUE THREAD

**Issue by jwulf** [electron/electron#14915]
* Output of `node_modules/.bin/electron --version`:
```
v3.0.2
```
* Operating System (Platform and Version):
```
Ubuntu 18.10
Ubuntu 18.04
Ubuntu 16.04
Mac OS 10.14
```
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
```
v2.0.10
```

**Expected Behavior**
A call to `net.Socket.setTimeout(0)` should clear the socket timeout.

**Actual behavior**
It works as expected in the main process, however it doesn't work in the renderer process. The timeout is not cleared.

Stepping through it in a debugger, Line 418 in the [Node.js `net.js`](https://github.com/nodejs/node/blob/8c70b2084ce5f76ea1e3b3c4ccdeee4483fe338b/lib/net.js#L418) has no effect in the renderer.

**To Reproduce**
Minimal reproducer here: [https://github.com/jwulf/electron-3-socket-bug](https://github.com/jwulf/electron-3-socket-bug)

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/jwulf/electron-3-socket-bug.git -b master
$ npm install
$ npm start
```

**Comment by jwulf** [comment]
Still happening in 3.0.13.

We are using Node.js 10.2.0, Chromium 66.0.3359.181, and Electron 3.0.13.

**Comment by luin** [comment]
Same issue here with Electron 4.0.0. Calling `Socket#setTimeout(0)` doesn't clear the timeout at all at the render process, causing all related modules not working.

```
socket.setTimeout(3000, () => {
  // the callback will still be invoked
})
socket.setTimeout(0)
```

**Comment by luin** [comment]
Digging into this issue. It seems caused by https://github.com/nodejs/node/blob/79aab5dd7cfe30f807b5d197c95aea9dd59ecb40/lib/net.js#L420 that `Socket#setTimeout()` uses `setUnrefTimeout` to create a timer that can't be cleared via `clearTimeout` https://github.com/nodejs/node/blob/79aab5dd7cfe30f807b5d197c95aea9dd59ecb40/lib/net.js#L413 (timer._destroyed is false after `clearTimeout`).

**Comment by warpdesign** [comment]
Has it been fixed in 4.x or 5.x?

**Comment by warpdesign** [comment]
@codebytere @sofianguy any follow up on this bug?

**Comment by codebytere** [comment]
@warpdesign just tested, this error still occurs in 4 and 5. I'll do my best to dig in soon.

**Comment by warpdesign** [comment]
@codebytere Thank you!

**Comment by dsanders11** [comment]
@warpdesign, @luin, @jwulf, I have a dirty hack which fixes this. See https://github.com/electron/electron/issues/18733#issuecomment-502591376 for a detailed explanation on why this works.

The hack is quick and dirty and not fun, but when you need to Get Stuff Done™️ it'll do the trick.

Use a preload script for the `BrowserWindow` to patch the `clearTimeout` global so that `net.Socket.setTimeout` works as expected.

When creating the `BrowserWindow`, provide a preload script:

```js
new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      preload: path.join(__dirname, 'preload.js')
    }
  })
```

And for the contents of `preload.js`:

```js
const { clearTimeout: nodeClearTimeout } = require('timers')

process.once('loaded', () => {
  const webClearTimeout = window.clearTimeout

  global.clearTimeout = arg => {
    if (arg === null) {
      return
    }

    if (arg.constructor && arg.constructor.name === 'Timeout') {
      nodeClearTimeout(arg)
    } else {
      webClearTimeout(arg)
    }
  }
})
```

**Comment by warpdesign** [comment]
@dsanders11 thanks, I need to test that out!

**Comment by dsanders11** [comment]
@warpdesign, I've updated it with a slightly better version (previously didn't handle `undefined` well). It's been working well for me though, haven't had timeout issues since adding it.

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/node/pull/107.
