### ISSUE TITLE
imp_uv_queue_work、imp_uv_default_loop no found on 4.0.0-nightly.20181006

### ISSUE THREAD

**Issue by luckywur** [electron/electron#15075]
* Output of `node_modules/.bin/electron --version`: 
4.0.0-nightly.20181006
* Operating System (Platform and Version):
Win7 x64

**Expected Behavior**
rebuild the native module [node-speaker](https://github.com/TooTallNate/node-speaker) on v4.0.0-nightly.20181006 failed.
`node-gyp rebuild --target=4.0.0-nightly.20181006 --arch=x64 --build-from-source --dist-url=https://atom.io/download/electron`
but build on v3.0.3 success

**Actual behavior**

```
binding.obj : error LNK2001: 无法解析的外部符号 __imp_uv_queue_work [D:\dev\workspace\xueliang\nvr_client\node_modules\speaker\build\binding.vcxproj]
binding.obj : error LNK2001: 无法解析的外部符号 __imp_uv_default_loop [D:\dev\workspace\xueliang\nvr_client\node_modules\speaker\build\binding.vcxproj]
D:\dev\workspace\xueliang\nvr_client\node_modules\speaker\build\Release\binding.node : fatal error LNK1120: 2 个无法解析的外部命令 [D:\dev\workspace\xueliang\nv
r_client\
node_modules\speaker\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\wcl\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wcl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.0
.0-nightly.20181006" "--arch=x64" "--build-from-source" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd D:\dev\workspace\xueliang\nvr_client\node_modules\speaker
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
```

**Comment by MarshallOfSound** [comment]
cc @nornagon this might be related to `electron.lib` vs `node.lib` 🤔

**Comment by nornagon** [comment]
It looks like we might not be exporting libuv symbols correctly, i'll look into it.

**Comment by adill** [comment]
I ran into this as well. `src\third_party\electron_node\deps\uv\BUILD.gn` is only setting `BUILD_UV_SHARED=1` when `is_component_build && is_win` is true.

I fixed it in our fork here https://github.com/discordapp/node/commit/d9e9760a8e0b664591b776f6a59bab3d0079b862

**Comment by nornagon** [comment]
hmm, i tried applying your patch locally and i'm still seeing errors about missing the `__imp_uv_default_loop` symbol. With that patch, it looks like electron.lib is exporting `uv_default_loop` but not `__imp_uv_default_loop`, which is confusing to me. @adill did you do anything else to get your build working?

**Comment by nornagon** [comment]
Ah, actually, nevermind—it works even though the symbols exported don't have `__imp` in them (at least, not as reported by `dumpbin /exports`). I'll update our libuv build.

**Comment by MarshallOfSound** [comment]
Fixed in #73
