### ISSUE TITLE
Paste and match style in webviews not working

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#15896]
* Output of `node_modules/.bin/electron --version`: v3.0.9
* Operating System (Platform and Version): macOS Mojave 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): ?

**Expected Behavior**
The menu role paste and match style should be able to paste in a `webview`.

**Actual behavior**
The menu role `pasteandmatchstyle` does no paste in a `webview`.
Though it does paste in a normal `BrowserWindow` and the role `paste`works well 

**To Reproduce**
Use https://github.com/alexstrat/electron-quick-start/tree/repro/pasteandmatchstyle

```sh
$ git clone https://github.com/alexstrat/electron-quick-start -b repro/pasteandmatchstyle
$ npm install
$ npm start
```

**Additional Information**
Seems related to #15219

**Comment by MarshallOfSound** [comment]
Potentially fixed by #15723

cc @brenca

**Comment by javan** [comment]
Confirmed this issue still exists in 4-0-x. Tested on macOS 10.14.2 / Electron 4.0.1.

**Comment by javan** [comment]
Note: `contents.pasteAndMatchStyle()` *does* work. Clicking the menu item or using its keyboard shortcut does not.

**Comment by javan** [comment]
Confirmed this issue exists in 5-0-x too.

**Comment by HaNdTriX** [comment]
Confirmed this issue exists in v7.0.0-beta.6 too.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
