### ISSUE TITLE
4.0 regression: chrome://resources/js/util.js fails to load (net::ERR_FAILED) on chrome://webrtc-internals/

### ISSUE THREAD

**Issue by bughit** [electron/electron#16006]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.8 x86
* Operating System (Platform and Version): win7 sp1 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.1.0-beta.2 x86

**Expected Behavior**
chrome://webrtc-internals/ loading without errors

**Actual behavior**
chrome://resources/js/util.js fails to load

**To Reproduce**

run
```js
'use strict';

const {app, BrowserWindow} = require('electron');

let win;

app.on('ready', async () => {

  win = new BrowserWindow({
    width: 1440,
    height: 900,
    useContentSize: true,
    webPreferences: {
      nodeIntegration: false,
    },
  });

  win.loadURL('chrome://webrtc-internals/');

  win.webContents.openDevTools({mode: 'right'});

});
```

**Screenshots**
![image](https://user-images.githubusercontent.com/895588/49768461-760cf280-fcaa-11e8-8c06-78f9c077bb87.png)

**Comment by nornagon** [comment]
thanks, looks like we missed that resource bundle in the switch to GN. #16009 should fix it.

**Comment by erlichmen** [comment]
Seem like this issue is back (at least the symptom I don't know about the cause) in v8.0.1.
In v7.1.11 it was still working, something broke it in V8.

I tried to run the window with and without "webSecurity: false" and in both cases, I get an empty window.

ELECTRON_ENABLE_LOGGING=true didn't show anything interesting (but it doesn't show anything in v7 were it works also)
