### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'nodeIntegration' of null" logged when renderer devtools are opened

### ISSUE THREAD

**Issue by bughit** [electron/electron#16114]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.10
* Operating System (Platform and Version): win7 sp1 x64

**Expected Behavior**
no error

**Actual behavior**
```
 [4692:1217/192827.998:ERROR:CONSOLE(253)] "Uncaught TypeError: Cannot read property 'nodeIntegration' of null", source: C:\path\to\electron-v4.0.0-beta.10-win32-ia32\resources\electron.asar\renderer\security-warnings.js (253)
```

**To Reproduce**
run
```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      START_URL = 'about:blank';

let win;

app.on('ready', () => {

  win = new BrowserWindow({
    width: 1440,
    height: 900,
    useContentSize: true,
    webPreferences: {
      nodeIntegration: false
    },
  });

  win.loadURL(START_URL);
  win.webContents.openDevTools({mode: 'right'});

});
```

**Comment by nornagon** [comment]
I think this is fixed by #16116

**Comment by zadam** [comment]
I'm getting this error on 4.0-beta.11. App otherwise works without problem.

**Comment by bengotow** [comment]
Hey folks—can confirm that this still happens in the 4.0-beta.11.

**Comment by bughit** [comment]
@nornagon please reopen

**Comment by wjehenddher** [comment]
It doesn't seem to happen in 4.1.1 but it happens in beta.10.

**Comment by nornagon** [comment]
Yeah I believe #16152 closed this.
