### ISSUE TITLE
Electron 4.0.0: webContents.print() must be called twice or with an empty object

### ISSUE THREAD

**Issue by c3er** [electron/electron#16219]
* Output of `node_modules/.bin/electron --version`: v4.0.0
* Operating System (Platform and Version): Windows 10 64 Bit, Version 1809
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.13

**Expected Behavior**

If I call `webContents.print()`, the print dialog shall open. If I give a callback function, the callback shall be called.

**Actual behavior**

I must call `webContents.print()` twice before the print dialog opens. There is a workaround: If I give an empty object as parameter, the behavior is as expected: `webContents.print({})`

Additionally, I observed that the callback, if given, gets not called. This works also as expected under Electron 3.0.13.

**To Reproduce**

I made a repository with multiple examples to the described behavior.

To clone the repository:

```
$ git clone https://github.com/c3er/electronPrintingIssue.git
```

All examples should start after typing the following commands in their respective directories:

```
$ npm install
$ npm start
```

You can either click File -> Print in the main menu or press `Ctrl+P` - behavior is the same.

**Additional Information**

Explanation to the examples:

- `01_expected_3.0.13`: This shows the expected behavior under Electron 3.0.13. I press `Ctrl+P` and the printing dialog appears immediately.
- `02_bug_4.0.0`: This shows the described bug under Electron 4.0.0. I must press `Ctrl+P` twice before the dialog opens. The debugger (VS Code) shows that the function gets called every time.
- `03_workaround_4.0.0`: This shows the described workaround under Electron 4.0.0 by giving an empty object as parameter.
- `04_callback-called_3.0.13`: As expected, a given callback gets called and gives some output to the console.
- `05_callback-not-called_4.0.0`: The given callback seems not to be called. There is no output in the console.

**Comment by javan** [comment]
Just tested on macOS (10.14.2) and `webContents.print()` doesn't work at all. The print dialog never opens.

**Comment by javan** [comment]
Did some more testing on macOS. Printing works as expected in the 4-0 betas up through 4.0.0-beta.9. Doesn't work in 4.0.0-beta.11 or 4.0.0.

**Comment by bengotow** [comment]
Hey folks—just wanted to add, I had this problem as well but was able to work around it by using `window.print()` instead (which seems to work fine.) Unfortunately you don't get a callback in that case...

**Comment by abdellaui** [comment]
does anyone have another clear solution as calling `webContents.print()` twice or `window.print()`?

**Comment by javan** [comment]
Here's my current workaround:
```diff
- contents.print()
+ contents.executeJavaScript("window.print()")
```

**Comment by TolgaDaSilva** [comment]
@javan  your current workaround works, but is there another way for printing silent.

**Comment by javan** [comment]
The `window.print()` API doesn't allow that, AFAIK. You could try using Electron v4.0.0-beta.9 or earlier until this issue is fixed.

**Comment by nitsakh** [comment]
Closing as this appears fixed in latest electron 5 beta. Feel free to reopen otherwise.

**Comment by maplemike** [comment]
Silent printing still fails in latest beta as mentioned in #16193

**Comment by maikonmatheus** [comment]
Silent printing still fails in Electron 5.0.3

**Comment by Catlite91** [comment]
Silent printing still fails in Electron 5.0.6.

**Comment by popod** [comment]
The backport which fix this issue is here #19038 Follow this PR to get notified when it will be merged into 5.x.x.
