### ISSUE TITLE
<input type=file> is not working on Windows.

### ISSUE THREAD

**Issue by agata** [electron/electron#18406]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.4
* **Operating System:**
  * Windows 10(1809) 64bit
* **Last Known Working Electron version:**
  * 5.0.1

### Expected Behavior

Can not select local file using <input type="file">.

### Actual Behavior

Can select local file using <input type="file">.

### To Reproduce

1. Run this commands.

```sh
$ git clone https://github.com/agata/can-not-select-file.git
$ cd can-not-select-file
$ npm install
$ npm start
```
or download [Installer for the sample app](https://github.com/agata/can-not-select-file/blob/master/dist/Electron%20Setup%201.0.0.exe). Then Install and run it.

2. The app shows mozilla's page with example for <input type="file"> .

3. Click "Choose File" and select a local file. It can not select file. It keeps to show "No file choosen."

### Screenshots
<img width="1154" alt="electron-6 0 0-beta 4" src="https://user-images.githubusercontent.com/40473/58185299-c7a3b980-7ced-11e9-9aa4-1378afc91fde.png">

Screeencast: [Electron-6.0.0-beta.4.mov.zip](https://github.com/electron/electron/files/3207975/Electron-6.0.0-beta.4.mov.zip)

### Additional Information

- Can select a file on Mac OS + Electron 6.0.0-beta.4.
- Can select a file on Mac OS + Electron 5.0.1.
- Can select a file on Windows 10 + Electron 5.0.1.
- Can not select a file on Windows 10 + Electron 6.0.0-beta.4.

I couldn't use the fiel open dialog on Electron 6.0.0-beta.3. Because beta.3 has [this issue](https://github.com/electron/electron/pull/18341) . It was fixed the issue by Electron 6.0.0-beta.4.

**Comment by MarshallOfSound** [comment]
Thanks for the detailed report, really appreciate it 👍 

This was fixed in #18383 and will be released in the next `6.0.0` beta release 👍

**Comment by agata** [comment]
@MarshallOfSound I've checked Release Notes for v6.0.0-beta.4. The release is including #18383 . But it didn't fix this issue. My sample for reproducing already use the version. https://github.com/agata/can-not-select-file/blob/master/package.json#L21

Could you please check again.

**Comment by agata** [comment]
@MarshallOfSound

Please reopen this issue. I checked #18383 . #18383 is for saveDialog. This issue is for **openDialog**. This issue didn't fix yet. Probably we should fix below line for openDialog the same way.

https://github.com/electron/electron/blob/cde02fd63fb686b6d5300afad986d6cc5c7112c9/atom/browser/ui/file_dialog_win.cc#L100

to
```c++
base::BindOnce(&OnDialogOpened, std::move(promise), !result, paths));
```

cc: @codebytere

**Comment by newPromise** [comment]
yes, you can update electron version to v6.0.12 to solve this question.

**Comment by newPromise** [comment]
I have some question on macOs Catalina
you can update electron version to v6.0.12 to solve this question.

**Comment by newPromise** [comment]
I have some question on macOs Catalina, last electron version is v5.02, when you click <input type="file"> to select the local 
file, the electron app is crashed no reason. then I update electron version to v6.0.12  and the question solved
you can update electron version to v6.0.12 to solve this question.
