### ISSUE TITLE
"Window is ready" notification on GNOME 3.32

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron/electron#18445]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.2
* **Operating System:**
  * Ubuntu 19.04 with GNOME 3.32
* **Last Known Working Electron version:**
  * Either 4.0.8 or 3.0.14. But more likely nothing, because this is a new version of GNOME.

### Expected Behavior
When Signal Desktop creates a new notification, all you see is the intended notification

### Actual Behavior
A strange 'is ready' notification is shown first.

![image](https://user-images.githubusercontent.com/36971246/58348210-d89b1a80-7e14-11e9-944b-2e542895563a.png)

### To Reproduce
- Start Signal Desktop, link to an account
- Have running, but not in focus
- Receive a message

Install Signal Desktop v1.24.1. Or build this tag: https://github.com/signalapp/Signal-Desktop/commits/v1.24.1

### Additional Information
Originally-reported bug: https://github.com/signalapp/Signal-Desktop/issues/3321

**Comment by malept** [comment]
This is not an Electron bug. I get "$app_name is ready" notifications from non-focused windows consistently, most notably "Firefox is ready" from its web notifications (I run GNOME 3.22.2). Check out the [relevant web search](https://duckduckgo.com/?q=gnome+%22is+ready%22+notifications) to give your users some options on how to disable them.

**Comment by MarshallOfSound** [comment]
Closing out as per above comment, appears to be a OS / WM bug rather than an Electron issue.

**Comment by mitar** [comment]
I think this is an Electron bug based on the perspective of Gnome developers. See discussion [in this issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/358) (and [related](https://gitlab.gnome.org/GNOME/mutter/-/issues/673)). So it seems Gnome is saying this logic is important and Electron is not passing correctly timestamps for Gnome logic to properly detect the proper "focus changes" vs. "focus stealing".

So while I agree that ideally Gnome would just magically do the right thing, maybe Electron can meet Gnome in the middle and do properly configure timestamps on their events so that Gnome logic can do its thing. And then through time Gnome can improve things as well.

I would like to ask for this issue to be reopened.

**Comment by maymage** [comment]
@MarshallOfSound 

Please reopen this issue. The comment https://github.com/electron/electron/issues/18445#issuecomment-495765465, to which you refer for closing is misleading. The issue still persists with Signal, Firefox doesn't show the notification and the points raised in
the above comment https://github.com/electron/electron/issues/18445#issuecomment-688609239  are still valid.  

---

I'm on current Debian Sid with current Signal app..

**Comment by nekohayo** [comment]
My understanding / guess of the problem here is… that Electron is setting the "urgency" activity hint onto its window (and/or attempting to grab focus) in addition to emitting the notification. There is no reason to do that when you are using a notification; it should _only_ emit the notification. In light of this technical hypothesis/clarification, I would recommend reopening this ticket.

**Comment by jsparber** [comment]
I fixed the GNOME Shell side of this issue with  [FdoNotificationDaemon: Emit ActivationToken before ActionInvoked signal ](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3199). But electron still needs to consume the token returned by https://gnome.pages.gitlab.gnome.org/libnotify/method.Notification.get_activation_token.html and us it when rising&focusing the electron window.

**Comment by nekohayo** [comment]
@scottnonnenberg-signal or @MarshallOfSound could you retitle and reopen this issue as per the findings above?

In any case I still don't think Electron apps should be trying to rise their own window for a simple notification, if that's what's actually happening. This is not a situation like the operating system going, "The laptop battery is at 2% and about to die on you", and Electron is the only app I know of that still does this even with GNOME 48…

**Comment by nekohayo** [comment]
Also, for the other way around (i.e. the situation where you are clicking a link _from within an Electron app_ to be opened in a separate browser like Firefox), doesn't Electron need to emit the ActivationToken for the other app (ex: Firefox) to consume, too?

**Comment by diegoe** [comment]
FTR current code suggests the activation token is being passed along to Chromium but I have no clue what happens next

https://github.com/electron/electron/blob/1cf98129e42ca3bff2b9ca13c78b65f10a156718/shell/browser/notifications/linux/libnotify_notification.cc#L218-L234
