### ISSUE TITLE
`navigator.mediaDevices.getUserMedia` promise resolves before user grants permissions -- intended usage?

### ISSUE THREAD

**Issue by jack-arms** [electron/electron#19017]
### Issue Details

* **Electron Version:**
  * 5.0.5
* **Operating System:**
  * macOS 10.14.5

### Expected Behavior
`navigator.mediaDevices.getUserMedia` promise doesn't resolve until user allows or denies permission, according to https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

### Actual Behavior
`navigator.mediaDevices.getUserMedia` resolves before user click "Don't Allow" or "OK" on the system dialog. 

### To Reproduce
- Run `tccutil reset Camera; tccutil reset Microphone` to clear permissions for the macOS terminal.
- Run electron-quick-start (https://github.com/electron/electron-quick-start)
- Open Developer tools
- In the console, run:
```
navigator.mediaDevices.getUserMedia({audio: true, video: true}).then(e => console.log(e));
```
- Observe that the promise resolves with a `MediaStream` before you click "Don't Allow" or "OK" on the dialog that pops up.

### Screenshots
![Screen Shot 2019-06-27 at 12 32 03 PM](https://user-images.githubusercontent.com/2754685/60295411-7da78800-98d8-11e9-839f-fa139c1cc447.png)

### Additional Info
If I understand correctly the promise resolves before the dialog closes in order for the dialog to not block the renderer process? However, the media stream returned doesn't do anything until the user actually accepts the permission. How can we know if the user accepted permission, in order to not use the returned media until it has a valid stream?

**Comment by MarshallOfSound** [comment]
This is this crbug --> https://bugs.chromium.org/p/chromium/issues/detail?id=885184
Fixed in part by --> https://chromium-review.googlesource.com/c/chromium/src/+/1511401 (and maybe some others, check the bug for more).

Maybe something we can / should backport?

**Comment by DeerMichel** [comment]
So apparently, this bug is still present in Electron v6 and v7 which both use a Chromium version that should include a fix for it. While we're investigating this, you can do a workaround using [session.setPermissionRequestHandler()](https://electronjs.org/docs/api/session#sessetpermissionrequesthandlerhandler) to intercept the permission request and [systemPreferences.askForMediaAccess()](https://electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos) which returns a "correct" promise.

**Comment by KASOGIT** [comment]
BUG still occurring on electron v8, do we have some updates on it ?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
