### ISSUE TITLE
The fs API doesn't work in a renderer process unless the BrowserWindow has been reloaded once

### ISSUE THREAD

**Issue by tyleo** [electron/electron#19554]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 5.0.8**
* **Operating System: Windows 10 (1809)**
* **Last Known Working Electron version: 3.1.12**

### Expected Behavior

Calling the asynchronous fs APIs should work in the renderer process in the same way that it works in the main process.

### Actual Behavior

Calls to the asynchronous fs APIs in the renderer process will randomly fail. No exception is thrown, rather, it seems like the callback is never called when using the old asynchronous API and the awaited promise will never complete when using the newer fs.promises API. The synchronous API seems to work consistently.

I have observed this error with code like:
```js
const fs = require("fs");
// Sometimes this callback will never be called
fs.stat("C:\\", () => {});
// Sometimes this will await forever
await fs.promises.stat("C:\\");
// This always seems to work
fs.statSync("C:\\");
```

While I use `stat` in the example above, I've also observed it with `readFile` and `writeFile`. I've also observed the issue on a variety of paths, not just "C:\\". The issue seems to go away if I refresh the browser window. So I've refactored my application in the short term to refresh the browser window after initial load. I've added a branch to renderer.js similar to:
```js
const electron = require("electron");
if (electron.remote.getCurrentWindow().hasReloaded) {
  // Run renderer logic
} else {
  electron.ipcRenderer.send("needs-reload");
}
```

Then in the main process I do:
```js
const electron = require("electron");
let browserWindow;
electron.ipcMain.on(
  "needs-reload",
  () => {
    browserWindow.hasReloaded = true;
    browserWindow.reload();
  }
);
// Run main logic, including creating browserWindow.
```

### To Reproduce

See my notes above, let me know if you'd like more information.

### Additional Information

It looks like this issue in nodejs is also observing the problem https://github.com/nodejs/node/issues/14889.

**Comment by tyleo** [comment]
I'm trying to get a repo up which reproduces the issue right now. I'll edit the comment when I'm done.

**Comment by nornagon** [comment]
This looks related to https://github.com/electron/electron/issues/19368

**Comment by tyleo** [comment]
Interestingly, I can't reproduce with a simple example. I have https://github.com/tyleo/electron-issue-19554 and I'm experimenting to see if I can replicate the behavior. There must be something else I'm doing in my private repo which is causing an issue.

**Comment by sentialx** [comment]
@tyleo Try running your repro on Electron 6.0.0.

**Comment by tyleo** [comment]
Alright, I've got more time to look at this over the next few days. I'm going to try to clone my larger repo which expresses the bug and then hack away initialization logic until I have a minimum working example.

Afterwords, I will tighten that up into my https://github.com/tyleo/electron-issue-19554 repo.

Once that's done I'll try to reproduce in electron 6.0.0 in the minimal repo.

**Comment by tyleo** [comment]
I'm seeing some very strange stuff. https://github.com/tyleo/electron-issue-19554 is now pretty minimal. It seems like I should be able to get it smaller by removing typescript from that project but for some reason, the issue will not reproduce if I don't run tsc before running electron... very strange.

Specifically, the issue reproduces pretty frequently on windows in that repo right after running `yarn install` and then running the `Broken` launch configuration in vscode (this will automatically run tsc). After that, if I'm having trouble reproducing I delete the target and node_modules folders and run `yarn install` and launch again.

Still working to try to get the repo to be even more minimal. Since this issue is flaky I've been running quite a few times after each change to try to reproduce it.

I have not reproduced the issue without typescript yet. I've tried to leave the .js files as-is and delete the typescript dependency and ts folder but I could not reproduce. I'll keep working to get this smaller but its currently less than 70 lines of code. I could probably cut a lot out of renderer.js I haven't touched it much.

**Comment by tyleo** [comment]
Just to clarify some interesting things:
1) The issue only reproduces when I run using the `Broken` launch configuration in VSCode. It does not reproduce when I run from the command line `electron .`.
2) The issue only reproduces when I build the project `tsc .` before the `Broken` launch configuration starts. If I comment the line which runs `tsc .` before launching, the issue goes away.

**Comment by tyleo** [comment]
I've replaced `tsc` with `touch` in my scripts and I'm still seeing the issue.

I've also tested with electron 6 and have not been able to reproduce. I'll probably update my own repo to 6 to work around this.

My minimal repo is now only 35 lines of code so it should be easy to work through the logic if you want to reproduce. To run it:
1) `git clone https://github.com/tyleo/electron-issue-19554.git`
2) `yarn install`
3) Run the "Broken" launch config in VSCode.

This bug will not reproduce if I remove the preLaunchTask which touches main.js and renderer.js.
This bug will not reproduce if I launch from the command line.
* I've tried running from the command line with `electron --preserve-symlinks --remote-debugging-port=9223 .` which are the same options I'm using in my launch config.
* I have not tried attaching the renderer debugger manually.

**Comment by Vavassor** [comment]
I *think* I've run into this same problem in 6.0.3? I was able to work around it for my use case by using `fs.readFileSync` instead of `fs.readFile`, but it's not ideal. I haven't had time yet to make a reproduction, so I can't offer much except confirmation.

**Comment by martin31821** [comment]
We have the same problem in an electron 4.0.2. 
It also only seems to be broken on some machines, it works fine within a VBox VM.

In our tests, this only occurred when loading a page via http, so I guess, there's some kind of race condition.

**Comment by robinchrist** [comment]
Regarding the comment by @martin31821
I can add that it *works* after Force Reloading the application.

**Comment by Doccrazy** [comment]
This issue has been driving me crazy after upgrading my app from Electron 3.0.14 to 6.0.12, and I've been trying unsuccessfully for days to get a minimal reproduction. It is not limited to dev mode, it also shows in the final packaged app.

However, after reading the thread and doing some experiments, it definitely seems like a `BrowserWindow.loadURL` race condition / timing issue.

The issue reliably appears on my dev machine with the following code in main.ts:
```
mainWindow.loadURL('http://localhost:1212/');
```
and reliably disappears when changing the line to the following, or after reloading:
```
setTimeout(() => {
  mainWindow.loadURL('http://localhost:1212/');
}, 100);
```
Environment: Electron 6.0.12, Typescript, Windows 10

**Comment by deanmikel** [comment]
@Doccrazy that works for me too. Using electron-builder, background.js:
``` setTimeout(() => {
      win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
    }, 100);
```

**Comment by g-jozsef** [comment]
Same problem, Electron Version: 8.1.0, Windows 10, using the timeout workaround reliably "fixed" it.

**Comment by RadoslavK** [comment]
No amount of waiting in setTimeout works for me. Version 8.2.0 on Windows 10.
But reloading worked.

**Comment by Chadnaut** [comment]
Issue persists with Electron 8.2.2 on Windows 10 with electron-forge
@Doccrazy 's timeout trick solved it for me.

Some additional observations for the devs:
```
app.allowRendererProcessReuse = (bool);
```

- **true** = the renderer readFile callback fires after window unload, seen by using console.log in the callback, Preserve log in the console, and reloading the app.
- **false** = the renderer readFile callback requires an initial reload to work at all.
```
setTimeout(() => {
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
}, 0);
```
Calling loadURL on the very next tick results in expected callback behavior, no matter what allowRendererProcessReuse is set to. Race condition indeed.

The resulting executables in this Electron version work without the timeout trick at all.

**Comment by Marcus10110** [comment]
Could you try setting the environment variable `UV_THREADPOOL_SIZE` to some thing larger than 4 and testing it again? e.g. `set UV_THREADPOOL_SIZE=16`.

I just troubleshooted what I thought was the same problem - electron 8, all fs.promises.* calls would not resolve or reject. However in my cause it was caused by having 4 outstanding calls to fs.promises.open, all at the same time, waiting for named pipes to become available.

It seems like those 4 calls I made blocked all 4 threads in the libuv thread pool, preventing any new fs commands from running. increasing UV_THREADPOOL_SIZE caused it to work and proved that was it.

**Comment by PieterVanZyl-NWU** [comment]
This is a problem for me to running on electron 9.1.0

Using Visual Studio code and Windows 10 

setTimeout() fixed the problem for me.

So glad this issue was here, without it I probably would have just given up on 20+ hours worth of app coding.

**Comment by drizzd** [comment]
None of the suggested workaround worked for me:
- Increasing UV_THREADPOOL_SIZE to 16
- `setTimeout(() => { win.loadURL(process.env.WEBPACK_DEV_SERVER_URL) }, 100);`
- Reloading manually

I am testing with `fs.promises.lstat`. Starting from the second invocation, the promise does not resolve. This reproduces reliably. Tested with Electron 9.0.0. Same behavior with Electron 10.1.0.

What does work for me is to use node APIs only in the main process. I use the messaging mechanism to invoke node APIs from the renderer process:

```
// main process
ipcMain.handle('lstat', async (event, filename) => await fs.promises.lstat(filename));

// preload.js
window.lstat= function(filename) { return ipcRenderer.invoke('lstat', filename); };

// renderer process
let st = await window.lstat(filename);
```

This is more work, but it is well worth the trouble. It works reliably and without workarounds.

The Electron [documentation](https://www.electronjs.org/docs/tutorial/application-architecture#using-nodejs-apis) advertises the use of Node.js APIs in the renderer process:

> Electron exposes full access to Node.js both in the main and the renderer process.

According to this issue, at least the `fs` API has been broken for at least a year. How about changing the documentation to say that the recommended, reliable practice is to call Node.js APIs (or at least the `fs` API, if the issue is limited to that) only from the main process, and to expose APIs to the renderer process as shown above? This is recommended for security reasons, anyways, right? Maybe we could even deprecate the use of Node.js APIs from the renderer process altogether?

What do you think?

**Comment by codebytere** [comment]
This should be fixed by https://github.com/electron/electron/pull/25869

**Comment by robinchrist** [comment]
@codebytere I don't think the issue will be fixed by #25869

We're on Electron 8, `app.allowRendererProcessReuse` is on default (and thus should take `false` value).
Also note that we first experienced this issue with Electron 4, `allowRendererProcessReuse` didn't even exist back then...

**Comment by remss** [comment]
Release 10.1.4 did not resolve the issue for me. I still need to reload the page to see FS module working, no matter if allowRendererProcessReuse is true or false. I'm stuck in version 9 😥

**Comment by codebytere** [comment]
@remss do you have a repro? i have no issues on macOS or windows as tested.

**Comment by remss** [comment]
@codebytere After investigations the issue appears only on CIS node (Windows10 VMWare guest) when Electron 10 is started by Spectron 12, and I don't reproduce on my workstation...  Sorry for the inconvenience.

**Comment by codebytere** [comment]
I'm gonna go ahead and close this out - if there are new issues please open them in a new issue!

**Comment by robinchrist** [comment]
@codebytere Could you please explain why you're closing this issue?

As far as I can say, the issue is not fixed and your proposed fix is not related to the initial issue at all.

**Comment by codebytere** [comment]
@robinchrist i'm not able to reproduce it on any platform, and have not seen a repro which has allowed me to do so.

**Comment by robinchrist** [comment]
The whole point of this issue is that it's notoriously difficult to reproduce and the cause cannot easily be isolated.

**Comment by blackChef** [comment]
I'm using windows@10 and electron@11.0.3, and still have this problem. I spent hours trying to narrow down the issue, luckily the `setTimeout` fix works for me.

**Comment by bikutaa-dev** [comment]
I just wanna say that I had this problem, and not only with FS, also with OBS-websocket-js: https://github.com/haganbmj/obs-websocket-js, didn't wanna work in developer mode, but works great in production mode. The timeout fix worked for me. 

The only thing I can say is that when I tried to find the problem with the OBS-websocket-js in developer mode is that it reached different parts of the OBS-websocket-js code every time I tried to use it.

**Comment by robinchrist** [comment]
Yeah, we also experienced issues when using Axios. The request just disappears.

But
I'M NOT AbLE TO reprODucE IT oN any PLaTfOrM, And HAVE NoT SEen A rePro wHIch HAs ALLOwed mE TO Do so.

¯\_(ツ)_/¯

**Comment by undergroundwires** [comment]
This was working fine for me in Electron 11. It stopped working after migration to Electron 12.

`setTimeOut` trick has however solved it to me with `electron-builder`.

Reproduce steps on Windows 10 for my project:

1. Clone [privacy.sexy](https://github.com/undergroundwires/privacy.sexy)
2. Check out to `1f515e7be525291c960ccb71db05312db6da53f5` (commit with the electron upgrade from 11 to 12)
3. `npm install` & `npm run electron:serve`
3. It hangs at `fs.promises.mkdir(dir, {recursive: true});` ([see line](https://github.com/undergroundwires/privacy.sexy/blob/1f515e7be525291c960ccb71db05312db6da53f5/src/infrastructure/CodeRunner.ts#L12)) and never resolves as described in #20951 (possible to triggersthis through clicking on any script in the application and click on the run button at the bottom)

**Comment by undergroundwires** [comment]
This was working fine for me in Electron 11. It stopped working after migration to Electron 12.

`setTimeOut` trick has however solved it to me with `electron-builder`.

Reproduce steps on Windows 10 for my project:

1. Clone [privacy.sexy](https://github.com/undergroundwires/privacy.sexy)
2. Check out to `1f515e7be525291c960ccb71db05312db6da53f5` (commit with the electron upgrade from 11 to 12)
3. `npm install` & `npm run electron:serve`
3. It hangs at `fs.promises.mkdir(dir, {recursive: true});` ([see line](https://github.com/undergroundwires/privacy.sexy/blob/1f515e7be525291c960ccb71db05312db6da53f5/src/infrastructure/CodeRunner.ts#L12)) and never resolves as described in #20951 (possible to triggers this through clicking on any script in the application and click on the run button at the bottom)

**Comment by dacanizares** [comment]
Same issue. The setTimeout workarround seems to work, but it 's so hacky. Any news regarding this?

**Comment by gaoshang212** [comment]
We have the same problem in an electron 11.4.*
it works fine within electron 11.3.0

**Comment by thangbui1999a** [comment]
I have same issue with Electron 11.4.4. Issue disappears when I updated Electron to v12.0.5 (don't need to setTimeout)

**Comment by ajackson-adi** [comment]
I recently ran into this issue while using Spectron with Electron(v11.2.1). Our application loaded fine on its own but had this(or a similar) issue when loaded with Spectron. It was odd because everything had been working fine and nothing in our codebase had changed(i.e. literally 0 changes).

I tried upgrading to v12.0.10 but had no luck. However, I noticed there was an update to malware definitions in Windows defender.

What ended up fixing it for us was turning off Real-time protection in Windows Defender. Hopefully, this is helpful to someone.

**Comment by xiaozhuai** [comment]
I have same issue with Electron 13.2.2. It appears randomly, very odd.

**Comment by prcdpr** [comment]
Occurs also in Electron v14.0.0. Hangs indefinitely on `fs.promises.readFile` until the page is reloaded. Occurs randomly but very often, about 50% of the time.

**Comment by alexanderkasten** [comment]
Having the same issue with Electron ^13.0.0 but mostly on WIndows.
