### ISSUE TITLE
currentWindow.maximize() doesn't truly maximize the window

### ISSUE THREAD

**Issue by Z3RoMan** [electron/electron#19934]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** Electron 6.0.4
* **Operating System:** Windows 10 (1903)

### Expected Behavior
The maximize() function maximizes the window as it would any other window.

### Actual Behavior
The maximize() function "maximizes" the window, but doesn't give it the maximized property. The window is still resizable via the edges of the app.

### To Reproduce
Have an app with a custom title bar emit the maximize() function on a custom placed maximize button. The properties of the window should be `frame: false` and `transparent: false`.

### Additional Information
The general concept of the custom titlebar with buttons is taken from a repository found here:
https://github.com/maxchaor/electron-title-bar-tutorial
The repository in question uses Electron 2.0.0 to run it.

This issue isn't present on every device. It's been tested on three of my own systems and it works fine on there.

**Comment by ZaDarkSide** [comment]
Yes this is a very very old bug, that no one bothered to fix.
https://github.com/electron/electron/issues/12854

**Comment by Z3RoMan** [comment]
> Yes, this is a very very old bug, that no one bothered to fix.
> #12854

Yeah, I found that bug report as well. It doesn't exactly describe it the same way since it even happens on `transparent: false` (and `frame: false`), but I'm guessing the result is the same, or rather lack thereof.

What I'm wondering is how other apps fixed this particular issue. Discord for example utilises a custom title bar and maximises just fine.

**Comment by ZaDarkSide** [comment]
Well they don't use `transparent: false` and `frame: false` at the same time to avoid the bug like everybody else.

**Comment by Z3RoMan** [comment]
> Well they don't use `transparent: false` and `frame: false` at the same time to avoid the bug like everybody else.

Are you certain that's the cause? Because we added in `transparent: false` after the bug was found to test it further, without result. In both `true` and `false` cases, the resizing glitch still occurs.

**Comment by ZaDarkSide** [comment]
For me it only manifests on using `transparent: true` and `frame: false` at the same time.

**Comment by AlexSHoffman** [comment]
@ZaDarkSide I also have this issue with `transparent: false`. 

My app always had the `fake maximized state resize ability` behavior described by OP but now after upgrading to `6.x` the `remote.getCurrentWindow().maximize()` function stopped setting `isMaximized` property to `true` so the shown below `maximizeWindow()` function stopped working as well:


## Info
* **Electron Version: 6.0.5**
  * 6.0.5
* **Operating System:**
  *  Win10 (1903) x64
* **Last Known Working Electron version:**
  * 4.x (not sure about 5.x)

### To Reproduce

```JS
const remote = require('electron').remote
const window = remote.getCurrentWindow()    

maximizeWindow () {
  // ALWAYS OUTPUTS FALSE
  console.log(this.window.isMaximized())
      
  if (this.window.isMaximized()) {
    this.window.unmaximize()
  } else {
    this.window.maximize()
  }
}
```

## main

```JS
 mainWindow = new BrowserWindow({
    width: 1280,
    height: 720,
    minHeight: 300,
    minWidth: 500,
    frame: false,
    webPreferences: {
      nodeIntegration: true,
      webSecurity: process.env.NODE_ENV !== 'development', // to make image loading from local drive possible
    } 
  })
```

**Comment by AlexSHoffman** [comment]
@ZaDarkSide I also have this issue with `transparent: false`. 

I'm not sure what happened after v4.x but this bug evolved, it seems. 
In version 4.x, my app had the `fake maximized state resize ability` behavior described by OP but now after upgrading to 6.x, something else happened to `remote.getCurrentWindow().maximize()`, because the shown below `maximizeWindow()` function in my app stopped working as well:


## Info
* **Electron Version: 6.0.5**
  * 6.0.5
* **Operating System:**
  *  Win10 (1903) x64
* **Last Known Working Electron version:**
  * 4.x (not sure about 5.x)

### To Reproduce

```JS
const remote = require('electron').remote
const window = remote.getCurrentWindow()    

maximizeWindow () {
  // ALWAYS OUTPUTS FALSE
  console.log(this.window.isMaximized())
      
  if (this.window.isMaximized()) {
    this.window.unmaximize()
  } else {
    this.window.maximize()
  }
}
```

## main

```JS
 mainWindow = new BrowserWindow({
    width: 1280,
    height: 720,
    minHeight: 300,
    minWidth: 500,
    frame: false,
    webPreferences: {
      nodeIntegration: true,
      webSecurity: process.env.NODE_ENV !== 'development', // to make image loading from local drive possible
    } 
  })
```

**Comment by Z3RoMan** [comment]
@AlexSHoffman Your problem is indeed directly related to ours. Whenever a window gets maximised on certain systems (all Windows 10), it does stretch it out accordingly, but doesn't give itself the correct state. Because of that, `isMaximized()` always returns false.

**Comment by AlexSHoffman** [comment]
@Z3RoMan yeah, but the weird thing is, for me it worked properly in v4.1.5, the `isMaximized()` function has been returning `true` in the maximized state, with the same config:
```JS
frame: false,
transparent: false
```

**Comment by ZaDarkSide** [comment]
The bug appears when you use `transparent: true`

**Comment by AlexSHoffman** [comment]
@ZaDarkSide ...and also when I use:
```JS
frame: false,
transparent: false
```

**Comment by ZaDarkSide** [comment]
Yes, well clearly something changed between 4.x and 6.x

**Comment by wangjikill** [comment]
```
{
    minWidth:800,
    minHeight:600,
    resizable:true
}
```
You must include the above configuration, win.isMaximized() and win.unmaximize() to work properly.

**Comment by AlexSHoffman** [comment]
@wangjikill your suggestion does not fix the problem, `window.isMaximized()` still returns `false` and `window.unmaximize()` doesn't work either. I'm using `v6.0.7`

**Comment by EGo14T** [comment]
@AlexSHoffman 
Do you have any solution to solve this issue？:)

**Comment by AlexSHoffman** [comment]
@EGo14T no, I couldn't find a solution. But maybe it will get fixed in Electron v7.x

**Comment by EGo14T** [comment]
> @EGo14T no, I couldn't find a solution. But maybe it will get fixed in Electron v7.x

hmm...all right，thinks :)

**Comment by binaryfunt** [comment]
It seems Electron 5.0.11 is the latest version in which tis bug is not present

**Comment by huan0118** [comment]
-webkit-app-region: drag 你需要加上这个试试

**Comment by EGo14T** [comment]
@AlexSHoffman  You can use Electron 5.0.12（<6.0.0），and set you body CSS like this
body {
  border: 1px solid #48545c;
  overflow-y: hidden;
}
then this issue is solved~

**Comment by binaryfunt** [comment]
@EGo14T It's just the use of Electron <6.0.0 that matters, the CSS is irrelevant

**Comment by AlexSHoffman** [comment]
@EGo14T staying on version <6.0 is not really a solution. It has to get fixed

**Comment by wangjikill** [comment]
Guys, today, I try window maximization and cancel maximization again, I found this.

`let size = electronScreen.getPrimaryDisplay().workAreaSize;
  // Create the browser window.
  win = new BrowserWindow({
    width: 800,
    height: 600,
    maxWidth: size.width,
    maxHeight: size.height,
    center: true,
    frame: false,
    show: false,
    resizable: false,
    movable: true,
    webPreferences: {
      nodeIntegration: true
    }
  });`

**Comment by Liupeng8** [comment]
Have the same problem, it looks like this problem should exist for a long time, isn't the author planning to fix it。

**Comment by friksa** [comment]
I have the same issue on Mac OS Catalina with Electron 7.1.2.

**Comment by AlexSHoffman** [comment]
The issue is fixed for me in `Electron 7.1.2` on Windows 10. I don't know at which point it got fixed after `6.0.7`

**Comment by TheKiLLerDz** [comment]
The issue still exists in Electron 7.1.3 on Windows 10!

**Comment by AlexSHoffman** [comment]
@TheKiLLerDz I just updated from `7.1.2` to `7.1.3` on Windows 10 and there's no issue, it works properly in my project on both of these versions, even though it didn't work before `7.1.2` and I'm not sure what fixed it for me. 

Man this is such an inconsistent bug.

**Comment by Liupeng8** [comment]
The issue still exists in Electron 7.1.3 on Windows 7

**Comment by TheKiLLerDz** [comment]
the bug is only when u use "transparent: true", when you don't  use it it works perfect

**Comment by AlexSHoffman** [comment]
@TheKiLLerDz nope, I had this issue with `transparent: false`. Read my message in the beginning of the thread

**Comment by TheKiLLerDz** [comment]
@AlexSHoffman  the css added to body seems not to work for my case , only making "transparent: false" that makes Maximize really do it's job
& as u said before the window doesn't really maximize it self since u can resize it this is why isMaximized Method is always returning false

**Comment by Liupeng8** [comment]
The issue still exists in Electron 7.1.4 on Windows 7

**Comment by chenjietao** [comment]
I wrote a plug-in to fix this problem. See [electron-frameless-window-plugin](https://www.npmjs.com/package/electron-frameless-window-plugin). In fact, I rewrote several  methods of BrowserWindow instance, including getNormalBounds(), maximize(), unmaximize() and isMaximzed(). And I've added some features to make frameless windows work better. Such as disable the menu when right clicking the drag region.

**Comment by wangjikill** [comment]
Guys,I found this, after you "setResizable(false)" or "new BrowserWindow({resizable: false})",then "isMaximized()" will always return "false",even if you execute "setResizable(true)".

So if you want "isMaximized()" to return the result correctly, make sure "resizable" is true always.

**Comment by kkgg123** [comment]
> Guys,I found this, after you "setResizable(false)" or "new BrowserWindow({resizable: false})",then "isMaximized()" will always return "false",even if you execute "setResizable(true)".
> 
> So if you want "isMaximized()" to return the result correctly, make sure "resizable" is true always.

I found that too!!!!!!!! version7.1.8

**Comment by zcbenz** [comment]
Fixed with https://github.com/electron/electron/pull/26586.

**Comment by morteza-jamali** [comment]
If you want to first use setResizable(false) and next time change it to setResizable(true) , you can use following code as replacement :

First time:

```javascript
mainWindow = new BrowserWindow({
    resizable: true,
    frame: false,
    width: 400,
    height: 400,
    minHeight: 400,
    minWidth: 400,
    maxHeight: 400,
    maxWidth: 400,
    .
    .
    .
  });
```

Next time:
```javascript
const { width, height } = screen.getPrimaryDisplay().workAreaSize;
mainWindow.setMaximumSize(width, height);
mainWindow.setSize(1024, 728);
mainWindow.center();
```

above code worked very good for me .

**Comment by olga-climova-2** [comment]
Seems that the `window.maximize() `function still doesn't work on Linux. We experience issues with automation testing, because the window still has 800x600 default size after `maximize()`. On Windows it's fine, and on Mac too, but we are using latest Ubuntu, and ubuntu 18.04 for testing too. For the moment we solved the issue by creating a window of minimal valid size for acceptance testing.

**Comment by mangeshsirkare** [comment]
Add below line in index.js 
It will maximized your window after splashScreen. You guys must try this

setTimeout(function(){
    mainWindow.maximize();
  },8000);

**Comment by paramula** [comment]
const { remote } = require("electron");
const win = remote.getCurrentWindow();
let isFullScreen = false
document.querySelector(".minimize").addEventListener("click", () => {
    win.hide();
});
document.querySelector(".maximize").addEventListener("click", () => {
  isFullScreen ? win.unmaximize() : win.maximize();
  isFullScreen=!isFullScreen
})
document.querySelector(".close").addEventListener("click", () => {
    win.hide();
    win.setSkipTaskbar(true);
    return false;
})

**Comment by paramula** [comment]
``const { remote } = require("electron");
const win = remote.getCurrentWindow();
let isFullScreen = false
document.querySelector(".minimize").addEventListener("click", () => {
    win.hide();
});
document.querySelector(".maximize").addEventListener("click", () => {
  isFullScreen ? win.unmaximize() : win.maximize();
  isFullScreen=!isFullScreen
})
document.querySelector(".close").addEventListener("click", () => {
    win.hide();
    win.setSkipTaskbar(true);
    return false;
})

**Comment by paramula** [comment]
const { remote } = require("electron");
const win = remote.getCurrentWindow();
let isFullScreen = false
document.querySelector(".minimize").addEventListener("click", () => {
    win.hide();
});
document.querySelector(".maximize").addEventListener("click", () => {
  isFullScreen ? win.unmaximize() : win.maximize();
  isFullScreen=!isFullScreen
})
document.querySelector(".close").addEventListener("click", () => {
    win.hide();
    win.setSkipTaskbar(true);
    return false;
})

**Comment by abbaty48** [comment]
> If you want to first use setResizable(false) and next time change it to setResizable(true) , you can use following code as replacement :
> 
> First time:
> 
> ```js
> mainWindow = new BrowserWindow({
>     resizable: true,
>     frame: false,
>     width: 400,
>     height: 400,
>     minHeight: 400,
>     minWidth: 400,
>     maxHeight: 400,
>     maxWidth: 400,
>     .
>     .
>     .
>   });
> ```
> 
> Next time:
> 
> ```js
> const { width, height } = screen.getPrimaryDisplay().workAreaSize;
> mainWindow.setMaximumSize(width, height);
> mainWindow.setSize(1024, 728);
> mainWindow.center();
> ```
> 
> above code worked very good for me .

// HANDLE WINDOW MAXIMIZE OR RESTORE
```
ipcMain.handle('maximizeOrRestore', (_event, _maximize: boolean) => {
  const _target = BrowserWindow.fromWebContents(_event.sender);
  const { height, width } = screen.getPrimaryDisplay().workAreaSize;
  _target.setMaximumSize(width, height);

  if (_maximize) {
    const [minWidth, minHeight] = _target.getMinimumSize();
    _target.setSize(minWidth, minHeight);
    _target.center();
    return false;
  } else {
    _target.setSize(width, height);
    _target.center();
    return true;
  }
});
```

**Comment by abbaty48** [comment]
> If you want to first use setResizable(false) and next time change it to setResizable(true) , you can use following code as replacement :
> 
> First time:
> 
> ```js
> mainWindow = new BrowserWindow({
>     resizable: true,
>     frame: false,
>     width: 400,
>     height: 400,
>     minHeight: 400,
>     minWidth: 400,
>     maxHeight: 400,
>     maxWidth: 400,
>     .
>     .
>     .
>   });
> ```
> 
> Next time:
> 
> ```js
> const { width, height } = screen.getPrimaryDisplay().workAreaSize;
> mainWindow.setMaximumSize(width, height);
> mainWindow.setSize(1024, 728);
> mainWindow.center();
> ```
> 
> above code worked very good for me .

// HANDLE WINDOW MAXIMIZE OR RESTORE
```
ipcMain.handle('maximizeOrRestore', (_event, _maximize: boolean) => {
  const _target = BrowserWindow.fromWebContents(_event.sender);
  const { height, width } = screen.getPrimaryDisplay().workAreaSize;
  _target.setMaximumSize(width, height);

  if (_maximize) {
    const [minWidth, minHeight] = _target.getMinimumSize();
    _target.setSize(minWidth, minHeight);
    _target.center();
    return false;
  } else {
    _target.setSize(width, height);
    _target.center();
    return true;
  }
});
```

**Comment by OmBayus** [comment]
use setFullScreen(true) instead of maximize()

```
win.setFullScreen(true);
```
