### ISSUE TITLE
Electron / Chromium Rendering Incorrect Colors in 30 bit Color Depth

### ISSUE THREAD

**Issue by kenpowers-signal** [electron/electron#20032]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.1
* **Operating System:**
  * Linux 5.2.8-1-MANJARO #1 SMP PREEMPT Fri Aug 9 19:34:20 UTC 2019 x86_64 GNU/Linux
* **Last Known Working Electron version:**
  * Never worked

### Expected Behavior
Electron should render proper colors in higher bit-depths.

### Actual Behavior
Electron looks like a night at the disco.

### To Reproduce

1. Switch to 30 bit color depth by editing xorg.conf
1. Open any Electron application

### Screenshots

![image](https://user-images.githubusercontent.com/49649953/63963341-d0312c00-ca62-11e9-88a5-b6e1027d68d4.png)

### Additional Information

This appears to be an upstream issue with Chromium. Our user reports the same issue in Chromium 76.0.3809.132-0. Here are links to our issue tracker and the Brave issue tracker:

- https://github.com/signalapp/Signal-Desktop/issues/3546
- https://community.brave.com/t/wrong-color-rendering-on-30-bit-displays-on-linux-possibly-on-other-platforms/50266

**Comment by bhlevca** [comment]
I have the same issue. I also filed a bug with the chromium guys, as chromium has the same problem. Since Chromium is used by electron, hopefully with requests coming from more than one direction someone may move to do something about it.  Yes it is an upstream issue and  although I was the guy who filed the bug with Brave cited by the OP, they did not do anything about it.  The silent, automatic  dismissal of bugs after 30 days because no one in the development team dose not acknowledge it, drives me crazy,  It is not nice and it is not moral.

**Comment by bhlevca** [comment]
Here a nice and useful read about 30 bit color depth https://www.nvidia.com/docs/IO/40049/TB-04701-001_v02_new.pdf

**Comment by TonyWuu** [comment]
> I have the same issue. I also filed a bug with the chromium guys, as chromium has the same problem. Since Chromium is used by electron, hopefully with requests coming from more than one direction someone may move to do something about it. Yes it is an upstream issue and although I was the guy who filed the bug with Brave cited by the OP, they did not do anything about it. The silent, automatic dismissal of bugs after 30 days because no one in the development team dose not acknowledge it, drives me crazy, It is not nice and it is not moral.

@bhlevca can you share the bug report you filed with Chromium? Do you know if it's being tracked elsewhere in the Chromium bug tracker?

**Comment by bhlevca** [comment]
Chromium has been fixed some time ago. The problem is on elecron side to
update to a newer version of chromium >=81.

All chromium based browxers, Chrome, Brave, Vivaldi, etc all work fine on
30 bits colour displays

**Comment by bhlevca** [comment]
> @bhlevca can you share the bug report you filed with Chromium? Do you know if it's being tracked elsewhere in the Chromium bug tracker?

@TonyWuu Sorry for the late reply, I was not watching. Here is the link. https://bugs.chromium.org/p/chromium/issues/detail?id=1016383#c66

I hope that you guys can fix  this, so many apps use now electron and they are useless on 30 bit displays on Linux

**Comment by madera** [comment]
I just downloaded the latest Visual Studio Code and ran it on a Dell UP3218K at 30bpp. The issue still persists.

Is this going to be fixed on this project? Since Chromium has been fixed (according to comments here), it might be fairly straightforward to bring the patch do electron, right?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
