### ISSUE TITLE
Horizontal Scroll Issue

### ISSUE THREAD

**Issue by gaby64** [electron/electron#20874]
Coming from VS Code where they have identified electron as the issue.
https://github.com/microsoft/vscode/issues/56964

MX Master mouse horizontal scroll does not work or works intermittently.

**Comment by DaanDL** [comment]
Can confirm. Scrolling doesn't work as intended for VS Code or Trello.

**Comment by martavis** [comment]
I found a solution for this. You need to disable hardware acceleration in VS Code. To do that, open the command search (`Ctrl + Shift + P`), then type in `Configure Runtime Arguments`. Once the JSON file opens, add a new entry `"disable-hardware-acceleration": true`. Then restart VS Code. Horizontal scrolling should work. I came to this conclusion from [another app having this issue with the MX Master](https://community.brave.com/t/horizontal-scrolling-doesnt-work/47148/9), then searching [how to disable hardware acceleration for VS Code](https://github.com/microsoft/vscode/issues/15211#issuecomment-540048507).

**Comment by mglimmerveen** [comment]
I just bought a Logitech MX Master 3, and the above solution does not work (yet) for me.  Perhaps there is another part of the fix you have done unaware?

**Comment by Dexy2811** [comment]
> I just bought a Logitech MX Master 3, and the above solution does not work (yet) for me. Perhaps there is another part of the fix you have done unaware?

Same here i have just bought an MX master 3 as well and still not working

**Comment by CiriousJoker** [comment]
MX Master 2S here, same issue. The disable-hardware-acceleration fix has worked form me so far (that is, for 5 mins of testing), but it rly sucks to have to do that :(

**Comment by nornagon** [comment]
Does Chrome have the same issue?

**Comment by gaby64** [comment]
disable-hardware-acceleration did not fix it for me

**Comment by Dexy2811** [comment]
> Does Chrome have the same issue?

No it works fine in chrome but not in Firefox

**Comment by JacobDB** [comment]
I just replaced a Microsoft Sculpt Ergonomic Mouse with a Logitech MX Master 25. Horizontal scrolling works in Chrome, Firefox, Excel, File Explorer, etc., but not in VS Code, Spotify, etc.

Really hope we can get this sorted out soon, I rely on horizontal scrolling quite a bit.

**Comment by Dexy2811** [comment]
@JacobDB how did you get it to work on firefox it doesn't work in firefox for me.

**Comment by JacobDB** [comment]
@Dexy2811 honestly, I don't know, it just worked. I'm using Firefox Developer Edition, v73.0b4 (64-bit)

**Comment by Dexy2811** [comment]
@JacobDB do you have Logitech options installed as well? i do and downloaded the version your on and didn't work

**Comment by JacobDB** [comment]
@Dexy2811 I do have Logitech Options installed &ndash; just tested again, and it still works.

Strangely, it seems to randomly start working in general in Electron apps. No idea why, I'll just be going about my day and suddenly it work. Then the next morning, after rebooting, it stops working again.

**Comment by andreialecu** [comment]
I'm also noticing this problem mostly in Brave and VS Code. Chrome seems to be ok, but in Brave most of the time horizontal scrolling doesn't work. Both Brave and VS Code are electron apps.

It's pretty random when it works and when it doesn't, sometimes it will start working randomly and it will keep working for a long time but then it will suddenly stop working again. I've noticed that sometimes toggling settings on/off in Logitech Options will revive it for a bit.

In Brave, for example when browsing Trello, using the wheel will initiate the horizontal scroll and scroll the screen for a few pixels, but then it will stop and not work again for a while.

**Comment by andreialecu** [comment]
Something that might be relevant that I noticed in VS Code:

1) If you switch to a vs code tab that does NOT have code in it that exceeds the width of the viewport a horizontal scroll bar won't be shown and horizontal scrolling won't be allowed. If you scroll vertically until something does exceed the width of the window, the scroll bar will appear and horizontal scrolling with the wheel might work. 

2) When the "bug" occurs, it will always allow scrolling for a bit before completely stopping and failing to respond to wheel events.

Dragging the scrollbar itself always works.

*Strange thing I've noticed:*

If I open a different non electron app (such as Chrome), and initiate a horizontal scroll in it with the wheel, the Electron based app will also initially react to the wheel. It's hit and miss whether it will get un-stuck completely or still hang after a few pixels of scrolling.

However, doing this repeatedly in the third party app usually eventually gets electron scrolling back online. (Until randomly failing again after switching to a different app and then back)

**Comment by andreialecu** [comment]
![qADFGYiiAm](https://user-images.githubusercontent.com/697707/72460530-a9874e00-37d5-11ea-91c2-334c012b26a9.gif)

Weird glitch showing above. Simply rolling the scroll wheel left/right over Chrome, even if there's nothing to scroll in it, will fix Electron scrolling. Even without first clicking in Chrome to switch focus. It's enough that the mouse cursor is over Chrome.

Giving another app focus without using the horizontal scroll wheel in it will pretty reliably result in Electron scrolling being broken.

**Comment by JacobDB** [comment]
Strangely I've found that scrolling over FileZIlla specifically seems to always fix it for a long period of time. I have idea why that's the case, but I've been using it as a workaround for a few days now and as far as I can tell it consistently works.

**Comment by crc389** [comment]
After exploring this issue a lot, I noticed that if I lower the horizontal scroll speed / sensitivity, there is no longer a problem. 
When the horizontal scroll is too fast, it breaks and does not fix itself. 

My issue was the same as described in most of these posts, especially in @andreialecu 's video. 

If you are using a logitech mouse, setting the thumb wheel sensitivity to ~< 75% seems to do the trick. I have had no issues since, unless I am super zoomed in on text in vs code.

**Comment by JacobDB** [comment]
Sensitivity doesn't seem to make a difference to me unfortunately

**Comment by mglimmerveen** [comment]
I have good news and I have bad news.  As opposed to before, it now started working for, most of the time. However, I have no idea when or why.  I might have changed the sensitivity, or installed an update of the Logitech software, but I don't quite noticed the link immediately.

I did have one weird quirk, I scrolled horizontally, when there was only a tiny bit to be scrolled. It scrolled once, then froze and broke down. IIRC, it restarted working after I reloaded the VScode window.

**Comment by ldsands** [comment]
Sorry I know I'm a little late to the party but none of the above suggestions seem to work very well or very long for me. Typically, the issue I see most is what @mglimmerveen had mentioned with the scroll working once then it just stops. This consistently happens every time I restart VS Code. Also, I would like to note that the tip from @andreialecu seems to work there are several caveats to using it that I detail below. I can also confirm that this seems to be the case not only for my MX master 3 but also for my G502 (that recently died thus the MX master 3) the same issues impacted that mouse as well.

I have ADHD and I often open more than one window of VS Code open at once. The tip described by @andreialecu only will work on one window at a time and if you switch to another window of VS Code the horizontal scrolling will is lost on all open windows. Then when I reapply the tip it will again work until I switch the active window again.

Related to this I use the horizontal scroll in any program (including chrome) on another desktop<sup>[1](#1)</sup> the horizontal scrolling will cease working on the active VS Code window on the other desktop.

I have no idea if any of these details will help to track down the issue. This is the single most annoying bug I have to deal with on a daily basis and I really hope that someone can track it down! Good luck!

<a name="myfootnote1">1</a>: Windows desktops which are available by using `Start` + `Tab`

**Comment by mattgaspar** [comment]
Here's proof that Logitech is doing something specifically to make horizontal scrolling work for Chrome!

1. Rename (or copy) the exe for the Electron/Chromium app that is having the problem to chrome.exe
2. Launch the program by double clicking chrome.exe
3. Horizontal scrolling now works perfect!  WTF Logitech!

For me this works for VS Code by renaming code.exe to chrome.exe.  (actually I made a copy so that code.exe is still available from the command prompt)

Found this on the Vivaldi forum.
https://forum.vivaldi.net/topic/41537/logitech-smooth-scroll-extension-is-not-working-in-vivaldi/8

**Comment by CiriousJoker** [comment]
Interesting! There's a scrolling issue I filed some time ago that could potentially give insights into how Logitech Options works behind the scenes. From what I've noticed, Logitech Options does hook into Chromium based browsers (potentially not all but only whitelisted ones hence no Vivaldi?).
Here's the issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1044457

**Comment by mundodisco8** [comment]
Still waiting for a proper fix, but I can confirm that with a MX Master (the first one) horizontal scroll on VS Code and Spotify work by using Shift + Vertical Scroll Wheel. I know it's not ideal. but it's something...

**Comment by artchess** [comment]
Have the same problem on Windows 10, vs code 1.45.1 and Logi MX Master 3 :(

**Comment by ikhsanalatsary** [comment]
I think the problem comes from Windows itself because it's not only Vscode but other app like Dbeaver got the same problem. I was using voyager GS distro (Xubuntu based). no problem so far.

**Comment by gaby64** [comment]
Dbeaver uses electron
The issue is with electron

**Comment by szszoke** [comment]
I am a VS Code and Azure Data Studio user and I use them both on Linux and Windows.

Both my MX Master 2S and MX Master 3 are exhibiting the same intermittent horizontal scrolling behavior regardless if I use Linux or Windows.

I pretty much had this issue since owning my MX Master 2S back in 2017.

**Comment by mosesoak** [comment]
Happens with Logitech Control Plus (L510) model as well, using the Logitech Options app on Windows 10.

One clue: while tinkering in the Options app with side scrolling options, horizontal scrolling in vs code started working. **BUT!** when I performed the `Reload Window` command, side scrolling worked briefly (for one notch) then stopped working. 🕵️ 

To me that indicates that while this problem surfaces with Logitech mice, there's definitely some process in electron or vs code that is severing the connection to horizontal scrolling.

**Comment by szszoke** [comment]
@mosesoak the issue also happens on Linux and Options doesn't exist there. Native apps (like Firefox, LibreOffice) doesn't have an issue consuming and reacting to the horizontal scroll events.

**Comment by mosesoak** [comment]
@szszoke kösz -- hopefully the fact that the Reload Window command knocked it out just after the reload started will be a good clue for someone looking into this!

**Comment by gaby64** [comment]
@codebytere @miniak @MarshallOfSound 

pining top contributors since this has gotten zero attention from any of the devs

**Comment by artchess** [comment]
> @codebytere @miniak @MarshallOfSound
> 
> pinging top contributors since this has gotten zero attention from any of the devs

Yes, we need a solution.

**Comment by codebytere** [comment]
There are over 1000 issues on this repository, so we cannot make promises with regard to when we'll be able to spend time on this. However, it is important to note that this may in fact not simply be an Electron issue, and rather a greater Chromium embedding one.

Specifically, per this comment: https://github.com/electron/electron/issues/20874#issuecomment-574775538 it also seems to be happening in Brave, and you will note if you look at the Brave repo that it is not, in fact, an Electron app, through it is likewise based on Chromium.

**Comment by CiriousJoker** [comment]
Possibly related:

- https://github.com/microsoft/vscode/issues/84136

The latest comment over there seems to imply that this is Logitech/Windows issue and not Electron

**Comment by fletching** [comment]
My horizontal scroll works when running VSCode on Mint Linux 20 in a Virtual Box hosted on Windows 10. However, it does not work on VSCode running directly on Windows 10.

**Comment by ahmadalli** [comment]
[this answer](https://superuser.com/a/1237722/104410) fixed it for me (at least for now)

**Comment by ahmadalli** [comment]
also this seems to work: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2096#issuecomment-444653912

**Comment by RubberChickenParadise** [comment]
This is definitely an issue with Logitech options and the way it hooks in to modify the mouse buttons.

Uninstalling options and there are no issues
Running as Admin where options cant hook in correctly and everything works
Change the exe to chrome.exe and logitech options will hook in correctly (though in the latest version of VS code 1.48.2, Electron 7.3.2, Chrome 78.0.3904.130, side scrolling will change tabs not side scroll the text window)

This can be closed out since this is very much outside of Electron as options is changing the normal side scroll mouse inputs.  This is also why users running on systems with out the ability to install options have not had issues.

**Comment by freMea** [comment]
> ![qADFGYiiAm](https://user-images.githubusercontent.com/697707/72460530-a9874e00-37d5-11ea-91c2-334c012b26a9.gif)
> 
> Weird glitch showing above. Simply rolling the scroll wheel left/right over Chrome, even if there's nothing to scroll in it, will fix Electron scrolling. Even without first clicking in Chrome to switch focus. It's enough that the mouse cursor is over Chrome.
> 
> Giving another app focus without using the horizontal scroll wheel in it will pretty reliably result in Electron scrolling being broken.

Same result if you do the same to any window where you know the horizontal scroll works like Windows Explorer, as explained [here](https://github.com/microsoft/vscode/issues/84136#issuecomment-655599016). Every Logitech mouse seems to have this issue. I don’t know if other brand has this feature. Although some linux users report it doesn’t work on their OS, it’s more a Windows specific issue so Microsoft and Logitech should work together to solve this. If anyone have link or email to logitech support/bug report so we can bugging them until they hear their users. This bug has been around all over the net for years with no effect on them.

**Comment by CiriousJoker** [comment]
Customer service won't respond, I even searched a logitech engineers and while I did hear back from him, nothing came out of it...
Pretty frustrating... 😐

**Comment by freMea** [comment]
> Customer service won't respond, I even searched a logitech engineer on Github and while I did hear back from him, nothing came out of it...
> Pretty frustrating... 😐

Let’s go bugging them on social networks until their CM address the issue, sharing the link to this page. Mention @Logitech in most of the SN. If all the users do this, we could eventually get a reaction.

**Comment by servetoz** [comment]
Workaround on Win 10: Run as administrator.

**Comment by vlad-pisanov** [comment]
Found a hacky workaround for my MX Master 3. Previously, horizontal scroll would stop working right after the first scroll. It would stay non-functional until I restarted VS Code.

However if I open a second window (not tab!), switch to it and scroll there, then switch back to my main window, horizontal scroll resumes working and works 100% reliably. 🤷‍♂️

**Comment by CiriousJoker** [comment]
Can someone reopen this issue? Nothing has changed and the issue is present on all Electron versions.

**Comment by freMea** [comment]
It’s a bug from logitech and there is not much to do than push them to fix it.
https://github.com/microsoft/vscode/issues/84136#issuecomment-772319907

**Comment by benaltair** [comment]
Seems like Logitech fixed this in their latest software update: Logitech Options `8.54.106`
It's been working for me for a couple weeks since the update now in VS Code at least. https://github.com/microsoft/vscode/issues/84136#issuecomment-828675056

This issue could possibly be closed if it's working across the board.

**Comment by mosesoak** [comment]
That’s great news, can’t wait to try it! (Although my last update annoyingly knocked out all my settings so I hope it’s less painful this time)

**Comment by JacobDB** [comment]
It's seemed improved for me as well, but only in some apps. VS Code has been working pretty contently, but Spotify is still broken, for example.

**Comment by derwentx** [comment]
Likewise, I'm on version 8.54.106, Windows 10 and still experiencing sideways scrolling issues. Switching from a different app makes scroll inputs work again for a split second, then it goes away.

**Comment by gaby64** [comment]
still breaking for me too

**Comment by benaltair** [comment]
Yes agreed. I'm using the new beta for Logitech Options+ and it's still a problem intermittently.

**Comment by benaltair** [comment]
I've reported the issue directly with Logitech now and it's being escalated. I've mentioned the relevant GH issues. Hopefully they're able to move this forward internally.

**Comment by vtintillier** [comment]
I changed the Logitech Options configuration for Google Chrome from `Navigate between tabs` to `Horizontal scroll`, and now it works fine in VS Code. This solution is OK for me as I disliked the default `Navigate between tabs` behavior 😃 

![image](https://user-images.githubusercontent.com/494652/122732278-6c51a600-d27c-11eb-9e38-206545a2991a.png)

**Comment by tellamon** [comment]
Problem appear with :
- VS Code : 1.56.2
- Logitech Options : some previous version


Problem solved with :
- VS Code : 1.56.2
- Logitech Options : 8.54.161

Hope it helps someone.

**Comment by BukeMan** [comment]
the problem still persists on:
* VS Code: 1.59.1 (Electron 13.1.7)
* Logitech Options: 8.54.161

**Comment by gaby64** [comment]
***** its damn annoying not being able to scroll horizontally

the problem still persists

- VS Code: 1.59.1 (Electron 13.1.7)
- Logitech Options: 8.54.161

**Comment by freMea** [comment]
Please stop complaining. It’s worthless. The problem is known and only Logitech can solve it. Read the comments before posting.

**Comment by gaby64** [comment]
> Please stop complaining. It’s worthless. The problem is known and only Logitech can solve it. Read the comments before posting.

I have reported the issue more then once to Logitech, until its solved, its good to let people know it is still a problem.
Every now and then some claim it has been solved.

Since Logitech is unlikely to act, maybe someone more capable could implement a fix?

**Comment by luiguild** [comment]
Just uninstall Logitech Options and it will work everywhere

**Comment by JacobDB** [comment]
@luiguild that's not a good option, because you lose out on all the customization features.

**Comment by luiguild** [comment]
So it's an open source project, send a PR, hacktoberfest is coming :D

**Comment by dingluo** [comment]
Just some personal experience which might be helpful.

My setup: MX Master 3 + VS Code 1.62.3 (user setup) + Chrome 95.0.4638.69.

I had a application-specific profile in logitech options for chrome which sets horizontal wheel to navigate between tabs. In this case, even if I make a application-specific profile for VS Code to set horizontal wheel to horizontal scroll, the scroll still would not work in VS Code. If the setting in the chrome profile is also set to horizontal scroll, the scroll works in VS Code.

It feels like that settings for VS Code in logitech options is (partially) overridden by the settings for Chrome. Probably has something to do with how the Logitech Options recognize apps.

**Comment by vtintillier** [comment]
Looks like it works now with Logitech Options 9.40.86

**Comment by szszoke** [comment]
I don't even think this is related to Logitech Options. I had the same issue with the 2S and the 3 as well on Linux.

**Comment by Elias-Graf** [comment]
@szszoke I only have this issue on Windows **when Logitec Options is installed**. It a) works when Logitec Options is not installed on Windows and b) works on Linux (Ubuntu 21.10).

I've reported the issue to Logitec and they could reproduce it.

**Comment by CiriousJoker** [comment]
@Elias-Graf Interesting. I've tried reaching out to them for years and nothing came out of it... Keep us updated on the status please!

**Comment by computergnome99** [comment]
[DanyCuba on the Linus Tech Tips forum](https://linustechtips.com/topic/1219444-mx-master-3-horizontal-scroll-in-vscode/?do=findComment&comment=14360795) found that horizontal scroll does work in VS Code when you run it as Administrator. I have tested it on my machine and can verify this does solve the issue.

Obviously not ideal but hopefully gives some further insight into the problem for someone with more inside knowledge.

**Comment by rrickfox** [comment]
> [DanyCuba on the Linus Tech Tips forum](https://linustechtips.com/topic/1219444-mx-master-3-horizontal-scroll-in-vscode/?do=findComment&comment=14360795) found that horizontal scroll does work in VS Code when you run it as Administrator. I have tested it on my machine and can verify this does solve the issue.
> 
> Obviously not ideal but hopefully gives some further insight into the problem for someone with more inside knowledge.

Thank you, this fixed the issue for me

**Comment by Elias-Graf** [comment]
@ciriousjoker As you've told me to keep you posted, here you go. This week I've received an e-mail from the support, stating that they have tested against an internal version (9.60.89, which is not released yet) and it works fine. So look forward to the release of that :).

**Comment by dreamthen** [comment]
Horizontal scrolling affects vertical scrolling. First scroll horizontally and then scroll vertically without lifting. The result is that you cannot scroll......  When can it be resolved?

**Comment by dinvlad** [comment]
@Elias-Graf have you heard from support on when it'll be released, by any chance?

**Comment by s1davide** [comment]
@Elias-Graf  they only plan to update options ?? and logi options +?, They are thinking about updating the options ??and what will they do with the logi options +? And what you say may be true since as of today the logitech options on my pc is in version 9.60.87.

**Comment by leocb** [comment]
Installing the latest [Logi Options+](https://www.logitech.com/en-us/software/logi-options-plus.html) Solved the issue for me

**Comment by s1davide** [comment]
@leocb a current version?, in my case it was the same, the same error.

**Comment by gaby64** [comment]
The problem persists, even after buying a new MX Master 3S

**Comment by Elias-Graf** [comment]
Some time has elapsed and Logitech released a new app called "Logi Options+". The old Logitech Options told me to update to that so I did. Sadly it seems like that app has the same issue. Can anyone confirm?

**Comment by BukeMan** [comment]
Yes, the problem still persists on Logi Options+

**Comment by Elias-Graf** [comment]
I have been informed that the issue should be fixed in **Logitech Options** (not Logi Options+) with the release of the version 9.70 (which will be soon -ish). They said that they don't know about Logi Optins+.

**Comment by gaby64** [comment]
> 

They have been saying it was fixed for years, ill believe it when they do it.

**Comment by spaghettiScreen** [comment]
The 100% reliable fix for me for VSCode with the MX Master 3 on Windows 10 is to open Logitech Options while VSCode is open, and just use the sidescroll once on top of the VSCode window (while Logitech Options is open on screen). I have to do this a few times over the course of the day, but it's the only fix that works for me every single time. 

It's absurd that I have to use weird tricks like this to get features working on what's supposedly a high-end productivity mouse.

**Comment by gaby64** [comment]
> The 100% reliable fix for me for VSCode with the MX Master 3 on Windows 10 is to open Logitech Options while VSCode is open, and just use the sidescroll once on top of the VSCode window (while Logitech Options is open on screen). I have to do this a few times over the course of the day, but it's the only fix that works for me every single time.
> 
> It's absurd that I have to use weird tricks like this to get features working on what's supposedly a high-end productivity mouse.

That is not a fix, do not call it a fix, its a workaround.
And its not really reliable considering you have to do it so often.

**Comment by Elias-Graf** [comment]
Update dropped today. It works for me in VSCode.

**Comment by gaby64** [comment]
I can confirm, fixed for my original MX Master mouse.

Hopefully it will be in Logi Options+ soon.

**Comment by Elias-Graf** [comment]
> Hopefully it will be in Logi Options+ soon.

I'm currently in the process of inquiring about that. But I'm happy that it works at all, all

**Comment by s1davide** [comment]
Guys I can confirm it today I got the update (9.70.68) and now the horizontal scroll is working in the applications developed with electron and the ones I currently use, I'm glad that logitech has listened to their customers, I had even posted this issue on reddit.

**Comment by s1davide** [comment]
The problem continues for Logi+, it was only fixed for Logitech options, so those who have a Mx Master 3s, will have to send many reports to Logitech to fix the problem in Logi+.

**Comment by SogoKato** [comment]
Though they released logi options+ 1.20.833, the issue still continues.

**Comment by D0t-Matrix** [comment]
An update for people, as a workaround I have found working for me: adding the electron app's executable as an application-specific setting in Logi Options+.

I am unsure why this works, however doing this (and copying the settings from global default) forces Logi Options+ to send a standard horizontal-scroll event.

It looks like Logitech decided (for whatever reason) to send some other input that is meant to _emulate_ the side-scroll for any electron-ran application. Doing this has corrected that for me, though I'm unsure why this is even needed. Does show it's an issue on Logitech's side, however.

**Comment by spootle** [comment]
Adding code.exe as a separate setting only temporarily works for me. It gives normal side scrolling when Options+ is opened, but if I then scroll in another app and go back to VS Code it's back to the emulated smooth scrolling which indicates it's back to the weird built in behaviour

**Comment by anthem89** [comment]
The [post](https://github.com/electron/electron/issues/20874#issuecomment-598522213) above from @mattgaspar which explains:

**If you change the "vscode.exe" file name to "chrome.exe", horizontal scrolling works.**

The [reference](https://forum.vivaldi.net/assets/uploads/files/1619906301779-fulogi.png) that he links to proves that Logitech hard coded certain apps (by name) to behave differently. This is pretty silly, but I am just glad someone found a simple solution, even if it is ugly...

**Comment by nornagon** [comment]
It seems like this is an issue with Logitech drivers, not with Electron, so I'm going to close this issue as I don't believe there is any action for the Electron team to take. Feel free to continue using this issue to discuss workarounds and solutions.

**Comment by markuckermann** [comment]
In case it helps anybody: removing the chrome specific actions from logi Options+ 1.34 instantly fixed my issues in VSCode

**Comment by martinlingstuyl** [comment]
> The [post](https://github.com/electron/electron/issues/20874#issuecomment-598522213) above from @mattgaspar which explains:
> 
> **If you change the "Code.exe" file name to "Chrome.exe", horizontal scrolling works.**
> 
> The [reference](https://forum.vivaldi.net/assets/uploads/files/1619906301779-fulogi.png) that he links to proves that Logitech hard coded certain apps (by name) to behave differently. This is pretty silly, but I am just glad someone found a simple solution, even if it is ugly...

This works for me. But it's not a good workaround. 
We can't reach the default settings, so I thought, let's install google chrome and configure it as an application in Logi Options+. This does not solve it 100% though. But it does change something:

The conclusion is that it now works more often. Sometimes it will jerk and stop scrolling. When unfocusing and refocusing the VS Code window, it will start working again.

**Comment by gostega** [comment]
Still not working in Brave on Win 10. Works for me in VSCode.

**Comment by whitesnakeftw** [comment]
MX Master 2S and Logitech Options 9.60.87: renaming code.exe to chrome.exe is the only thing that fixed it (not sure about renaming it to anything else).
