### ISSUE TITLE
The menu of electron app turn white and it leads to hang in Ubuntu 19.10 in VirtualBox.

### ISSUE THREAD

**Issue by jim-king-2000** [electron/electron#21028]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0-beta2
* **Operating System:**
  * Ubuntu 19.10 in VirtualBox 6.0.14, hosted by Win10
* **Last Known Working Electron version:**
  *  None

<img width="503" alt="Untitled" src="https://user-images.githubusercontent.com/7019050/68372933-be63b780-017c-11ea-93c4-4eee5f732517.png">

### Expected Behavior

Show menu normally.
### Actual Behavior

The menu turns white.
### To Reproduce

Run "electron-quick-start" in Ubuntu 19.10 in VirtualBox 6.0.4, hosted by Win10. Close and open the app several times.

### Additional Information

https://github.com/microsoft/vscode/issues/83996

**Comment by jim-king-2000** [comment]
It has been fixed in Visual Studio Code v1.42.1 (Electron 6.1.6).

**Comment by ehanoc** [comment]
This still happens with Visual Studio Code 1.51.1 ( Electron 8.3 )
