### ISSUE TITLE
Crash when print with 'margins' option

### ISSUE THREAD

**Issue by xland** [electron/electron#21167]
Electron Version: 7.1.1
Operating System: Windows 10 (1803)

If I set the 'margins' option when call webContents.print method,
The app will crash with no error message.

```js
let { remote } = require("electron");
let webContents = remote.getCurrentWebContents();
webContents.print(
  {
    margins: {
      marginType: "custom",
      top: 30,
      bottom: 0,
      left: 0,
      right: 0
    }
  },
  (success, errorType) => {
    if (!success) console.log(errorType);
  }
);
```

**Comment by codebytere** [comment]
Yeah - printing is a mess in 7 right now (apologies) but is fixed with 8. I'll try to backport some stuff but Chromium has done massive refactors in there so it's been a struggle trying to re-invigorate it across platforms.

**Comment by xland** [comment]
Thanks

**Comment by almas** [comment]
It does not fixed on version 8.0.0-beta.5 on Windows. 
Crashed electron and closed just after print. Also it does not remove margins with "none" and "custom" settings. I also tried @page { margin: 0; } CSS but could not have luck with version 7.1.2 also.

`npm ERR! code ELIFECYCLE
npm ERR! errno 3221225725
npm ERR! myproj@1.0.0 dev: `cross-env NODE_ENV=DEV electron .`
npm ERR! Exit status 3221225725
npm ERR!
npm ERR! Failed at the myproj@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by acutus** [comment]
Facing the same issue. Electron crashes with exit code: 3221225477

For me at least this seems to only affect marginType: 'custom' with custom margins provided. With marginType: 'none' | 'printableArea' | 'defaults' there was no crash.

Electron Version: 7.1.1
Operating System: Windows 10
