### ISSUE TITLE
Always matches `prefers-color-scheme: light` media-query (no dark mode)

### ISSUE THREAD

**Issue by konsumer** [electron/electron#21427]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3 & 8.0.0-beta.4
* **Operating System:**
  * Linux Manjaro 18.1.3

### Expected Behavior
Electron should behave like Chromium with `prefers-color-scheme` media-queries.

### Actual Behavior
Electron always matches `prefers-color-scheme: light` so OS dark-mode isn't selected in media-query.

### To Reproduce

I made an electron-fiddle [here](https://gist.github.com/dc86e8931bef1781db8fbd0a6faf76ee). You can reproduce issue by switching to dark theme in your OS. See `<link>` tags in `<head>`.

### Screenshots
This is a comparison of same web-page in electron 7.1.3 (right) and chromium 78.0.3904.97 (left) on Arch/Manjaro. I am switching between "Adwaita-dark" and "Adwaita" themes on gnome.

![Peek 2019-12-06 20-06](https://user-images.githubusercontent.com/83857/70368820-84adcb80-1864-11ea-876a-21ad7c612c1e.gif)

**Comment by gombosg** [comment]
Yep, same for me.
See also [VSCode](https://github.com/microsoft/vscode/issues/91169), [Joplin](https://discourse.joplinapp.org/t/feature-idea-automatic-dark-light-theme-switching-according-to-os/6010/8).

For me `window.matchMedia((prefers-color-scheme: light)).matches === true` also returns always true in Chromium regardless of theme. Works in FF properly though.

**Comment by Prinzhorn** [comment]
@konsumer for me this is fixed in 9.0.0-beta.13 (see #22900). Can you confirm?

**Comment by gombosg** [comment]
@Prinzhorn 
I tried an Electron fiddle with 9.0.0-beta.13, but still doesn't seem to work in GNOME 3.34. :disappointed: 
I reckon it's because of [this unsolved Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=998903) . `prefers-color-scheme` doesn't at all seem to be working properly in Linux.

**Comment by Prinzhorn** [comment]
@gombosg oh I understand, these are two separate things. What was fixed in 9.0.0-beta.13 was a regression where explicitly setting `nativeTheme.themeSource` would not work anymore. This is about having `nativeTheme.themeSource = 'system'` work automatically with the system theme on Linux.

**Comment by ckerr** [comment]
#23678 does appear to make things better (and I also like the way it decides whether a theme is dark or light) but unless I'm missing something it doesn't appear to be a full fix for this bug.

When switching themes (e.g. between yaru-dark and yaru-light, or between adwaita and adwaita-dark as described by @konsumer), the gist above does not change its appearance, and when I look in the inspector, window's `prefers-color-scheme` value doesn't change. (Tested on master @ 3fa42999394502c664037091a0f356be94083541)

I've confirmed that #23678 does ensure `set_use_dark_colors()` is called so that's a step in the right direction, but that doesn't appear to be the whole fix.

**Comment by konsumer** [comment]
I am running Pop!OS 20.04 (very similar to Ubuntu 20.04) and chrome  83.0.4103.97 doesn't seem to work right, anymore.
I made [this codepen](https://codepen.io/konsumer/pen/NWxPaaO) to demonstrate:

![Peek 2020-06-04 14-57](https://user-images.githubusercontent.com/83857/83814791-d0a2c700-a673-11ea-80a6-786384214394.gif)

You can see, weirdly, it seems to understand to change the window decorations to light/dark, but the content doesn't change.

Here I am testing with same HTML, in that electron-fiddle, with same issue:

![Peek 2020-06-04 15-00](https://user-images.githubusercontent.com/83857/83815024-4313a700-a674-11ea-9ec6-8129b161fa1b.gif)

**Comment by konsumer** [comment]
I tested on windows 10, and it seems to work right:

latest chrome:

![Peek 2020-06-04 15-09](https://user-images.githubusercontent.com/83857/83815643-7efb3c00-a675-11ea-876c-759628ea910e.gif)

latest electron-fiddle:
![Peek 2020-06-04 15-13](https://user-images.githubusercontent.com/83857/83815870-fe890b00-a675-11ea-8ea4-1bad3cd6be7e.gif)

**Comment by konsumer** [comment]
I also tried same source in [neutralino](https://neutralino.js.org/), a sort of competing project, which uses [webkitgtk](https://webkitgtk.org/) and it works as expected:

![Peek 2020-06-04 17-24](https://user-images.githubusercontent.com/83857/83823249-61839d80-a688-11ea-8a07-9fec79432cac.gif)

**Comment by zcbenz** [comment]
It seems that GTK theme observer is not working, and could not update dark mode setting when it is changed:

```
linux_ui->GetNativeTheme(nullptr)->AddObserver(dark_theme_observer_.get());
```

**Comment by zcbenz** [comment]
I would not be able to look into this for a while, feel free to dig more if anyone is interested.

**Comment by purple-cmd** [comment]
still have this bug :( pls help us linux users.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
