### ISSUE TITLE
electron screen capture failure on chromium based apps

### ISSUE THREAD

**Issue by its-me-ilia** [electron/electron#21687]
I am building application with `desktopCapturer` and while recording chromium based apps or electron apps (such as Slack, VS Code, Atom, Postman, etc.) it shows black screen, currently there are many open issues on electron repository, but as it seems it is fixed

[https://bugs.chromium.org/p/webrtc/issues/detail?id=10734](issue)

it needs some kind of flag with name of `PW_RENDERFULLCONTENT` to be passed, I can not exactly get where should i pass this flag or how can i do it, and i believe there are many developers suffering from this problem, so how is it possible to add this flag? Thanks in advance!

**Comment by aabuhijleh** [comment]
Check #6599

This is a well known issue that was never fixed in Electron

**Comment by its-me-ilia** [comment]
> Check #6599
> 
> This is a well known issue that was never fixed in Electron

[https://github.com/electron/electron/issues/6599#issuecomment-562716592](6599) answer,check this!

**Comment by codebytere** [comment]
@its-me-ilia please fill out the required template including version; the linked CLs which fix this problem should be in 8 already.

**Comment by TongDaDa** [comment]
@codebytere Did you mean the issue will solve in electron v8?

**Comment by TongDaDa** [comment]
I also have the same problems

**Comment by its-me-ilia** [comment]
@TongDaDa electron 8.x is not released yet, current version is 7.1.9 so we should wait for updates

**Comment by TongDaDa** [comment]
@its-me-ilia I know, thank you. 🌹

**Comment by aabuhijleh** [comment]
You can install and try out beta releases to see if your issues are fixed or not

```sh
npm i electron@8.0.0-beta.7
```

**Comment by TongDaDa** [comment]
It is very risky, and can not use this version in production env. @aabuhijleh

**Comment by aabuhijleh** [comment]
You can use it to test if v8 solves your issue or not. You probably shouldn't use it in production.

If your problem was not solved, you should open an issue in this repository.

**Comment by TongDaDa** [comment]
@aabuhijleh Okay

**Comment by electron-triage** [comment]
Reported as fixed in Electron 8.x

**Comment by masudhossain** [comment]
Has this version been fixed? if so what version?

**Comment by DakuangmingZheng** [comment]
> Has this been fixed? if so what version?

I have the same problem. I tried version 27.0.0, but the problem remains unresolved.
