### ISSUE TITLE
Support for Native File System API

### ISSUE THREAD

**Issue by packetstracer** [electron/electron#23440]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Getting the following error when accessing this native file system method in window object.

Native File System API method: chooseFileSystemEntries()
Error: Unhandled Rejection (TypeError): window.chooseFileSystemEntries is not a function

### Proposed Solution

Create an Electron specific version/branch with latest chromium V8 version so it includes latest API versions and experimental features in order to be able to develop with next gen web features.

### Alternatives Considered

Provide a possibility to config electron with an specific chromium V8 version with its corresponding specific settings/flags for development environments.

### Additional Information

Example code:
```typescript
async function getFileHandle (options = {}) {
  const handle = await window.chooseFileSystemEntries(options)

  return handle
}

async function openFile (options = {}) {
  const handle = await getFileHandle()
  const file = await handle.getFile()
  const text = await file.text()

  return file
}
```

**Comment by packetstracer** [comment]
done via appendSwitch method, enabling experimental features

`app.commandLine.appendSwitch('enable-experimental-web-platform-features');`

**Comment by jfahrenkrug** [comment]
@packetstracer Could you please elaborate on how to do this? I've added your line in my `index.ts` right after `import { app, BrowserWindow } from 'electron';`, but I still get `(TypeError): window.chooseFileSystemEntries is not a function` when trying to call `window.chooseFileSystemEntries` in my renderer.
