### ISSUE TITLE
Devtron will not load in 9.0.0

### ISSUE THREAD

**Issue by bendemboski** [electron/electron#23676]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0
* **Operating System:**
  * MacOS
* **Last Known Working Electron version:**
  * 8.3.0

### Expected Behavior
Running `require('devtron').install()` from the renderer process console or main process successfully installs the devtron extension

### Actual Behavior
If run from the main process it fails with:

```
(node:52975) UnhandledPromiseRejectionWarning: Error: Loading extension at /private/tmp/foo/node_modules/devtron failed with: The 'manifest_version' key must be present and set to 2 (without quotes). See developer.chrome.com/extensions/manifestVersion.html for details.
(node:52975) UnhandledPromiseRejectionWarning: Error: Loading extension at /private/tmp/foo/node_modules/devtron failed with: The 'manifest_version' key must be present and set to 2 (without quotes). See developer.chrome.com/extensions/manifestVersion.html for details.
```

and similar if it is run from the renderer process' console

### To Reproduce
Run `yarn init -y && yarn add --dev electron@9 devtron`. Put this in `index.js`:

```javascript
const { app, BrowserWindow } = require('electron')

function createWindow () {
  // setImmediate() to work around https://github.com/electron/electron/issues/23656
  setImmediate(() => require('devtron').install());

  // Create the browser window.
  let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // and load the index.html of the app.
  win.loadFile('index.html')
}

app.whenReady().then(createWindow)
```

Run `yarn electron .` and observe the error in the console. Open the devtools console in the browser window and run `require('devtron').install()` -- same result.

**Comment by miniak** [comment]
Please report to https://github.com/electron-userland/devtron/issues

**Comment by bendemboski** [comment]
@miniak any clue on what changed on the Electron/Chromium side that might have started causing this failure in 9.x to tell the Devtron folks?

**Comment by jphw** [comment]
@bendemboski hi. devtron repo is pretty much dead, no commits since 2018. so imo it's Electron team who should fix the issue since devtron worked on before E9

**Comment by Slapbox** [comment]
> "WARNING: Devtron is currently unmaintained."

If https://www.electronjs.org/devtron is going to stay live then I think that Devtron issues should not be ignored by the Electron team, especially since this issue persists.

If it's only usable on versions of Electron the team no longer supports, then I think that page should be removed. 

Devtron was (is) a crucial tool and to lose it just when Electron starts really moving everyone towards IPC communications is a _major_ loss for developers.
