### ISSUE TITLE
nativeTheme shouldUseDarkColors not respecting Linux system preference

### ISSUE THREAD

**Issue by davidwinter** [electron/electron#23861]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0
* **Operating System:**
  * Ubuntu 20.04 x64

### Expected Behavior

If my Ubuntu system has it's Window Theme appearance set to Dark, then `nativeTheme.shouldUseDarkColors` should return `true`.

Also, listening for the `updated` event on `nativeTheme` should also trigger if switching between window themes.

### Actual Behavior

When Window Theme is set to dark, `nativeTheme.shouldUseDarkColors` returns `false`.

The `updated` event is never triggered when alternating between window themes.

### To Reproduce

See: https://github.com/davidwinter/electron-native-theme/blob/master/main.js

```js
const {nativeTheme} = require('electron');

...

console.log(`Dark colours: ${nativeTheme.shouldUseDarkColors}`);

nativeTheme.on('updated', () => {
	console.log('system theme changed');
});

...
```

![Screenshot from 2020-05-31 09-07-37](https://user-images.githubusercontent.com/9681/83347654-48908a80-a31e-11ea-8b9b-6744a5e11a44.png)

**Comment by MarshallOfSound** [comment]
Fixed in #23678

**Comment by davidwinter** [comment]
@MarshallOfSound thanks for the fix. 

On the launch of the app, the setting is being retrieved correctly, however, if the theme changes while the app is running, the `updated` event is not triggered. 

Example repo above updated with v9.0.2

**Comment by davidwinter** [comment]
@MarshallOfSound can confirm this is still not working with v9.0.5.

If the theme changes while the app is launched, the `updated` event is not being triggered.

**Comment by davidwinter** [comment]
Demo: https://github.com/davidwinter/electron-native-theme

**Comment by davidwinter** [comment]
@MarshallOfSound this is still not working for v10.1.3. Could this issue please be reopened?

**Comment by davidwinter** [comment]
> @MarshallOfSound this is still not working for v10.1.3. Could this issue please be reopened?

I've created a new issue to track this for 10.1.3 as I'm worried this issue has been closed, and the request to reopen may get missed.

https://github.com/electron/electron/issues/25925
