### ISSUE TITLE
Ability to disable pdf viewer

### ISSUE THREAD

**Issue by t57ser** [electron/electron#24977]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Since electron 9, pdf viewer has been implemented but does not fully work:
https://github.com/electron/electron/issues/22178
https://github.com/electron/electron/issues/24458
https://github.com/electron/electron/issues/22180
There should be an option to disable this feature so that it is possible to upgrade to a newer electron version and keep old working behavior until the pdf viewer gets fully fixed.

### Proposed Solution
Add a flag to disable the pdf viewer

### Alternatives Considered
I have checked if there is a chrome command line flag to handle this but could not find anything

**Comment by leonheess** [comment]
Could be closed, right? All issues have been fixed.

**Comment by Jelmerro** [comment]
I would still like an option to disable it because it's still broken in others ways: it claims the user keyboard input away from any listeners, doesn't allow custom listeners or shortcuts, and there is no easy option to download pdfs instead of using the (broken) viewer. Please add the option to disable it regardless of how well it works (or not), because some users just don't want it to be in Electron at all.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
