### ISSUE TITLE
Electron programs leak onto second monitors

### ISSUE THREAD

**Issue by Tamberlox** [electron/electron#26638]
### Expected Behavior
The programs should fit into the monitor and not go beyond.

### Actual Behavior
The programs leak onto the other monitors.

### To Reproduce
Install Discord and open it in maximized mode.

### Screenshots
![2020-11-22 14_17_40-](https://user-images.githubusercontent.com/56069014/99904871-07c26e80-2cce-11eb-8a19-84b023b0b1cb.png)

### Additional Information
Everyone using Discord on Windows 10 has this issue. The community would highly appreciate it if this bug were fixed.

**Comment by RichardTea** [comment]
Also affects Teams, is a very longstanding issue.
See:
https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/38463106-maximized-window-bleeds-onto-second-monitor

Was previously issue #5267, that issue appears to have been closed without solution.

**Comment by zcbenz** [comment]
This had been fixed with https://github.com/electron/electron/pull/25940.

**Comment by EdgeyDoctour** [comment]
I'm not sure whether to create new issues but this bug is not fixed and still happens in electron apps intermittently for me such as spotify, as seen by the white line between my two leftmost monitors and still happens with discord randomly and has not been fully fixed.
![Image](https://github.com/user-attachments/assets/399bb513-1b78-4cb8-93f7-227646d1f5e1)

**Comment by EdgeyDoctour** [comment]
I hope oyure treated exactly liek the women in your nativce country for this issue being unfixed for so many years. cant even make the chromium wrapper work properly after all this time.

**Comment by EdgeyDoctour** [comment]
If a human ever reads this I hope you're treated exactly liek the women in your nativce country for this issue being unfixed for so many years. Cant even make the chromium wrapper work properly after all this time what a joke.
