### ISSUE TITLE
BrowserView attached with non zero `x` or `y` bounds has an invisible draggable area

### ISSUE THREAD

**Issue by kevinlinv** [electron/electron#27204]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.6 and beyond
* **Operating System** macOS 10.15.7
* **Last Known Working Electron version:** 10.1.5

### Expected Behavior

The end part of the BrowserView **should not be** draggable

### Actual Behavior

The end part of the BrowserView **is** draggable

### To Reproduce

Load electron fiddle friendly gist here https://gist.github.com/kevinlinv/9b2b1d078920b7dbf4efce015fda9f6e

<details>
<summary>Collapse here for the code in case gist is not loading</summary>

`index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <link rel="stylesheet" type="text/css" href="./styles.css">
    <style>
      * { margin: 0px; padding: 0px; }
    </style>
  </head>
  <body>
    <h2>This is the content of the window - try to drag the bottom part of the window</h2>
    <script>
      // You can also require other files to run in this process
      require('./renderer.js')
    </script>
  </body>
</html>
```

`main.js`
```js
const {app, BrowserView, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })
  mainWindow.loadFile('index.html')

  const browserView = new BrowserView();
  browserView.setBackgroundColor('#000000');
  browserView.setAutoResize({
    width: true,
    height: true,
    horizontal: false,
    vertical: false,
  });

  const { width, height } = mainWindow.getContentBounds();
  const windowContentHeight = 40;
  mainWindow.setBrowserView(browserView);
  browserView.setBounds({
    x: 0,
    // Setting the y point on the bounds causes the same amount of px
    // being draggable at the bottom of the view
    y: windowContentHeight, 
    width,
    height: height - windowContentHeight,
  });
}

app.whenReady().then(createWindow)

app.on('window-all-closed', app.quit)
```

`package.json`
```json
{
  "name": "browser view draggable",
  "productName": "browser view draggable",
  "description": "My Electron application description",
  "keywords": [],
  "main": "./main.js",
  "version": "1.0.0",
  "scripts": {
    "start": "electron ."
  },
  "dependencies": {},
  "devDependencies": {
    "electron": "10.1.6"
  }
}
```
</details>

Note that in this example, I am modifying the `y` bound and as result the same amount of px is draggable towards the end of the view, the same happens if we modify `x` but on a different axis.

https://user-images.githubusercontent.com/44967897/103723126-7b71ce00-5025-11eb-9084-8179afe9fda7.mp4

### Additional Information

I believe this is related to https://github.com/electron/electron/pull/26145
Which originally causes issues: https://github.com/electron/electron/pull/27147, https://github.com/electron/electron/pull/26690

**Comment by kevinlinv** [comment]
cc @codebytere as I see you're the assignee for the other similar issues 🙂

**Comment by codebytere** [comment]
hey @kevinlinv - i already fixed this actually :D https://github.com/electron/electron/pull/27147 should take care of it, out in a new release soon

**Comment by kevinlinv** [comment]
Ah, cool 🙈 thanks for the quick response, lets close this issue then 👌

**Comment by codebytere** [comment]
If you don't see it fixed in the next release though please ping me and i can investigate and reopen!

**Comment by kevinlinv** [comment]
👌 Wil do

**Comment by ruihanzhao** [comment]
I am still seeing this issue on 10.4.0. It's a very similar situation where the part shifted in the BrowserView has an invisible draggable region on the other side. I do notice that this only happens though if inside the browserview's webcontents itself there is any kind of draggable region (does not matter if set to drag or no-drag), similar to the last comment on https://github.com/electron/electron/issues/27112. This is preventing us from upgrading our app to electron 10 or 11, previously we were on 8 and it was working fine. Any updates on if this issue is still being looked into?

**Comment by codebytere** [comment]
@ruihanzhao can you please open a new issue and tag me?
