### ISSUE TITLE
"File/Archive" dropdown menu is showed in wrong monitor

### ISSUE THREAD

**Issue by RafaelLinux** [electron/electron#27723]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

* **Electron Version:**
VS Code version: Code 1.51.1 (e5a624b, 2020-11-10T23:31:29.624Z)
Electron Fiddle 0.20.0-1 (rpm version)https://github.com/microsoft/vscode/issues/111308

* **Operating System:**
OS version: Linux x64 5.3.18-lp152.50-default
Operating System: openSUSE Leap 15.2
KDE Plasma Version: 5.20.90
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.3.18-lp152.63-preempt
OS Type: 64-bit

### Expected Behavior
The dropdown menu should appear on same monitor where Electron is maximized.

Configuration:
Two monitors. Monitor 1 at left (secondary monitor) Monitor 2 at right side (primary monitor). 

### Actual Behavior
The dropdown menu appears on on left side monitor, not where Electron is maximized.

### To Reproduce
1 - Open Electron
2 - Maximize Electron (if not maximized yet) on monitor 2
3 - Click on "Archive" (Files)

I tried with other GTK based applications (Chorme, Inkscape, Opera ...) and no problems like this at all. Dropdown menus appears in same monitor than application.

### Screenshots
![photo_2021-02-12_21-30-12](https://user-images.githubusercontent.com/13048959/107819559-a9130b00-6d79-11eb-87df-2f5a53349387.jpg)

**Comment by miniak** [comment]
@RafaelLinux you are supposed to report affected Electron version, not VScode or other products.

**Comment by RafaelLinux** [comment]
Well, is right that a talk and took screenshot from VSCode, cause I reproduced they in Fiddle previously, following what someone wrote me here:
https://github.com/microsoft/vscode/issues/111308#issuecomment-736265617

So, YES, I installed and tried Fiddle (as I wrote [in this link](https://github.com/microsoft/vscode/issues/111308#issuecomment-738749468)) and then, I told here what's happening. That's the issue. After check what deepak1556 told me, I uninstalled Fiddle (I guess there is some relation about Fiddle and VSCode) and the published issue here.

I'm sorry if not the right place, but follow the logical steps to tell to whatever the issue. As a simple "VSCode" (not Fiddle or Electron) user, I can't do more.

Best regards

**Comment by cdarken** [comment]
I get the same behavior on the actual Electron Fiddle application, also when downloading and running the last 12 version. The issue appears to be fixed on the 13.x versions, starting with the first beta available in the dropdown.

**Comment by nornagon** [comment]
Sounds like this is fixed in 13.x, so I'm going to close this issue.

**Comment by RafaelLinux** [comment]
Finally, my o.s. got version 1.57.1 of VSC and effectively , is solved!!!!

Thank you. That bug was very annoying.

**Comment by chnavarro** [comment]
The issue is not solved on 
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.19.4-200.fc36.x86_64
