### ISSUE TITLE
Allow vibrancy effect

### ISSUE THREAD

**Issue by wisesascha** [electron/electron#3002]
Actually achieving vibrancy is fairly easy. You simply make the NSVisualEffectView the content view of the mac window. The issue with this is that it blurs the whole window, which is obviously not ideal. The way I see it there are couple different ways of going about this. There could be an API that allows you to create these VisualEffect views and then update their position and size. This may have issues with timing though, as things like element resizes would have to go through chromium to JS and then back to C++. Now this may prove to be negligible. The other solution would be to create a css property that can achieve this. This would prove to be harder. I am not completely sure where CSS is parsed, but a starting place may be the code behind `-webkit-app-region`. This seems like the most ideal way to implement this as it allows people to easily style their elements with it.

**Comment by dkfiresky** [comment]
NSVisualEffectView could be injected into NSWindow content view. The only problem is background of a web view, which should be transparent in order to view the NSVisualEffectView view.

**Comment by Tribex** [comment]
Also see the webkit implementation which would allow such an effect in pure CSS, were it ported and included in Blink/Chromium. https://www.webkit.org/blog/3632/introducing-backdrop-filters/

**Comment by dkfiresky** [comment]
:+1: +1 for the backdrop filters

**Comment by wisesascha** [comment]
The issue with using backdrop filters is that they wouldn't render through
to background apps. As far as I know the only way to achieve this feature
is the  use of a NSVisualEffectView or something custom. We could modify
backdrop filters to achieve this, but that may prove to be difficult.

**Comment by Tribex** [comment]
@wisesascha Ah, I figured they'd probably cover that. Not sure how that would work.

**Comment by ggamel** [comment]
Having the ability to easily toggle vibrancy will bring apps under OS X even closer to native. :+1: on adding this effect as a toggle.

**Comment by dkfiresky** [comment]
For basic vibrancy effect background of web view should be transparent and NSWindow appearance set to dark/light and it should have NSVisualEffectView view.

**Comment by evgenyzinoviev** [comment]
For everyone interested in Vibrancy effect I've made a small example on how to do it https://github.com/evgenyzinoviev/electron-vibrancy-demo/commit/7417821ad8f7ff6e9c669a3c3da35133c128f160

**Comment by daviddfm** [comment]
Being able to enable blur purely on the Mac window behind BrowserWindow would be huge.  No need to support HTML blur - the right blur effect would blur against the Mac's background.  It would give Electron apps a native feel which could be visible in any part of the HTML page simply by using background:transparent;  Consider this a vote for enabling this alongside transparent:true with something like transparent_blur: 10;

**Comment by knpwrs** [comment]
Count :+1: for me as well. Is there anything in particular that would prevent this from shipping if somebody were to formalize the example by @evgenyzinoviev into a pull request?

**Comment by ggamel** [comment]
It would be really quite nice if @evgenyzinoviev or anyone else with understanding of [**NSVisualEffectView**](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSVisualEffectView_Class/) opted to submit a PR for Vibrancy. Had I the ability and experience, I'd work on this.

This is an enhancement many will utilize.

**Comment by evgenyzinoviev** [comment]
Vibrancy depends on enabled transparency, and since 0.36 (or since Chromium 47, more precisely) Electron has troubles with it. Right now I'm writing a project that has blurred transparent window and I'm forced to stick to 0.35 with patches because of that.

I'm going to contribute this feature to Electron someday if nobody overtake me, but with transparency bug now it looks pretty terrible. I hope that Chromium guys will fix it. This should be done at first.

**Comment by tommoor** [comment]
Super interested in this are the transparency issues still present?

**Comment by evgenyzinoviev** [comment]
@tommoor yes. Compared to Chromium 47, 49'th is much better but still not perfect. There is related issue: https://github.com/atom/electron/issues/4157

**Comment by EnricoMonese** [comment]
+1
Before porting my app to electron, in Xcode I simply put a NSVisualEffectView behind a web view with a transparent background. It might not have been the 'right' way to do it but it worked. Now I'm stuck with a white background.
![schermata 2016-06-10 alle 01 17 29](https://cloud.githubusercontent.com/assets/19847464/15949617/2e81ba9e-2ea9-11e6-8931-fcd27f22d2a4.png)

**Comment by oskarkrawczyk** [comment]
Is there an official stance from the Electron team on this? 

Any stance it better than none. If you're not willing to get this in, just let us know.

**Comment by fritx** [comment]
+1

**Comment by paulcbetts** [comment]
Nobody on Electron team is against this, someone submit a PR :)

**Comment by knpwrs** [comment]
Not sure how relevant this is, but my Chrome just updated to 52 (latest version mentioned in this issue is 49) and includes vibrancy in the tab bar:

![image](https://cloud.githubusercontent.com/assets/174864/17598508/e8ca50be-5fc8-11e6-80ac-08a0532fc800.png)

**Comment by paulcbetts** [comment]
@knpwrs The tab bar is rendered natively (i.e is not HTML), so it doesn't help us much :cry:

**Comment by scherii** [comment]
I'm just going to leave this here…
https://github.com/evgenyzinoviev/electron/commit/7417821ad8f7ff6e9c669a3c3da35133c128f160

**Comment by MikeLP** [comment]
Hey guys! Any updates?

**Comment by paulcbetts** [comment]
It'll update when someone does it!

**Comment by arkenthera** [comment]
It would be awesome if this gets implemented. In Windows 10, I think it is possible using ```SetWindowCompositionAttribute```

**Comment by miniak** [comment]
`SetWindowCompositionAttribute` is undocumented API

**Comment by sidneys** [comment]
Has there been any progress on this? Have the upstream chromium transparency issues been resolved as of Electron 1.4.0 / Chromium 53? Looking forward to this.

**Comment by stanleyxu2005** [comment]
This will be a fantastic visual effect. I tried with `BrowserWindow.webPreferences.experimentalFeatures=true` and then use css3 filter `-webkit-backdrop-filter:blur(1px)`. But still no luck. Wait for someone's PR

**Comment by akashwoz** [comment]
@stanleyxu2005 
try **`app.commandLine.appendSwitch('--enable-experimental-web-platform-features');`** 
in **`main.js`**, use **`backdrop-filter: blur(10px);`** in CSS
It works and here's the screenshot taken on Linux
[![Selection_259.png](https://s14.postimg.org/z0xnba5y9/Selection_259.png)](https://postimg.org/image/6o25ktk7x/)

**Comment by oskarkrawczyk** [comment]
@akashwoz it's not what this ticket is about. Window vibrancy effect is something completely different than backdrop blur.

**Comment by arkenthera** [comment]
Hey guys, until this gets implemented in Electron,I am presenting a very hacky way to achieve this effect. Basically create a native addon, feed the native window handle, call native APIs to create the vibrant view. It only **works on Windows 10**, extending to Win8 and Win7 shouldn't be hard. If there are people who want to use it I'd be willing to implement Win8/Win7 and Linux version. 

Here is a screenshot:

![](http://i.imgur.com/yvkK4mY.png)

The addon uses ```SetWindowCompositionAttribute``` on Windows 10, which is a private API, meaning that Microsoft can change this API any time and break the addons functionality. ```SetWindowCompositionAttribute``` is being used by OS for blurring behind the start menu, notification center etc.  
Here is the addon [electron-vibrancy](https://github.com/arkenthera/electron-vibrancy)

## Problem with MacOS
```browserWindow.getNativeWindowHandle()``` returns ```NSView*``` on macOS but I couldn't get the ```NSView*``` on C++ side (#7460). If anyone is willing to help, It'd be awesome.

**Comment by MikeLP** [comment]
Hey. It's awesome! Thanks for addon. So we will wait MacOs support.

**Comment by scherii** [comment]
@arkenthera Would this https://github.com/electron/electron/issues/7460#issuecomment-254989875 by @zcbenz help with support for macOS?

**Comment by arkenthera** [comment]
Update: Mac version of [electron-vibrancy](https://github.com/arkenthera/electron-vibrancy) will be live probably this weekend. You can try the test app on mac now and get something like this.

![](http://i.imgur.com/J59ptMC.png)

Also light/dark materials are available through options object. Thanks for @scherii for his help on testing.

**Comment by controversial** [comment]
@arkenthera Would you be willing to submit a PR for this?

**Comment by arkenthera** [comment]
There is no Electron member response on this matter for over a year so I wouldn't do it.But 
looks like someone already did it (#7898). I hope it gets merged!

**Comment by kevinsawicki** [comment]
Fixed by #7898 and release in 1.4.7, closing this out.

**Comment by matthiasg** [comment]
@arkenthera #7898 only supports mac while https://github.com/arkenthera/electron-vibrancy supports windows too. Any specific reason for only merging Mac ?

**Comment by danbulant** [comment]
@kevinsawicki shouldn't be closed as this supports only MacOS, not windows or linux. (which is quite sad, I would love to see those effects on Linux)

**Comment by limbo-official** [comment]
> @kevinsawicki shouldn't be closed as this supports only MacOS, not windows or linux. (which is quite sad, I would love to see those effects on Linux)

The same... Really wish to use it. I've lost all desire to develop desktop app for linux on Electron because of lack of this effect =(
 And I would like to contribute, but dont know how to do it exactly. Do I need to write a plugin on GTK for Electron or what?

**Comment by embu18** [comment]
> @kevinsawicki shouldn't be closed as this supports only MacOS, not windows or linux. (which is quite sad, I would love to see those effects on Linux)

The same... Really wish to use it. I've lost all desire to develop desktop app for linux on Electron because of lack of this effect =(
And I would like to contribute, but dont know how to do it exactly. Do I need to write a plugin on GTK for Electron or what?

**Comment by adel-sbeh** [comment]
When will this come to windows? ~~(at least windows 10)~~
It's possible to get a blurred window on Windows 10 using this module: https://github.com/Seo-Rii/electron-acrylic-window
It's pretty stable.
<a href="https://ibb.co/Bg4mvFj"><img src="https://i.ibb.co/MR8bKQp/2020-10-26-14-10-38.png" alt="2020-10-26-14-10-38" border="0"></a>

**Comment by kylewelsby** [comment]
Unless you make an up-to-date pull request, never.   This ticket has been
open for years with no progression.


Kind Regards

Kyle Welsby
Director, MeKyle LTD
Mobile +44 757 5790 552
Email kyle@mekyle.com
Website https://mekyle.com

**Comment by adel-sbeh** [comment]
Hmmm, ok. I'll try to get in contact with the module owner to make a pull request.

**Comment by FVellu** [comment]
Still nothing? Would be cool to have in vs code

**Comment by 0xENDER** [comment]
I believe they have been working on this recently. (IDK if it was released or not)
