### ISSUE TITLE
[Bug]: Possibly broken user agent client hint

### ISSUE THREAD

**Issue by webdevmario** [electron/electron#30201]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2

### What arch are you using?

x64

### Last Known Working Electron version

12.0.15

### Expected Behavior

Checking `navigator.userAgentData` in Chrome 91 returns an array of brands appropriately. Electron 13/14 do not return anything.

This appears to then become a problem for my situation. I am posting a form with hidden variables to a third-party vendor I work with. This form post ultimately loads an iframe.

Expected: As it does in Chrome 91, load the iframe from this third-party vendor.

### Actual Behavior

A header of "sec-ch-ua" is included in the request to the third-party vendor and it is blank. They are rejecting the post because of an invalid header. I suspect this is because Chrome 13/14 does not make this hint data made available correctly.

I tried loading various sites in Chrome 91 that do load brand names in Electron 13/14 and they are empty if you review `navigator.userAgentData`.

**Comment by quanglam2807** [comment]
I confirmed this bug. 

`navigator.userAgentData` and `navigator.userAgentData.getHighEntropyValues` return empty values.

**Comment by Swastyy** [comment]
@webdevmario Hi, is this issue fixed? If not, I want to work on this.

**Comment by nornagon** [comment]
I have a branch which starts on this, but it interferes with some other UA overriding stuff, so it's not quite straightforward. https://github.com/electron/electron/compare/navigator-useragentdata is my WIP, for reference.

**Comment by phryneas** [comment]
We had problems with this as the empty header triggered a WAF.
Not really a solution, but a mitigation strategy until this gets fixed:
```
app.commandLine.appendSwitch('disable-features', 'UserAgentClientHint');
```

**Comment by jarek-foksa** [comment]
I can reproduce this bug with Electron 19.0.3 running on macOS 12.4. This should have higher priority as Chrome Dev Tools are now instructing developers to migrate away from `navigator.userAgent` to `navigator.userAgentData`.

<img width="482" alt="Screen Shot 2022-06-06 at 12 02 58" src="https://user-images.githubusercontent.com/193371/172148990-dfe3328d-a2ad-4749-a8c3-c6126241d09b.png">

**Comment by nornagon** [comment]
Cleaned up and finished off my branch, #34481 should fix this.

**Comment by Shamar** [comment]
Hi, looks like client hints are still broken in electron 25.4.0: by setting app.userAgentFallback, the User-Agent header is correctly set in requests, but clients hints such as SEC-CH-UA, SEC-CH-UA-MOBILE and SEC-CH-UA-PLATFORM are not (despite easy to reconstruct from the userAgentFallback.

Also the navigator.userAgentData completely ignores the userAgentFallback, while the navigator.userAgent seems correctly set.
