### ISSUE TITLE
[Bug]: GPU process crashes when electron is in a folder with unicode characters

### ISSUE THREAD

**Issue by tnixeu** [electron/electron#30966]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

13.4.0

### Expected Behavior

I extracted electron and one of the parent folders contained a unicode character. I would expect electron to start regardless if there is a unicode character in the path to electron.

### Actual Behavior

Electron does not open and prints the following text to the command line:
```
Microsoft Windows [Version 10.0.19043.1165]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\electron⚛️>electron.exe

C:\electron⚛️>

Electron 14.0.0 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
(node:29828) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)
[29828:0914/164827.234:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=-1073741819
[29828:0914/164827.359:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=-1073741819
[29828:0914/164827.486:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=-1073741819
[29828:0914/164827.609:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=-1073741819
[29828:0914/164827.719:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=-1073741819
[29828:0914/164827.828:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=-1073741819


C:\electron⚛️>
```

**Comment by nikeedev** [comment]
> app.commandLine.appendSwitch('no-sandbox')
> app.commandLine.appendSwitch('disable-gpu')
> app.commandLine.appendSwitch('disable-software-rasterizer')
> app.commandLine.appendSwitch('disable-gpu-compositing')
> app.commandLine.appendSwitch('disable-gpu-rasterization')
> app.commandLine.appendSwitch('disable-gpu-sandbox')
> app.commandLine.appendSwitch('--no-sandbox')
> app.disableHardwareAcceleration();

did work on me but i got still this: 
![image](https://user-images.githubusercontent.com/69197950/137626101-064efea4-fb8a-44bd-9b1f-5dcd13e36061.png)


and after using rs(restart) is shows this:

```
Restarting App

✔ Launching Application

[11048:1017/134926.802:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
[10348:1017/134928.442:ERROR:cache_util_win.cc(20)] Unable to move the cache: Ingen tilgang. (0x5)
[10348:1017/134928.444:ERROR:cache_util.cc(144)] Unable to move cache folder C:\Users\myftr\AppData\Roaming\videorecorder\Cache to C:\Users\myftr\AppData\Roaming\videorecorder\old_Cache_000
[10348:1017/134928.446:ERROR:disk_cache.cc(184)] Unable to create cache 
```

**Comment by bgerm** [comment]
I have the same issue with Electron 15.2.0 on Windows 10 Pro.

About 30% of the time my BrowserView doesn't paint and a minute or so later I get the `Passthrough is not supported, GL is disabled, ANGLE is` error.

I've tried the `disable-gpu-sandbox` appendSwitch in addition to disabling all sandboxing, but I still get the error.

**Comment by NoahAndrews** [comment]
I see these exact logs, but without any unicode characters in the path.

**Comment by bavulapati** [comment]
I see the issue on latest 15 and 16 too

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

Thanks for your help with this issue!

**Comment by nornagon** [comment]
Actually, I was able to reproduce this. Crash dump attached.

```
Crash reason:  EXCEPTION_ACCESS_VIOLATION_EXEC
Crash address: 0x0
Process uptime: 0 seconds

Thread 0 (crashed)
 0  0x0
    rax = 0x0000000000000000   rdx = 0x0000000000003055
    rcx = 0x0000000000000000   rbx = 0x000030360011c590
    rsi = 0x000030360011c580   rdi = 0x0000000000000000
    rbp = 0x0000000000000000   rsp = 0x000000419adfe928
     r8 = 0x000000000000000d    r9 = 0x000000419adfe718
    r10 = 0x000000000000001e   r11 = 0x2200000080082000
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x000030360011c5b0   r15 = 0xaaaaaaaaaaaaaaaa
    rip = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  electron.exe!gl::RealEGLApi::eglQueryStringFn(void *,int) [gl_egl_api_implementation.cc : 85 + 0x15]
    rsp = 0x000000419adfe930   rip = 0x00007ff61582c7fa
    Found by: stack scanning
 2  KERNELBASE.dll!GetProcAddressForCaller + 0x6c
    rsp = 0x000000419adfe960   rip = 0x00007ffccdf853dc
    Found by: stack scanning
 3  electron.exe + 0x2f9ee6c
    rsp = 0x000000419adfe9b0   rip = 0x00007ff616eeee6c
    Found by: call frame info
 4  USER32.dll!int64_t CtfHookProcWorker(int,uint64_t,int64_t,uint64_t) + 0x40
    rsp = 0x000000419adfe9c0   rip = 0x000001e609986130
    Found by: stack scanning
 5  electron.exe!gl::DriverEGL::InitializeClientExtensionBindings() [gl_bindings_autogen_egl.cc : 116 + 0x16]
    rsp = 0x000000419adfe9d0   rip = 0x00007ff61580c506
    Found by: stack scanning

[...]
```

[0ba3c035-0da4-409c-8bbc-d361d906229c.zip](https://github.com/electron/electron/files/7892023/0ba3c035-0da4-409c-8bbc-d361d906229c.zip)

**Comment by nornagon** [comment]
Looks like an upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=1246942 (currently restricted).

**Comment by tidy-dev** [comment]
FWIW, we on GitHub Desktop, we ran in to this when upgrading to 16.0.8 and the unicode issue appears to resolve in 16.0.9. But, still experiencing problems for some windows users, maybe the issue reported in #32440

**Comment by tnixeu** [comment]
It seems that the bug is now resolved with the release of v18.0.0. 

The latest affected version seems to be v17.4.0.

Thank you for fixing it.

**Comment by keyiis** [comment]
@tnixeu I update to electron@18.2.0,It still appears.
`[19552:0510/143127.588:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is`

**Comment by newghost** [comment]
Still reproduced on: "electron": "^19.0.8"

My app only have a tray and without a BrowserWindow. When I start the app these errors appears, and the app crashed.

```
$ electron .

App is ready
[21520:0720/160032.817:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[0720/160033.835:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: No process is on the other end of the pipe. (0xE9)
[21520:0720/160033.875:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160033.937:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160034.008:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160034.070:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160034.112:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160034.159:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160034.212:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160034.251:ERROR:gpu_process_host.cc(974)] GPU process exited unexpectedly: exit_code=-1073741659
[21520:0720/160034.251:FATAL:gpu_data_manager_impl_private.cc(450)] GPU process isn't usable. Goodbye.
error Command failed with exit code 2147483651.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After add these commands:
```
app.commandLine.appendSwitch('no-sandbox')
app.commandLine.appendSwitch('disable-gpu')
app.commandLine.appendSwitch('disable-software-rasterizer')
app.commandLine.appendSwitch('disable-gpu-compositing')
app.commandLine.appendSwitch('disable-gpu-rasterization')
app.commandLine.appendSwitch('disable-gpu-sandbox')
app.commandLine.appendSwitch('--no-sandbox')
app.disableHardwareAcceleration()
```
Will show these errors but it will not crash.
```
$ electron .

App is ready
[0720/160843.271:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: No process is on the other end of the pipe. (0xE9)
[21876:0720/160843.331:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
[0720/160844.208:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: No process is on the other end of the pipe. (0xE9)
[0720/160845.069:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: No process is on the other end of the pipe. (0xE9)
[0720/161034.521:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: No process is on the other end of the pipe. (0xE9
```

**Comment by saostad** [comment]
I set `app.disableHardwareAcceleration();` and it fixed the problem.

**Comment by turbobuilt** [comment]
Yeah I'm having this issue in virtualbox

**Comment by Axorax** [comment]
Adding this line of code like @saostad seems to fix it for me as well.

```js
app.disableHardwareAcceleration();
```

**Comment by mistercheff** [comment]
> Por favor, tente as linhas abaixo para solition:
> 
> ```
> app.commandLine.appendSwitch('no-sandbox')
> app.commandLine.appendSwitch('disable-gpu')
> app.commandLine.appendSwitch('disable-software-rasterizer')
> app.commandLine.appendSwitch('disable-gpu-compositing')
> app.commandLine.appendSwitch('disable-gpu-rasterization')
> app.commandLine.appendSwitch('disable-gpu-sandbox')
> app.commandLine.appendSwitch('--no-sandbox')
> app.disableHardwareAcceleration();
> ```

This solution worked for me
