### ISSUE TITLE
[Bug]: showSaveDialogSync fails assertion

### ISSUE THREAD

**Issue by legraphista** [electron/electron#31152]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

20.10

### What arch are you using?

x64

### Last Known Working Electron version

13.4.0

### Expected Behavior

`dialog.showSaveDialogSync` opens a save dialog

### Actual Behavior

`dialog.showSaveDialogSync` is ignored and throws a console warning
```
[293296:0927/191734.375994:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
```

### Testcase Gist URL

https://gist.github.com/legraphista/7498e518f623da1c20fed241d55e538d

**Comment by rooklift** [comment]
From the report I had, I believe `showOpenDialogSync` is also affected. (Can't check myself, no easy access to Linux.)

**Comment by legraphista** [comment]
> From the report I had, I believe `showOpenDialogSync` is also affected. (Can't check myself, no easy access to Linux.)

Can confirm, `dialog.showOpenDialogSync(mainWindow);` does not work
```
[9896:0929/110120.256968:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
```

**Comment by nicarl** [comment]
We see the same issue in https://github.com/opossum-tool/OpossumUI for `showOpenDialogSync`, but only for running under Linux. macOS does not seem to have problems.

**Comment by mathieulj** [comment]
I just ran into this myself. I tracked the failure to bring up the file picker down to a change between https://github.com/electron/electron/compare/v14.0.0-nightly.20210401...v14.0.0-nightly.20210402 there is one commit in that range that seems like a likely culprit: https://github.com/electron/electron/commit/fa65faa4b0221dfd6e5d64abcff01321640a19ad. There might be more at play since that version didn't exhibit the assertion error in the console but I wonder if this might be the root cause.

**Comment by justkowal** [comment]
Any solutions for this issue?

**Comment by livthomas** [comment]
I can no longer reproduce this problem in either Electron 16.0.8 or 17.0.0.

It looks like it has already been fixed in all affected major versions (14+).  See issue #31997.

**Comment by deepak1556** [comment]
Fix has been landed in `14.2.3`, `15.3.4`, `16.0.5`. Merging to https://github.com/electron/electron/issues/31997

**Comment by logicguy1** [comment]
I encountered this error on ArchLinux electron v. 21.1.1

**Comment by AlejandroFNadal** [comment]
I still see this with electron 31 in Nextron, reported to that repository: https://github.com/saltyshiomix/nextron/issues/491
