### ISSUE TITLE
[Bug]: pageSize not work when silent print on windows 10

### ISSUE THREAD

**Issue by sunchanglong** [electron/electron#31705]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0-beta.6

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

pageSize  works when silent print.

### Actual Behavior

`webContents.print({silent:true, pageSize: 'A5'})`
pageSize not works when silent print. it always use printer default pageSize.

#29532
#29334 
#31489 

other print options has been fixed, except pageSize.

**Comment by pushkin-** [comment]
`header` also doesn't work. See comment [here](https://github.com/electron/electron/pull/31615#issuecomment-958166233)

**Comment by m4heshd** [comment]
Tested on both `15.x` and `16.x`. I cannot reproduce this. It works perfectly fine for me. I suggest providing a reproducible Gist.

**Comment by sunchanglong** [comment]
Test Gist: https://gist.github.com/399fde90c29877ce940f78ec6ce49ee7

My printer support both A4, A5 papers. 
<ul>
    <li>Print options pageSize: 'A5'</li>
    <li>System printer default pageSize 'A4'</li>
    <li>Expect print with A5 papers. Result in A4 print, don't honor electron print options pageSize.</li>
  </ul>

**Comment by sunchanglong** [comment]
I have test in chrome with a5 print using the same printer, it works.

**Comment by m4heshd** [comment]
@sunchanglong I tried your Gist with `Adobe PDF` and the output dimensions are correct. Can you try the same or with `Microsoft Print to PDF`? It would narrow the issue down to physical device interfaces.

**Comment by sunchanglong** [comment]
@m4heshd I tried to print with `Microsoft Print to PDF`  and the output dimensions are correct too.
When print to physical device, Notice the system print task queue, the print properties is not same with specified in code.

**Comment by m4heshd** [comment]
Ah. Then this definitely is an issue which needs to be addressed.

**Comment by m4heshd** [comment]
Just tested this and can confirm. These settings are being completely ignored when printed to non-emulated devices. @codebytere, @nornagon can we get some assistance on this? Printing is such a vital task for a majority of Electron apps. I truly hope this can be addressed soon because since #31489 I've written thousands of lines of code around this whole functionality without the knowledge of this being an issue.

**Comment by blaspix-tech** [comment]
Hello @codebytere , same issue on **Linux**.
Also custom page sizes like "62X1" for pos printers for example are not supported.

**Comment by m4heshd** [comment]
Any update on this issue? It's ~insanely difficult~ impossible to replace this functionality with third-party libraries.

**Comment by Hedwig188** [comment]
I can also reproduce this with any printer. also not able to workaround the issue currently.

**Comment by sunchanglong** [comment]
> Hedwig188
Did you test this on chrome browser?Chrome seems works right.

**Comment by Hedwig188** [comment]
> > Hedwig188
> 
> Did you test this on chrome browser?Chrome seems works right.

Yes, I've also confirmed paper size is correctly being respected in Chrome when printing to those affected printers.

**Comment by Hedwig188** [comment]
`Kyocera FS-CS3500DN KX` driver is also broken.

**Comment by sunchanglong** [comment]
hello @codebytere, is there any timeline on this issue? thanks.

**Comment by sunchanglong** [comment]
#22066
#22014
#33190
#29532
All above are printing pageSize bugs.
pageSize bug makes printing in electron nearly not work.
@codebytere hopes this would be solved.

**Comment by TheJamesMachine** [comment]
Are you having a problem with only the pageSize? 

I'm seeing all options are ignored when silent is true, including the printer. There have been a lot of other bugs reported about various print options being ignored that have been marked as fixed. I'm still seeing it being ignored in 20.0 and 11.5

**Comment by Hedwig188** [comment]
Is there a plan to fix this issue?

**Comment by andredealmei** [comment]
Is there a plan to fix this issue?

**Comment by moom-en** [comment]
It's not work in electron 22.0.0（windows 10）

**Comment by m4heshd** [comment]
@codebytere, @ckerr, @nornagon can one of you please look into this issue? I don't get why this is being ignored for such a long period of time. This issue was there since forever and it's undeniably a most needed feature for desktop applications.

**Comment by Xavier9896** [comment]
Is there a plan to fix this issue?

**Comment by mingyangzhu** [comment]
Is there a plan to fix this issue?

**Comment by jhetuts** [comment]
Bump

**Comment by 490465044** [comment]
![image](https://github.com/electron/electron/assets/7018123/e6c4314b-c53b-42da-94fb-6037a67fd7e9)
![image](https://github.com/electron/electron/assets/7018123/842c044e-94da-4137-9fba-946727453426)
![image](https://github.com/electron/electron/assets/7018123/b47fbc58-7570-479e-92f9-620b4393ad09)
I have specified the paper size using parameters.
But the parameter does not take effect on the printing device.
I've noticed that this problem has persisted for a very long time. The print function is a common function. There are so many places where this functionality is needed, so it's very important to us.
Hope to fix it soon

**Comment by 490465044** [comment]
It is unbelievable that a problem lasted so long. Neither was fixed.

**Comment by m4heshd** [comment]
@codebytere, Yes, you're gonna get pinged constantly because you're assigned to this issue. So pinging you again, can we get this fixed because it works completely fine on Chromium. This is not a small issue. Electron apps are made for desktop and a lot of those desktop tasks require printing. How this issue gets ignored is beyond my imagination.

**Comment by 1339240789** [comment]
It's still a problem on some printers. Can't silent print perform the same set of paper sizes as non-silent print?

**Comment by qingyanbaby** [comment]
Is there a plan to fix this issue? @codebytere

**Comment by ShaunaGordon** [comment]
electron@24.7.1 respects custom pageSize, but then v25 presents with the bug described in #39179

**Comment by WillPoulson** [comment]
Also experiencing the same issue with 25, 24 working perfect

**Comment by m4heshd** [comment]
Opening a new issue is the only way to get help for this. This issue is tagged with ancient, unsupported versions of Electron. So devs won't pay any attention to these. Try the latest stable releases, create a repro gist if the issue persists, and open a new issue. Silent printing works perfectly fine on Chromium BTW. Worth mentioning that.

**Comment by moom-en** [comment]
This issue has been left over for many years, and if it is consistently marked as Does Not Block Stable, then this issue will never be resolved @codebytere @dsanders11

**Comment by 1339240789** [comment]
bump

**Comment by ShaunaGordon** [comment]
> Opening a new issue is the only way to get help for this. This issue is tagged with ancient, unsupported versions of Electron. So devs won't pay any attention to these. Try the latest stable releases, create a repro gist if the issue persists, and open a new issue. Silent printing works perfectly fine on Chromium BTW. Worth mentioning that.

@m4heshd [Codebytere has specifically said *not* to open duplicates of this.](https://github.com/electron/electron/issues/39702#issuecomment-1706261390) Our only option is to continue to post here to keep it open.

**Comment by m4heshd** [comment]
@ShaunaGordon You can clearly see that all that happened and the tags were updated AFTER my comment you quoted. Yet this issue from 2021 is still open and is reproducible after more than 10 major releases later. 🤷🏻‍♂️

**Comment by ShaunaGordon** [comment]
I'm aware, hence the "fyi" part.

**Comment by samknp** [comment]
bump

**Comment by lwestfall** [comment]
bump

**Comment by cah-eric-waight01** [comment]
Bump

**Comment by daa68** [comment]
bump

**Comment by codebytere** [comment]
I just ran https://gist.github.com/7c307aeb031e823ed8273ae44e861d45 on 31 and this appears to be working as expected for me with a non-emulated printer. I ran it with `a5` and then `a6` twice and see the previews reflect my expectations:

<img width="481" alt="Screenshot 2024-08-15 at 4 51 34 PM" src="https://github.com/user-attachments/assets/68e1b6d4-caef-4616-958b-bdb6ea45692e">

**Comment by davbrito** [comment]
bump

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
