### ISSUE TITLE
[Bug]: Vibrant windows are missing their border on macOS

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#32002]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

macOS

### Operating System Version

Monterrey

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Vibrant windows on macOS have an inset light coloured border:

<img width="1083" alt="Screen Shot 2021-11-25 at 5 33 16 PM" src="https://user-images.githubusercontent.com/7342119/143505085-612a2cf7-e3ed-4112-8db2-5ccea936c72a.png">

### Actual Behavior

A vibrant Electron window does not have this border:

<img width="882" alt="Screen Shot 2021-11-25 at 5 33 37 PM" src="https://user-images.githubusercontent.com/7342119/143505115-3534082b-341e-45ac-8268-57adbd24dd63.png">

The window config is:

```ts
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    vibrancy: "sidebar",
    transparent: true,
    titleBarStyle: "hidden",
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })
```

### Additional Information

It is possible to get the correct look by using a native module to set an opaque background on the NSWindow, and applying vibrancy on top of it:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/7342119/143505362-d4e9f2ce-d8ad-4f40-a1c5-1928d6a10747.png">

The Swift code is:

```swift
windowView.window?.backgroundColor = NSColor.white

let frame = CGRect(x: 0, y: 0, width: windowView.frame.width, height: windowView.frame.height)
let view = VibrantSidebarView(frame: frame)
view.blendingMode = NSVisualEffectView.BlendingMode.behindWindow
view.material = NSVisualEffectView.Material.sidebar
view.wantsLayer = true
view.autoresizingMask = [.width, .height]

windowView.addSubview(view, positioned: NSWindow.OrderingMode.below, relativeTo: nil)
```

But I think this is something Electron should be able to do without a native module.

**Comment by mitchchn** [comment]
Never  mind -- it looks like this has indeed been fixed in the latest 16.x releases. Thanks all!

**Comment by eldh** [comment]
I'm still seeing this bug in 17.1.2 — is there something special that's needed to get this working correctly?
