### ISSUE TITLE
[Bug]: Draggable regions don't update when CSS changes

### ISSUE THREAD

**Issue by neobyteUK** [electron/electron#32341]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Professional

### What arch are you using?

x64

### Expected Behavior

When the DOM is changed very early after launch, electron should repaint/initialise appropriately.

### Actual Behavior

Electron does not update the page correctly when the DOM changes early. See attached gist.

### Testcase Gist URL

https://gist.github.com/neobyteUK/fb856a8e24c0f30b694e5c8501f0566a

### Additional Information

This does not appear to be specific to -webkit-app-region changes - this was just a simple way for me to reproduce the issue for a bug report.

This first manifested (for me) when using React's Suspense feature, which provides a temporary DOM element to display while lazy-loading a module. I found that occasionally the temporary DOM element would be replaced "correctly" (mouseover cursor changes showed it could "see" elements) but visually on the screen I was still looking at the temporary DOM element that had been "removed".

Opening devtools immediately caused the visual representation to update to what it should be displaying (i.e. I could no longer see the temporary element).

So this appears to be more of a repaint/initialisation issue that happens when the DOM changes very early on window launch.

**Comment by neobyteUK** [comment]
As additional information, I have also seen this manifest with BrowserViews (not just BrowserWindows) - changing their content early not being honoured.

**Comment by neobyteUK** [comment]
Further info: resizing the window manually after launch causes the app-region in the test case to start being honoured.

**Comment by neobyteUK** [comment]
Possibly related issues: #32534 #29859 #31109.

**Comment by nornagon** [comment]
I can repro on 16.0.6 but not 16.0.7, so it looks like this has been fixed.

**Comment by neobyteUK** [comment]
I have just confirmed it DOES still happen on 16.0.7 with Electron Fiddle. Please reopen.

**Comment by nornagon** [comment]
I can't produce the same behavior:

https://user-images.githubusercontent.com/172800/151063799-09d7ec5e-206f-4f5f-8ab2-738ff89a17d3.mov


Perhaps there's something else happening here?

**Comment by neobyteUK** [comment]
Are thats on Windows 10? If so yes something weird happening here. I will try and upload a video too.

**Comment by neobyteUK** [comment]
![32341-a](https://user-images.githubusercontent.com/6770417/151066018-dff8f9d9-603a-45af-83c3-b1b3a0bdcf5f.gif)

**Comment by nornagon** [comment]
Okay, I'm _sometimes_ able to reproduce this on 16.0.7. It doesn't happen consistently for me, though. I'll reopen.

**Comment by nornagon** [comment]
Adding the class in a timeout makes it much more reliably reproducible:

```
setTimeout(() => { document.getElementById('root').classList.add('draggable') }, 1000)
```

Updated gist: https://gist.github.com/c22c2b2f891203d3c4a15d0c48c7bcc6

**Comment by nornagon** [comment]
This reproduces on macOS too.

**Comment by nornagon** [comment]
Hm, also, this reproduces as far back as Electron 4.x, so I wonder if this is a technical limitation.

**Comment by nornagon** [comment]
This patch to Blink seems to resolve the issue:

```patch
diff --git a/third_party/blink/renderer/core/frame/local_frame_view.cc b/third_party/blink/renderer/core/frame/local_frame_view.cc
index 0fe738fae9377..07851b8c3d136 100644
--- a/third_party/blink/renderer/core/frame/local_frame_view.cc
+++ b/third_party/blink/renderer/core/frame/local_frame_view.cc
@@ -1852,8 +1852,6 @@ void LocalFrameView::PerformPostLayoutTasks(bool visual_viewport_size_changed) {
     }
   }

-  UpdateDocumentAnnotatedRegions();
-
   GetLayoutView()->EnclosingLayer()->UpdateLayerPositionsAfterLayout();
   frame_->Selection().DidLayout();

@@ -3233,6 +3231,7 @@ void LocalFrameView::UpdateStyleAndLayout() {
     PerformPostLayoutTasks(visual_viewport_size_changed);
     GetFrame().GetDocument()->LayoutUpdated();
   }
+  UpdateDocumentAnnotatedRegions();
   UpdateGeometriesIfNeeded();
 }
```

i.e., we update the annotated regions unconditionally whenever `UpdateStyleAndLayout` is called, instead of only when a layout actually occurred.

So this is a bug in Blink: draggable regions are not being updated in this case because no layout is happening, even though the draggable regions _have_ changed.

You can work around this in your app by forcing a relayout when you change draggable regions without otherwise causing a layout. Here's an example: https://gist.github.com/cb1442125da2cb139ee04a94980303eb

Unfortunately I'm not sure the future is bright for this one. It was reported upstream in 2018: https://bugs.chromium.org/p/chromium/issues/detail?id=803361 and closed as WontFix because
> webkit-app-region is a non-standard feature that we'd like to remove.
> 
> Realistically we do not have the resources to address this anytime soon, closing as WontFix.

On the other hand, since then, there's a new standard which references this property: https://github.com/WICG/window-controls-overlay/blob/main/explainer.md#defining-draggable-regions-in-web-content

So maybe they'd be interested in the fix? I'll try submitting that fix upstream and see what response I get.

**Comment by nornagon** [comment]
Uploaded here: https://chromium-review.googlesource.com/c/chromium/src/+/3416279

**Comment by nornagon** [comment]
The upstream CL was merged. I'll backport to 17.x.

**Comment by nornagon** [comment]
This was reverted in Chrome, so reopening.

**Comment by nornagon** [comment]
@Slapbox you should be able to work around it in your app by forcing a relayout after applying the relevant styles.

**Comment by Slapbox** [comment]
@nornagon thanks for your tip. Do you mean just invoking [one of these methods](https://gist.github.com/paulirish/5d52fb081b3570c81e3a) should work around the issue for us?

I tried a bunch of removing/re-applying CSS tricks - but I didn't think to try forcing a relayout.

**Comment by nornagon** [comment]
yep, should do! see https://gist.github.com/cb1442125da2cb139ee04a94980303eb for an example (linked above, too)

**Comment by Slapbox** [comment]
@nornagon thanks again for the tip! I finally got a chance to test this but it's not working as smoothly as I'd hoped.

In our app we need to delay execution of that code for nearly 3 seconds, which means the very first thing that users will encounter when installing our app is a bug, which is not a good first impression. If we shorten the `setTimeout` anymore, then the workaround fails to change/fix anything.

Additionally, simply calling one of those methods was not enough - we had to modify an element style as you do in your:

```js
    root.style.width = '0';
    root.getBoundingClientRect();
    root.style.width = '';
  ```
  
Is there anything we can do to further reduce, or ideally eliminate, this substantial delay?

**Comment by Slapbox** [comment]
Or is there anything else that can be done from the Electron team's side?

**Comment by nornagon** [comment]
@Slapbox no idea why a delay would be needed, you should be able to trigger the workaround as soon as your layout is in place.

**Comment by Slapbox** [comment]
Could it have to do with animating a previously draggable region? That's my only idea. We use a drag region logo screen on startup and then remove the draggability and fade it out - but perhaps drag removal has some bug when a previously draggable element is animated?

@nornagon the example you shared did use a short `setTimeout` - are you sure a delay isn't necessary more generally speaking? We don't run the code until the application is showing the login screen, but still we need the arbitrary timeout of about 2800ms.
