### ISSUE TITLE
[Feature Request]: File.path equivalent for the File System Access API

### ISSUE THREAD

**Issue by cirras** [electron/electron#33647]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In an Electron environment, the `File` interface is extended with a `path` attribute containing the real filesystem path.

At the moment, there is no equivalent for file or directory handles returned by the File System Access API.
Furthermore, a `File` returned by [FileSystemFileHandle.getFile](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/getFile) has an empty `path`.

### Proposed Solution

- Add a `path` attribute to the `FileSystemHandle` interface containing the real filesystem path
- Ensure the `path` attribute is populated on the `File` returned by [FileSystemFileHandle.getFile](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/getFile)

### Alternatives Considered

Using the node `fs` module in an Electron environment is a completely viable approach.
The downside is increased complexity for applications that share code between web and electron.

### Additional Information

See:
- https://github.com/electron/electron/blob/v1.2.8/docs/api/file-object.md
- https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle
- https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle
- https://github.com/electron/electron/issues/28422#issuecomment-962484932

**Comment by el3um4s** [comment]
Hello

Is there any news regarding this feature?

**Comment by Matrixbirds** [comment]
I tried to apply this [patch](https://github.com/electron/electron/blob/main/patches/chromium/blink_file_path.patch) with offical latest version of CEF , and test on my demo. can reproduce with `window.showOpenFilePicker`. Maybe it is caused by chromium?

**Comment by jtbandes** [comment]
> Furthermore, a `File` returned by [FileSystemFileHandle.getFile](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/getFile) has an empty `path`.

We ran into this as well in [foxglove/studio](https://github.com/foxglove/studio) after switching from File to FileSystem*Handle APIs for some of our file interactions.

@zcbenz it looks like you were the original author of `blink_file_path.patch` which adds the `File.path` property. Would you happen to know how difficult this might be to add to FileSystemFileHandle as well?

**Comment by johot** [comment]
I also really need this one. I implemented all my file logic using the file system api (for me I also got better performance than doing file operations over ipc + fs module) but now I am stuck because there is no way to find the real path of a file or folder created/read using the file system api :(

**Comment by nikwen** [comment]
Electron has now adopted `webUtils.getPathForFile()` as a replacement for `File.path`. However, it still cannot resolve the file of a `FileSystemFileHandle` in Electron v35.

Fiddle gist: https://gist.github.com/nikwen/16895ce0118595dd2f86ef3f802725dc

**Comment by nikwen** [comment]
**Investigating the code**

The [`FileSystemFileHandle::getFile` function](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/file_system_access/file_system_file_handle.cc;l=122-123;drc=75c5e5c6fb11f2e9785b93c142f73996d9169d2d;bpv=0;bpt=1) uses a `File` constructor which doesn't include the file path and [sets it to an empty string](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/fileapi/file.h;l=85-93;drc=75c5e5c6fb11f2e9785b93c142f73996d9169d2d). I assume that's why `webUtils.getPathForFile()` returns an empty string.

The challenge is that the renderer doesn't know the path of a [`FileSystemHandle`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/file_system_access/file_system_handle.h;drc=75c5e5c6fb11f2e9785b93c142f73996d9169d2d). It only [has access to](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/file_system_access/file_system_handle.h;l=82-83;drc=75c5e5c6fb11f2e9785b93c142f73996d9169d2d;bpv=1;bpt=1) a `FileSystemAccessTransferToken`. This token can be resolved in the browser process using [`ResolveTransferToken`](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/file_system_access/file_system_access_manager_impl.h;l=175-179;drc=75c5e5c6fb11f2e9785b93c142f73996d9169d2d;bpv=1;bpt=1?q=ResolveTransferToken&ss=chromium%2Fchromium%2Fsrc).

One approach could be to create a `webUtils.getPathForFileHandle(fileHandle: FileSystemHandle)` function (available in the preload script only, similar to [`webUtils.getPathForFile`](https://www.electronjs.org/docs/latest/api/web-utils#webutilsgetpathforfilefile)) which obtains the `FileSystemHandle`'s `FileSystemAccessTransferToken` and uses IPC to have the browser process resolve the transfer token using `ResolveTransferToken`.

For this to work, it would be necessary to make `FileSystemFileHandle` and `FileSystemDirectoryHandle` serializable over IPC.

Some security considerations can be found in #35604. (Given that we have a similar function for `File` objects, I believe this approach should probably be fine.)

**Comment by nikwen** [comment]
Wanted to provide an update here with feedback I got. The credits for the research go to @codebytere!

The proposal from my previous comment won't work for security reasons. The reason `File.path` can be exposed to the renderer is that, technically speaking, the renderer already has access to it. If compromised, it could retrieve the path from memory. However, a `FileSystemFileHandle` has no inherent concept of its own path — exposing any mechanism for the renderer to obtain that path would weaken the web’s security model.

It might be possible to have a browser-process-only API that receives a `TransferToken` from the renderer and returns the path to the browser process without sending it back to the renderer. That said, there is still risk to that. If we implement that, we'll need strong documentation making it clear that the API should never be exposed to the renderer.

**Comment by codebytere** [comment]
Closing out in light of the above - thanks for the great summary @nikwen 🙇‍♀️
