### ISSUE TITLE
[Bug]: Console.assert errors

### ISSUE THREAD

**Issue by robertpatrick** [electron/electron#35399]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

macOS

### Operating System Version

12.5

### What arch are you using?

x64

### Last Known Working Electron version

17.4.4

### Expected Behavior

Electron-based applications run without errors.

### Actual Behavior

With 20.0.3, I see lots of these errors as I run my application.  This didn't occur with 17.x...

[62415:0822/074915.763764:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[62415:0822/074915.763805:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[62415:0822/074915.763826:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[62415:0822/074915.763844:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[62415:0822/074915.763862:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[62415:0822/074915.763880:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[62415:0822/074915.763897:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[62415:0822/074915.763914:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by robertpatrick** [comment]
@codebytere I have no idea why this is happening but our code has not changed so clearly, this issue is cause by some sort of change in recent versions of Electron.  Our code can be found at https://github.com/oracle/weblogic-toolkit-ui.  

I have tried to reproduce in a basic Electron Fiddle but it does not happen--even with opening the dev tools window.  I will keep searching but I am not sure what you expect.  I guess we can downgrade to 17.x to eliminate this problem until you fix the issue...

**Comment by codebytere** [comment]
Looks like https://github.com/electron/electron/pull/33093 introduced it

**Comment by MarshallOfSound** [comment]
I'd not that these errors are harmless

**Comment by robertpatrick** [comment]
@MarshallOfSound But they are polluting the logs, making it difficult to see other entries that might be important.  This really needs to be addressed.

**Comment by robertpatrick** [comment]
Still happening in 21 Beta 5.

My reproducer is at https://github.com/oracle/weblogic-toolkit-ui.

Steps to reproduce:

1. Clone the repo at https://github.com/oracle/weblogic-toolkit-ui..
2. `cd weblogic-toolkit-ui/webui`
3. `npm i`
4. `npm start`
5. Open a new window in `weblogic-toolkit-ui` directory.
6. `cd electron`
7. `npm i`
8. `npm start`
9. Observe the following output in the terminal window of the electron directory during startup:

```
[44774:0912/193300.314004:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.314062:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.314095:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.314125:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.314145:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.314163:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.372606:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.372680:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.372721:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.372755:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.372785:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.372841:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[44774:0912/193300.372866:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
```

**Comment by robertpatrick** [comment]
@codebytere Reproducer provided so this should no longer be blocked.

**Comment by ckerr** [comment]
@robertpatrick, I understand isolating a bug down from the full app can be frustrating, but the repro testcase request was:

> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
>
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue?
 
There are something like 380,000 lines of JS code in weblogic-toolkit-ui, so I'd vote for leaving `blocked/needs-repro` until there is a more practical standalone testcase. :slightly_smiling_face:

**Comment by robertpatrick** [comment]
@ckerr I have tried and failed to create a smaller test case.  Like you, our team is very small and juggling multiple projects.  With that said, I fee certain that our code has nothing to do with this bug since it works fine in 17.x and fails with 18.x+ with zero code change.

**Comment by ckerr** [comment]
@robertpatrick, I get where you're coming from. Would it be possible for you to try bisecting your app with https://github.com/electron/fiddle-core from Electron 17 to Electron 18 to see if you can find where the regression occurred? Bonus points if you include nightlies / alphas / betas to narrow down the range of Electron commits where this might have taken place.

**Comment by rpatrick00** [comment]
@ckerr i thought Shelley already did that above?  https://github.com/electron/electron/issues/35399#issuecomment-1222487291

**Comment by artus9033** [comment]
I am experiencing the issue as well in v19.0.16

**Comment by ckerr** [comment]
@rpatrick00 ah, I missed that! Thank you for the link :+1:

**Comment by ckerr** [comment]
> @ckerr i thought Shelley already did that above? [#35399 (comment)](https://github.com/electron/electron/issues/35399#issuecomment-1222487291)

@rpatrick00 ah, I missed that! Thank you for the link +1

**Comment by vanowm** [comment]
Please remove macos tag, it's not system related. This has been happening on Windows since `v18.0.0-beta.1`

Last version that didn't have this issue was `18.0.0-alpha.5`

**Comment by chuyaguo2014** [comment]
This is happening to me as well. I'm on macOS Ventura 13.0 (22A380) and am using electron v19.0.5.

**Comment by zaynekomichi** [comment]
Definitely, a bug involved was facing the same issue, had to do with looping using the map function. The key/index is required on each item you return. Not sure if it applies to everyone but mainly looping objects. Hope that helps. And I'm sure you can check when the error pops up in the console that's the only way to see which code is causing this.

**Comment by mnumanuyar** [comment]
please add windows platform to labels

**Comment by sotrh** [comment]
I'm seeing this on Linux (Pop OS 22.04 LTS) on Electron version `21.0.1`

**Comment by oxedom** [comment]
Having the same issue with my nextJS webapp, not sure what is causing it.

**Comment by Hybueno09** [comment]
Any updates?

**Comment by zaynekomichi** [comment]
caused by map function make sure to include index 
`data.map((item,index)=>{
 console.log("display data")
})`

**Comment by robertpatrick** [comment]
I am no longer seeing this error so I suspect that it was something in the code that was triggering this (that has since been changed).

**Comment by m-atanasova** [comment]
For anyone still struggling with this, here is my solution:  open the DevTools of the DevTools of your electron application.  Check the filter levels of the Console tab, most probably they are set to "All levels" and Verbose mode is causing the issue.  Set it to "Default levels", restart the app and the console.asser error should be gone.

**Comment by robertpatrick** [comment]
@m-atanasova is correct, it is the Verbose logging level that is causing this.

**Comment by xmedeko** [comment]
Is there any way how to fix it in the release build automatically (so as users of an app do not need to open DevTools and change level manually)?

**Comment by yosle** [comment]
In my case after some time I figured out it was the devContentSecurityPolicy , because I'm using electron forge + webpack + typescript. I edited the forge.config.ts , 
```
(...)
      devContentSecurityPolicy: "connect-src 'self' 'unsafe-eval' 'unsafe-inline' * 'http://localhost:* ws://localhost:*",
(...)
```

This still shows 1 warning on development and of course you probably want to setup this according to your app. 
And that was it. No more annoying assert logs when dev tools are open.

More information in https://www.electronjs.org/docs/latest/tutorial/security

**Comment by michaeljelly** [comment]
> For anyone still struggling with this, here is my solution: open the DevTools of the DevTools of your electron application. Check the filter levels of the Console tab, most probably they are set to "All levels" and Verbose mode is causing the issue. Set it to "Default levels", restart the app and the console.asser error should be gone.

I haven't managed to open the DevTools of the DevTools, I've tried `win.devToolsWebContents.openDevTools()` and pressing Cmd-Option-J and Command-Shift-J.

Any tips? It's not very well documented online how to do it.

**Comment by m-atanasova** [comment]
@michaeljelly Here is what I do: below the code where you set up your main window (in my case called mainWindow), I place the following code:
  const devtools = new BrowserWindow()
  mainWindow.webContents.setDevToolsWebContents(devtools.webContents)
  mainWindow.webContents.openDevTools({ mode: 'detach' })

Then upon startup the DevTools will start in detached mode (a separate window) on which you can open DevTools with the key combination or use the View --> Toggle Developer Tools menu

**Comment by kaliiiiiiiiii** [comment]
Had exactly that issue some time ago with python. Maybe the following helps you..

 > Has anyone of y'all ever encountered chrome crashing (UI hanging to be percise) with some `javascript` when having a automation library connected?
> Only seems to apply when
> -  the chrome-devtools console is open
> - `--user-data-dir` and `--remote-debugging-port` are specified
> 
> 
> To reproduce:
> ```python
> import subprocess
> import sys
> import time
> import shutil
> 
> from cdp_socket.utils.utils import random_port, find_chrome_executable
> import tempfile
> 
> with tempfile.TemporaryDirectory() as _dir:
>     PORT = random_port()
>     args = [
>         f"--remote-debugging-port={PORT}",
>         f"--user-data-dir={_dir}",
>         "about:blank"
>     ]
>     proc = subprocess.Popen(
>         [find_chrome_executable(), *args],
>         stdin=subprocess.PIPE,
>         stdout=subprocess.PIPE,
>         stderr=sys.stderr # or =None,  fine
>         # stderr=subprocess.PIPE  # makes chrome hang
>     )
>     time.sleep(5)
>     input("execute script now, press ENTER to quit:\n")
> 
>     # cleanup
>     proc.terminate()
>     proc.wait()
 >    time.sleep(2)
>     shutil.rmtree(_dir, ignore_errors=True)
> ```
> just execute the following script in the console:
> ```js
> const gl = document.createElement("canvas").getContext("webgl")
> 
> const params = Array(100).fill(undefined);
> 
> setTimeout(() => {
>     params.forEach((param) => {
>         gl.getParameter(param)
>     })
> }, 1000)
> ```
> 
> ### conclusions
> - seems like the issue is that `subprocess.PIPE` can't hande that many errors (
> ```
> [24088:12012:1007/021520.274:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/devtools-frontend/front_end/panels/console/console.js (6)
> ```
> - there might be other JavaScript API's which write a error to `stderr` without requiring the console to be open => > possibly a detection method

**Comment by samjowen** [comment]
Bump, not stale.

**Comment by WSINTRA** [comment]
Bump, happening when using Cypress in Electron for E2E tests

**Comment by iamisti** [comment]
This is still happening

**Comment by czh6865801** [comment]
this bug is fixed  [https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4835692](url)
it`s from ChromeDevTools not electron bug [https://github.com/ChromeDevTools/devtools-frontend](url)

you can click Debugging attempt and toggle Developer Toolsto  reproduce the issue. 
<img width="489" alt="IMG20240320-200554152" src="https://github.com/electron/electron/assets/52740690/37082e9c-a28b-4c36-b19c-daa246dc9671">

so. we need to up or down electron version to change chromium version

**Comment by sosioo** [comment]
Still happening, I am Linux.
It seems this will never be fixed.. Is there way to filter this error from the terminal? It really makes debugging painful.

**Comment by LucaConfa** [comment]
bump

**Comment by ExInferi** [comment]
bump

**Comment by iamisti** [comment]
bump

**Comment by EmptyBox-Design** [comment]
bump

**Comment by vanowm** [comment]
fking bots...these are the cancer of repositories now...

**Comment by iamisti** [comment]
bump

**Comment by LucaConfa** [comment]
bump

**Comment by wangsen2020** [comment]
这个错误的原因可能是本地的node.js版本与electron内置的node.js版本不一致导致的

**Comment by ExInferi** [comment]
Still an issue

**Comment by kblok** [comment]
bump

**Comment by ExInferi** [comment]
bump 🚀
