### ISSUE TITLE
[Bug]: Failed to load React Devtools

### ISSUE THREAD

**Issue by sprout2000** [electron/electron#36545]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I want to load [React Devtools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) whose manifest version is v3.

```js
app.whenReady().then(async () => {
  new BrowserWindow().loadFile("index.html");

  const devtoolPath = path.join(
    os.homedir(),
    "/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.27.0_0"
  );
  await session.defaultSession.loadExtension(devtoolPath, {
    allowFileAccess: true,
  });
});
```

<img width="638" alt="2022-12-03-152048" src="https://user-images.githubusercontent.com/52094761/205427820-d513a6a0-2c8e-4234-81da-0630d280530e.png">

### Actual Behavior

Received an error message **"Permission 'scripting' is unknown or URL pattern is malformed"**:

```sh
(node:44297) ExtensionLoadWarning: Warnings loading extension at $HOME/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.27.0_0:
  Permission 'scripting' is unknown or URL pattern is malformed.
```

### Stack Trace

```sh
[44297:1203/150155.162121:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    ManifestError
[44297:1203/150155.162205:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    RuntimeError
  Context: chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Stack Trace: 
    {
      Line:     107
      Column:   1
      URL:      chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
      Function: (anonymous function)
    }
```

### Additional Information

The problem has not occurred with [Vue3 devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg), whose manifest version is v2.

<img width="714" alt="2022-12-03-152723" src="https://user-images.githubusercontent.com/52094761/205428009-e7ce63c9-e039-4486-b1fd-fd718eba5522.png">

**Comment by Kilian** [comment]
Ran into this too. 4.27 switched over to manifest v3 which could be the cause, but according to https://github.com/facebook/react/pull/25145 they also now use `chrome.scripting.registerContentScripts` which is an API electron might not support yet.

**Comment by Kilian** [comment]
I wrote up some quick downgrade instructions for Electron apps (replace "Polypane" with your app name): https://polypane.app/docs/downgrading-react-devtools/

**Comment by codebytere** [comment]
Closing as an upstream bug: https://github.com/facebook/react/issues/25843

**Comment by mondaychen** [comment]
@codebytere Can you please reopen this? I believe Electron should add `chrome.scripting` APIs (as well as other Manifest V3 support) to fix this issue. 
Here's my argument https://github.com/facebook/react/issues/25843#issuecomment-1406766561

**Comment by spamshaker** [comment]
how to disable this warning?

**Comment by nostazac** [comment]
Errror  is in this line 
$HOME/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.27.0_0.

The warning specifically mentions that the permission "scripting" is unknown or the URL pattern is malformed. This could indicate that the extension is using a deprecated or outdated permission, or that the URL patterns specified in the extension manifest are incorrect.

To address this issue, you could try disabling or removing the extension causing the warning and see if the problem persists. Alternatively, you could contact the developer of the extension for further assistance in resolving the issue.

**Comment by sprout2000** [comment]
Still same with Electron v24.x.

```sh
[26821:0415/145134.612606:ERROR:extensions_browser_client.cc(67)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    RuntimeError
  Context: chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Stack Trace: 
    {
      Line:     107
      Column:   1
      URL:      chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
      Function: (anonymous function)
    }
[26821:0415/145134.612901:ERROR:extensions_browser_client.cc(67)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    ManifestError
[26821:0415/145134.981682:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
[26821:0415/145135.087366:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[26821:0415/145135.087392:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
```

**Comment by guozhengzhongGit** [comment]
yeah
<img width="558" alt="image" src="https://user-images.githubusercontent.com/26349728/232654282-89645141-eeed-4b23-881f-e55caef6562b.png">
the latest version electron also have same error

**Comment by Vn-ChemGio** [comment]
I have same issue with electron 24.x

**Comment by kkshinkai** [comment]
I also encountered this issue in Electron 24.x.

Does this mean that React developers on Electron have been unable to use development tools for half a year?

**Comment by Bartel-C8** [comment]
Yes, to use React Devtools, you should downgrade its version.

**Comment by RazvanCretu** [comment]
> Yes, to use React Devtools, you should downgrade its version.

how?

**Comment by kkshinkai** [comment]
> > Yes, to use React Devtools, you should downgrade its version.
> 
> how?

Here's a script that might help: https://github.com/facebook/react/issues/25843#issuecomment-1368733054

Replace `/path/to/your/data/extensions` with either `%AppData%/<YourApp>/extensions` (for Windows) or `~/Library/Application Support/<YourApp>/extensions` (for macOS).

Alternatively, if you prefer not to run the script, you can manually download https://polypane.app/fmkadmapgofadopljbjfkapdkoienihi.zip and replace the `fmkadmapgofadopljbjfkapdkoienihi` folder.

**Comment by Slapbox** [comment]
> Does this mean that React developers on Electron have been unable to use development tools for half a year?

A lot longer than that in production builds if you're following good security practices; which are where it's recommended to use tools like React's Profiling. I haven't had access to profiling in _YEARS_ and can't even imagine how much low-hanging fruit I have overlooked as a result.

**Comment by EvgeneOskin** [comment]
> A lot longer than that in production builds if you're following good security practices; which are where it's recommended to use tools like React's Profiling. I haven't had access to profiling in _YEARS_ and can't even imagine how much low-hanging fruit I have overlooked as a result.

Because I experience the same issue and more others with electrons and have a plan to abandon Electron in favor of Tauri, your reply triggered me to check out does Tauri has it. I found out that Tauri does not have it, and [a workaround to use standalone React DevTool](https://stackoverflow.com/a/74330841/4183400). I checked it out quickly, and it works without issues with the Electron.

**Comment by Slapbox** [comment]
@EvgeneOskin thanks for your investigation! I wonder if you're using a custom protocol in your production app like `app://` instead of `https://` or `file://`

To date, I haven't found any workaround that works with the `app://` protocol but I'd be super interested to hear if you had!

**Comment by EvgeneOskin** [comment]
The production app is running on `file://`.

**Comment by stuartambient** [comment]
> > > Yes, to use React Devtools, you should downgrade its version.
> > 
> > 
> > how?
> 
> Here's a script that might help: [facebook/react#25843 (comment)](https://github.com/facebook/react/issues/25843#issuecomment-1368733054)
> 
> Replace `/path/to/your/data/extensions` with either `%AppData%/<YourApp>/extensions` (for Windows) or `~/Library/Application Support/<YourApp>/extensions` (for macOS).
> 
> Alternatively, if you prefer not to run the script, you can manually download https://polypane.app/fmkadmapgofadopljbjfkapdkoienihi.zip and replace the `fmkadmapgofadopljbjfkapdkoienihi` folder.

Problem with this one, for me at least is if I open Chrome browser it updates the devtools.  Afaik, you'd have to shut off Chrome updates to keep this 'fix' working.

**Comment by kkshinkai** [comment]
> Afaik, you'd have to shut off Chrome updates to keep this 'fix' working.

I don't use Chrome extensions, so I can't say for sure. But I reckon it's pretty unlikely that Chrome would even know about the existence of the `~/Library/Application Support/MyElectronApp` folder. Its own extensions are stored in `~/Library/Application Support/Google/Chrome/Default/Extensions`, and it shouldn't and wouldn't poke around in other apps' data.

**Comment by stuartambient** [comment]
@kkshinkai apologies, you're right but in the original instructions I followed it was placed in  `Chrome/User Data/Default/Extensions/`
I'll make the change, ty!

**Comment by yxshv** [comment]
i am getting the same error

**Comment by mulgurul** [comment]
Please fix this soon so we dont have to workaround!

**Comment by spamshaker** [comment]
Versions 
        node:18.16.1
        acorn:8.8.2
        ada:1.0.4
        ares:1.19.1
        brotli:1.0.9
        cldr:43.0
        icu:73.1
        llhttp:6.0.11
        modules:116
        napi:8
        nghttp2:1.52.0
        openssl:1.1.1
        simdutf:3.2.2
        tz:2023c
        undici:5.21.0
        unicode:15.0
        uv:1.44.2
        uvwasi:0.0.15
        v8:11.6.189.20-electron.0
        zlib:1.2.13.1-motley
        electron:26.2.4
        chrome:116.0.5845.190

React Devtools 4.28.0_0

[2137:1001/130308.425155:ERROR:extensions_browser_client.cc(69)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Message: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ExecutionWorld')
  ID:      fmkadmapgofadopljbjfkapdkoienihi
  Type:    RuntimeError
  Context: chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
  Stack Trace: 
    {
      Line:     59
      Column:   1
      URL:      chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/background.js
      Function: (anonymous function)
    }

**Comment by codebytere** [comment]
@spamshaker addressed in https://github.com/electron/electron/pull/39676

**Comment by Bartel-C8** [comment]
@codebytere : Issue is still present in 27.0.0-beta.8 though?

**Comment by sprout2000** [comment]
Unfortunately, it is still the same in v26.3.

```sh
(node:58225) ExtensionLoadWarning: Warnings loading extension at /Users/XXXXX/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.28.4_0:
  Manifest contains a differential_fingerprint key that will be overridden on extension update.
```

**Comment by codebytere** [comment]
@sprout2000 that's a warning and not an error though? It should still load.

**Comment by sprout2000** [comment]
@codebytere 
Hmmm, I tried your code (minus the version number) and it was the same.

```javascript
const { app, BrowserWindow, session } = require("electron");
const path = require("node:path");
const { homedir } = require("node:os");

app.whenReady().then(async () => {
  await session.defaultSession.loadExtension(
    path.join(
      homedir(),
      "Desktop",
      "fmkadmapgofadopljbjfkapdkoienihi",
      "4.28.4_0"
    ),
    { allowFileAccess: true }
  );

  const w = new BrowserWindow();
  await w.loadURL("https://react.dev");
  w.webContents.toggleDevTools();
});
```

<img width="824" alt="スクリーンショット 2023-10-06 16 14 55" src="https://github.com/electron/electron/assets/52094761/84fdfd0a-b597-40f7-8031-7b99491377f6">

My guess is that the key is in the message below, but I don't know what it means.

```sh
Manifest contains a differential_fingerprint key that will be overridden on extension update.
```

**Comment by codebytere** [comment]
From `v26.3.0` on macOS Sonoma 14 on my machine, just now:

<img width="807" alt="Screenshot 2023-10-05 at 11 22 11 AM" src="https://github.com/electron/electron/assets/2036040/9e6fb694-bf71-4ad0-816a-c99e9cf757d5">

**Comment by sprout2000** [comment]
@codebytere 
You're right, it does work with Fiddle.
Hmmm, I need to find out what is wrong with my environment...

- Electron v27.0.0
- macOS Sonoma 14 (arm64)
- Node.js v18.18.0
- React Devtools v4.28.4

<img width="861" alt="スクリーンショット 2023-10-10 14 38 59" src="https://github.com/electron/electron/assets/52094761/6ec5ee7a-3c99-49ac-860e-3b2708c488d7">

**Comment by danielweck** [comment]
When you say "it works" ... can you actually see the React component hierarchy, or does the tree fail to load? The Chrome extension can load but the functionality can be broken.

**Comment by sprout2000** [comment]
@danielweck 
The tree can be displayed, although the notation is strange since it is after bundling. But only for execution with Fiddle.

<img width="800" alt="スクリーンショット 2023-10-10 18 15 22" src="https://github.com/electron/electron/assets/52094761/03198b76-b562-472a-b0de-987c67feb34d">

**Comment by sprout2000** [comment]
How to reproduce the problems I have:

1. Clone electron-quick-start
2. Edit `main.js`
3. Run the app

```sh
% git clone https://github.com/electron/electron-quick-start.git
% cd electron-quick-start
% npm install    # v26.3.0
```

```javascript
const { app, session, BrowserWindow } = require("electron");
const os = require("node:os");
const path = require("node:path");

app.whenReady().then(async () => {
  const mainWindow = new BrowserWindow();

  const extPath = path.join(
    os.homedir(),
    // Rewrite the Devtools version number accordingly
    "/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.28.4_0"
  );
  await session.defaultSession.loadExtension(extPath, {
    allowFileAccess: true,
  });

  await mainWindow.loadURL("https://react.dev");
  mainWindow.webContents.openDevTools();
});

app.once("window-all-closed", () => app.quit());
```

```sh
% npm start
```

- Does ANYONE have any problems loading the React Developer Tools with the code above?
- Why is there a problem with the above code when there is no problem with Fiddle?

**Comment by UndefinedOffset** [comment]
It seems based on my testing using the default Electron Fiddle on 25.9.0, 26.3.0 and 27.0.0 React Dev Tools will not load when using `mainWindow.loadFile()` even if you have `allowFileAccess: true` unless you are using a url like `https://react.dev` as has been used in examples above.

```javascript
const { app, BrowserWindow, session } = require('electron')
const path = require('path')

async function createWindow () {
  const extPath = "{extension path}";
  await session.defaultSession.loadExtension(extPath, {
    allowFileAccess: true,
  });
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  mainWindow.loadFile('index.html')

  mainWindow.webContents.openDevTools()
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

**Comment by Slapbox** [comment]
Now I'm even getting errors like:

```
proxy.js:116 Uncaught Error: Attempting to use a disconnected port object
    at handleMessageFromPage (proxy.js:116:10)
```

![image](https://github.com/electron/electron/assets/6835891/9d158014-8613-4a3d-affe-65f550c9f7b7)


Very frustrating that this is only getting more and more unusable even after years of struggles to get React Devtools working in Electron. Ever since the security upgrades, particularly `contextBridge` it's been impossible to keep React Devtools working, and now it even interrupts work when you've given up hope on using it.

**Comment by codebytere** [comment]
@UndefinedOffset can you explain a little more what you mean in https://github.com/electron/electron/issues/36545#issuecomment-1759547298? The way React Devtools works is that it does not show up on pages not containing any react components, so on a bare-bones html page it wouldn't show up by design.

**Comment by Slapbox** [comment]
Thanks for your reply @codebytere. We just recently started getting this issue where the debugger pauses on an uncaught exception on that line. I'm guessing there was some change in React Devtools to cause this but I don't know. It seems specific to the Electron environment but it may not be an Electron issue per se.

Our longer term problem has been that running the production app over a secure protocol prevents using the React Profiler with internal production builds, which is where it's intended to be used. https://github.com/electron/electron/issues/26812

**Comment by n-gist** [comment]
Can't get last DevTools (v. 4.28.5) working with Electron 27.0.2
When I replace extension files to other versions (4.25.0 or 4.27.1), it loads and working normally, but it is manifest 2 old versions.
using `allowFileAccess` or not gives no effect
using https://react.dev instead of local file url - no effect

**Comment by sprout2000** [comment]
Could you please reopen this issue? The problem still remains.

<img width="829" alt="スクリーンショット 2023-11-13 16 52 37" src="https://github.com/electron/electron/assets/52094761/5d6bc6cf-7ef6-4dd6-8711-0ee9f0126fb7">

The following is a reproduced code based on [electron-quick-start](https://github.com/electron/electron-quick-start):

```javascript
const { app, BrowserWindow, session } = require("electron");
const os = require("node:os");
const path = require("node:path");

function createWindow() {
  const mainWindow = new BrowserWindow();

  mainWindow.loadURL("https://react.dev");
  mainWindow.webContents.openDevTools();
}

const reactDevtoolsPath = path.join(
  os.homedir(),
  "/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.28.5_0"
);

app.whenReady().then(async () => {
  createWindow();
  await session.defaultSession.loadExtension(reactDevtoolsPath);
});

app.once("window-all-closed", () => app.quit());
```

I wonder if anyone else could run the above code as is and still have React Devtools load correctly.

**Comment by zhouzi** [comment]
The PR was merged 4 hours ago and the last release is 5 days old so the fix has not been released yet.

**Comment by sprout2000** [comment]
@zhouzi 
Oh... Sorry for the haste.

**Comment by zhouzi** [comment]
This fix is now released with v26.6.0, v27.1.0 and v28.0.0-beta.5 (it's still not working for me but it might be related to my setup).

**Comment by Bartel-C8** [comment]
Still fails to work for me for v27.1.0...


```
  [44477:1116/133228.513886:ERROR:extensions_browser_client.cc(69)] Extension Error:
    OTR:     false
    Level:   2
    Source:  chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
    Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
    ID:      dmcmnlnmbgdfljfjniabngbfglcgggdk
    Type:    RuntimeError
    Context: chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
    Stack Trace: 
      {
        Line:     107
        Column:   1
        URL:      chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
        Function: (anonymous function)
      }

```

React devtools tabs are there, but with the message :
```
Loading React Element Tree...

If this seems stuck, please follow the [troubleshooting instructions](https://github.com/facebook/react/tree/main/packages/react-devtools#the-issue-with-chrome-v101-and-earlier-versions).
```

**Comment by derekcicerone** [comment]
Not working for us either.

**Comment by Bartel-C8** [comment]
Not working here either on v27.1.0 on macos:
```
┏ Electron -------------------

  (node:48091) ExtensionLoadWarning: Warnings loading extension at /Users/bartel/git/klstr-ctrl/node_modules/electron-devtools-vendor/extensions/react-developer-tools:
    Permission '<all_urls>' is unknown or URL pattern is malformed.
  
  (Use `Electron --trace-warnings ...` to show where the warning was created)

┗ ----------------------------
```

```
┏ Electron -------------------

  [48091:1116/135717.525208:ERROR:extensions_browser_client.cc(69)] Extension Error:
    OTR:     false
    Level:   1
    Source:  manifest.json
    Message: Service worker registration failed. Status code: 15
    ID:      dmcmnlnmbgdfljfjniabngbfglcgggdk
    Type:    ManifestError

┗ ----------------------------
┏ Electron -------------------

  [48091:1116/135717.528034:ERROR:extensions_browser_client.cc(69)] Extension Error:
    OTR:     false
    Level:   2
    Source:  chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
    Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
    ID:      dmcmnlnmbgdfljfjniabngbfglcgggdk
    Type:    RuntimeError
    Context: chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
    Stack Trace: 
      {
        Line:     107
        Column:   1
        URL:      chrome-extension://dmcmnlnmbgdfljfjniabngbfglcgggdk/build/background.js
        Function: (anonymous function)
      }

┗ ----------------------------
```


Other extension (not React devtools)
```
┏ Electron -------------------

  [48091:1116/140148.092777:ERROR:CONSOLE(2)] "TypeError: Cannot read properties of undefined (reading 'action')", source: chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js (2)
  [48091:1116/140148.092907:ERROR:CONSOLE(2)] "Uncaught TypeError: Cannot read properties of undefined (reading 'action')", source: chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/window.bundle.js (2)

┗ ----------------------------
```

Should we do anything special to use the `chrome` API? Seems that no chrome API is working...
I am using https://github.com/BlackHole1/electron-devtools-vendor to load/install my extensions....

**Comment by JStrummer** [comment]
It seems to work fine for me with v.26.6.0

I can see the components tree and the state.

**Comment by sprout2000** [comment]
Still doesn't work on v27.1.0. What's wrong with my set up?

```javascript
const { app, session, BrowserWindow } = require("electron");
const path = require("node:path");
const os = require("node:os");

function createWindow() {
  const mainWindow = new BrowserWindow();
  mainWindow.loadURL("https://react.dev");
}

const reactDevtoolsPath = path.join(
  os.homedir(),
  "/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.28.5_0"
);

app.whenReady().then(async () => {
  createWindow();
  await session.defaultSession.loadExtension(reactDevtoolsPath);
});

app.once("window-all-closed", () => app.quit());
```

```sh
(node:14579) ExtensionLoadWarning: Warnings loading extension at /Users/doe/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.28.5_0:
  Manifest contains a differential_fingerprint key that will be overridden on extension update.
```

**Comment by julianmesa-gitkraken** [comment]
@sprout2000 
> Still doesn't work on v27.1.0. What's wrong with my set up?

You forgot: `, {allowFileAccess: true}`
it is: `await session.defaultSession.loadExtension(reactDevtoolsPath, {allowFileAccess: true});`

But it is not working for me I cannot see react devtools tabs.

**Comment by julianmesa-gitkraken** [comment]
@sprout2000 I think I've found a workaround.
Try to load the extension twice.
```
const { app, session, BrowserWindow } = require("electron");
const path = require("node:path");
const os = require("node:os");

function createWindow() {
  const mainWindow = new BrowserWindow();
  mainWindow.loadURL("https://react.dev");
}

const reactDevtoolsPath = path.join(
  os.homedir(),
  "/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.28.5_0"
);

app.whenReady().then(async () => {
  createWindow();
  await session.defaultSession.loadExtension(reactDevtoolsPath, {allowFileAccess: true});
  await session.defaultSession.loadExtension(reactDevtoolsPath, {allowFileAccess: true});
});

app.once("window-all-closed", () => app.quit());
```

**Comment by Bartel-C8** [comment]
Not able to get it working, even with the latest React Devtools...

Reproduction case in most simple form in Electron Fiddle (you can load the gist in Electron Fiddle): https://gist.github.com/Bartel-C8/0330843ddf220d8bddb64183acd7bcad

@codebytere : Would it be possible to re-open this issue? As it definitely does not seem resolved...

```
(node:7320) ExtensionLoadWarning: Warnings loading extension at /private/var/folders/_n/ln9pzc1s23z_619h7h6jv6d80000gn/T/electron-fiddle-4848-3ZIIKHaMCTZb/node_modules/electron-devtools-vendor/extensions/react-developer-tools:
  Permission '<all_urls>' is unknown or URL pattern is malformed.

(Use `Electron --trace-warnings ...` to show where the warning was created)
[7320:1122/093428.129424:ERROR:extensions_browser_client.cc(69)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://cjmlfkgkjjjlokhimplkmlegcbflodei/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'ExecutionWorld')
  ID:      cjmlfkgkjjjlokhimplkmlegcbflodei
  Type:    RuntimeError
  Context: chrome-extension://cjmlfkgkjjjlokhimplkmlegcbflodei/build/background.js
  Stack Trace: 
    {
      Line:     1
      Column:   1
      URL:      chrome-extension://cjmlfkgkjjjlokhimplkmlegcbflodei/build/background.js
      Function: (anonymous function)
    }

[7320:1122/093428.129629:ERROR:extensions_browser_client.cc(69)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      cjmlfkgkjjjlokhimplkmlegcbflodei
  Type:    ManifestError

[7320:1122/093428.622529:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[7320:1122/093428.622587:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)
```

**Comment by julianmesa-gitkraken** [comment]
@Bartel-C8 Can you try to load extension twice and load the extension before create createWindow?
I have extension errors but the extension works fine.
```
app.whenReady().then(() => {
  installExtensions()
  installExtensions()

  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})
```

**Comment by Bartel-C8** [comment]
> @Bartel-C8 Can you try to load extension twice and load the extension before create createWindow? I have extension errors but the extension works fine.
> 
> ```
> app.whenReady().then(() => {
>   installExtensions()
>   installExtensions()
> 
>   createWindow()
> 
>   app.on('activate', function () {
>     // On macOS it's common to re-create a window in the app when the
>     // dock icon is clicked and there are no other windows open.
>     if (BrowserWindow.getAllWindows().length === 0) createWindow()
>   })
> })
> ```


Does not work for me (macOS) with Electron Fiddle unfortunately. Does making this change in my gist work for you? Very strange...

> 
> Also you are using `mainWindow.loadFile('index.html')`, that index.html has no react. I recommmend the next test: `mainWindow.loadURL('https://react.dev');`

Same with loading `[react.dev ](https://react.dev)` , no React Devtools. And that should not matter normally, the React Devtools tab in the devtools should be available anyway.

**Comment by n-gist** [comment]
Double loading worked for me. Does not give me any errors though
Windows, electron 27.1.0, DevTools 4.28.5
```typescript
const devToolsPath = 'D:/Users/username/AppData/Roaming/octopus/extensions/fmkadmapgofadopljbjfkapdkoienihi'
const load2 = () => {
    session.defaultSession.loadExtension(devToolsPath).then(
        () => { createWindow() },
        () => {}
    )
}
const load1 = () => {
    session.defaultSession.loadExtension(devToolsPath).then(
        () => { load2() },
        () => {}
    )
}

let started = false
const start = () => {
    if (started) return
    started = true
    load1()
}

app.whenReady().then(() => {
    start()
    app.on('activate', () => start())
}).catch(console.log)
```

**Comment by Bartel-C8** [comment]
Got it fixed in my case, somehow the sources of my react devtools plugin provides had some issues in the manifest.json file, where "scripting" lacked under "permissions".


https://github.com/BlackHole1/electron-devtools-vendor/issues/35#issuecomment-1825476129

Manually copying the correct manifest.json let it work in my Electron Fiddle.
Sorry to bother! Thanks for your work on this @codebytere !

**Comment by alperen-bircak** [comment]
Still doesn't work for me, I get the same errors, does not work with double loading as well.

**Comment by rendomnet** [comment]
This is not WORKING!

**Comment by Bartel-C8** [comment]
Do try my workaround above, or vote for the new issue:

As this is a react devtools issue now, not related to electron...

https://github.com/facebook/react/issues/27749

**Comment by jameshfisher** [comment]
Does anyone have an example repo showing Electron with working React dev tools?
