### ISSUE TITLE
[Bug]: navigator.permissions.query always returns "granted"

### ISSUE THREAD

**Issue by t57ser** [electron/electron#38611]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

Windows

### Operating System Version

10.0.19042

### What arch are you using?

x64

### Expected Behavior

Calling `navigator.permissions.query({ name: "geolocation" }).then((result) => {console.log(result)})` should call a function in the main process (like ses.setPermissionCheckHandler(handler)) to ask for the permission result. (state "prompt" should also be supported)

### Actual Behavior

The state is always reported as "granted" 
This is happening for all kinds of permissions not just "geolocation"

**Comment by codebytere** [comment]
@t57ser that is what it does. It returns `granted` only if there is no check handler, which is what we've stated is the case previously.

By calling

```js
navigator.permissions.query({
    name: "display-capture"
}).then((result) => {
    console.log(result)
})
```

in the renderer process and adding 

```js
session.defaultSession.setPermissionCheckHandler((event, type) => {
   return false
})
```

you see the following, correctly, in console:
<img width="565" alt="Screenshot 2023-06-07 at 10 31 26 AM" src="https://github.com/electron/electron/assets/2036040/e1a067f0-7e4b-496d-aef8-269c277a07b4">

**Comment by t57ser** [comment]
That is indeed what happens. I do not know why I did not see this before. Trying again I do get into the permission check handler.
In this case the only issue would be that it isn't possible to return "prompt" as a result.
I think this would be useful, implementing the prompt handling could be done in the permission request handler via custom code

**Comment by t57ser** [comment]
Another weird thing i noticed is that i get into the handler twice. Is this intended?
I tried this in a very small example to ensure nothing else interfers
The code:
```
const electron = require("electron");
electron.app.whenReady().then(()=>{
	let main = new electron.BrowserWindow({
		"height" : 700,
		"width" : 800,
		show: true
	});

	main.loadURL("https://www.google.com").then(() => {
	});

	electron.session.defaultSession.setPermissionCheckHandler((webContents, permission, requestingOrigin, details ) => {
		console.log(`[permission check] ${permission} - ${details.requestingUrl}`);
		return true;
	});

})
```

**Comment by codebytere** [comment]
@t57ser no 🤔  i fixed something like this a while back: https://github.com/electron/electron/pull/36787

i wonder if they're related. I can look into it.

**Comment by wheezard** [comment]
Bump. There still isn't any way to return `prompt` from the permission check handler.

**Comment by codebytere** [comment]
@wheezard see https://github.com/electron/electron/issues/38611#issuecomment-1580196392

That the handler doesn't return prompt is a separate issue - you're welcome to file a new one.
