### ISSUE TITLE
[Bug]: Can't save performance traces from the performance tab in DevTools

### ISSUE THREAD

**Issue by Mike-Dax** [electron/electron#39818]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3 (21E230)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

24.8.2

### Expected Behavior

When recording a performance trace in the devtools, I should be able to hit the save button and save the JSON file for sharing and parsing in other applications.

### Actual Behavior

`Failed to save timeline: The request is not allowed by the user agent or the platform in the current context. (NotAllowedError)` is logged to the console

Zero byte file is created at the save location.

### Additional Information

On macOS Monterey 12.3 (21E230):

24.8.2 works
25.0.0 does not work 
25.3.2 does not work 
26.2.0 does not work
27.0.0-beta.1 does not work

On a Linux machine, 25.0.0 breaks while 24.0.0 works. 

`uname -a`: `Linux 6.5.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:01:01 +0000 x86_64 GNU/Linux`

**Comment by Etheryte** [comment]
This doesn't seem to be a bug in Electron, but instead an issue in Chromium. I can replicate the same error when trying to record a performance trace on a random webpage using the latest Chrome on macOS for example. At a glance I couldn't find a relevant issue on their issue tracker.

**Comment by Mike-Dax** [comment]
Chrome (`Version 117.0.5938.62 (Official Build) (arm64)`) works fine for me, while Electron doesn't work.

**Comment by Etheryte** [comment]
For context, the issue replicates for me on Chrome versions `116.0.5845.187 (Official Build) (x86_64)` as well as `117.0.5938.88 (Official Build) (x86_64)`. The latter is a slightly newer version than what you are running, so we can rule out them fixing it in Chromium between then and now.

**Comment by Bug-Reaper** [comment]
Same issue on:
- M1-Pro MacOS Ventura 13.5.
- Electron ^26.2.2

Very unfortunate as this blocks a proper analysis of many consecutive dropped frames w/no execution.

Was unable to resolve by manually applying full-disk access permissions to the bundled `electron.app`

**Comment by deepak1556** [comment]
Fixed with https://github.com/electron/electron/pull/41492

**Comment by whitenoisedev** [comment]
This is marked as backported but. Still happens 28.3.3. 

![Obsidian_qrZqBG8XX8](https://github.com/electron/electron/assets/3163647/caab3eb1-f208-42ce-a468-a4a58c21be13)

**Comment by deepak1556** [comment]
Sorry the issue was incorrectly marked as fixed for v28, let us know if the issue persists with >= v29. Thanks!
