### ISSUE TITLE
Windows 10 Browser Window Bounds Calculating Incorrectly

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#4045]
The Browser Window `width` and `x` coordinates are being calculated incorrectly in Windows 10 (Windows 8.1 did not have this problem). Here you can see that the `getBounds()` function is showing that my `x` value is 0 but the desktop background is showing through. I'm guessing this may have something to do with a subtle shadow that each window in Windows 10 is now casting.

![image](https://cloud.githubusercontent.com/assets/62191/12224314/36dccefa-b7a2-11e5-9ae0-a7181a41f1c7.png)

Not sure how to fix this, but would be nice to resolve as I have some window state management code written to pin windows in the correct location, and now they are not properly being positioned.

**Comment by kirkouimet** [comment]
Here is one more screenshot. In this screenshot the window should be positioned in the bottom left of the screen - you can see there is padding on the left, bottom, and right. Interestingly, the `y` value seems to be working correctly, so if you set `y` to zero it will appropriately put the window right at the top of the screen.

![image](https://cloud.githubusercontent.com/assets/62191/12224363/4619767e-b7a3-11e5-975b-b882838ca66f.png)

**Comment by kirkouimet** [comment]
And lastly, here is my code which addresses the issue until an official fix comes out:

	// Temporary hack to fix Windows 10 browser window sizing issues until Electron is fixed
	if(Node.OperatingSystem.platform() == 'win32' && Node.OperatingSystem.release().startsWith('10.')) {
		this.x = this.x - 7;
		this.width = this.width + 14;
		this.height = this.height + 7;
	}

**Comment by zcbenz** [comment]
Windows 10 has a thinner frame than before, and in order to be compatible with existing apps it is returning wrong values in its win32 APIs. You can reproduce the same problem in Chrome browser:

<img width="1058" alt="screen shot 2016-01-11 at 3 25 55 pm" src="https://cloud.githubusercontent.com/assets/639601/12228532/d726e7b2-b877-11e5-9c2a-59f466da93ca.png">

I have reported the problem to upstream: https://crbug.com/576192.

**Comment by lukeapage** [comment]
@zcbenz @kirkouimet I see the linked bug in chrome is closed as cannot reproduce - is this bug fixed or do you still have the problem?

**Comment by UAVova** [comment]
the problem is still here!

**Comment by kirkouimet** [comment]
Yeah someone is going to have to go and reopen that Chromium ticket and follow it through to the end

**Comment by paulcbetts** [comment]
Would setting a new key in our App manifest opt us out of this?

**Comment by zcbenz** [comment]
I hope so, but I can't find any documentation on it, even this behavior is not documented anywhere.

**Comment by paulcbetts** [comment]
Alright, I sent an Email to the relevant Microsoft MVP mailing list, we'll see if anyone has any ideas

**Comment by bsclifton** [comment]
Was this fixed with https://github.com/electron/electron/pull/9167 ?

**Comment by kevinsawicki** [comment]
> Was this fixed with #9167 ?

Perhaps, @kirkouimet could you confirm this as fixed in 1.6.7+?

**Comment by kirkouimet** [comment]
@kevinsawicki and @bsclifton this is still an issue as of Electron 1.8.2 on Windows 10 updated October 2017

**Comment by ErraticFox** [comment]
Any update regarding this?

**Comment by rdepena** [comment]
update ?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by CopyNippyJoin** [comment]
@sofianguy It's still an issue with Electron 4/5 and latest win 10.

**Comment by Stanzilla** [comment]
Super annoying issue a lot of Electron apps are having

**Comment by appurist** [comment]
This is still a problem in Electron 6.1.5. It's going to be a major problem for my app.

I can fix (only) the _left_ position by using a negative number, but it seems the width and height always fall short even if I set them larger.

**Comment by pushkin-** [comment]
Can repro with Electron 8

**Comment by Stanzilla** [comment]
@zcbenz @MarshallOfSound this is affecting high profile apps like Discord, any chance someone could look into it?

**Comment by Ansraer** [comment]
Managed to reproduce this issue with both vs code and Discord on a 1920x1080 display. Based on my testing the window is exactly 10px to wide/tall. I am currently running Windows 10 18362.
I would be happy to help with testing and/or collecting more data if someone can tell me what information is required.

**Comment by gerbus** [comment]
Still happening with Electron 8.2.2. 

It's possible based on my investigation that `BrowserWindow.getBounds()` in Windows 10 should be returning the equivalent of `window.innerHeight` and `window.innerWidth` but isn't. 

<img width="217" alt="windows_dimensions_mismatch" src="https://user-images.githubusercontent.com/2348366/85183744-af300680-b241-11ea-9646-31383ecfd5b8.png">

At the top of my devtools console, you can see the output of `BrowserWindow.getBounds()`, followed by dimensions from the browser's `window` object.

In my case, I'm setting the dimensions on a BrowserView to fit its parent BrowserWindow. When I set the dimensions on my BrowserView as follows, things seem to fit perfectly on Windows 10:
```
browserView.setBounds({
    width: browserWindow.getBounds().width - 16,
    height: browserWindow.getBounds().height - 59,
});
```

**Comment by nbanerje** [comment]
Is there an update on when this might be addressed or what the best workaround is?

**Comment by lynxtaa** [comment]
In my case I'm opening new child window alongside the right border of the parent window to fill the empty screen space. Right now my code looks like this. Looks hacky but works okay (Electron v9.1.0). Hope it helps:

```js
const currentWindow = remote.getCurrentWindow()
let { x, y, height, width } = currentWindow.getBounds()
const { workAreaSize } = remote.screen.getPrimaryDisplay()

// https://github.com/electron/electron/issues/4045#issuecomment-170399607
if (isWindows10()) {
  width -= 14
}

// https://github.com/electron/electron/issues/501
if (currentWindow.isMaximized()) {
  y += 7
}

const childWindowMinWidth = 500
const childWindowWidth = Math.max(workAreaSize.width - width - x, childWindowMinWidth)

const childWindow = new remote.BrowserWindow({
  height,
  minWidth: childWindowMinWidth,
  width: childWindowWidth,
  x: Math.min(width + x, workAreaSize.width - childWindowWidth),
  y,
  parent: currentWindow,
  minimizable: false,
})
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Stanzilla** [comment]
Well that's an annoying bot. Could at least ask if it is still an issue and then update the label.

**Comment by appurist** [comment]
> "Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated."

Ignore the bug report for 4 years -- TEN major releases -- and then close it due to it being reported against an unsupported version. "Brilliant" way to manage issue lists getting long. 

I disabled my apps' features of remembering window size and position, as a temporary workaround to this problem. (Not really a workaround.) For a while I tested this problem on every major update, and was one of the people who confirmed it was still present, for a while, when I hoped an update might include a fix. I stopped retesting it after major release after major release did not include any fix. Apparently, for those updates where I **did** retest it, I was wasting my time.

This is very discouraging, if not infuriating. And unfortunately this kind of policy will only damage code quality, especially as developers such as myself, see this as a clear reason to halt efforts to try to narrow down Electron bugs, to take the time to reproduce the problems and file bug reports against Electron, and instead begin the process of finding and migrating to different solutions to cross-platform development needs.

**Comment by junguksim** [comment]
Is this issue fixed? Still repro in 11.2.1

**Comment by ricardomomm** [comment]
Still happening on Windows 11

**Comment by ThaUnknown** [comment]
https://github.com/electron/electron/issues/45052#issuecomment-2571438611
