### ISSUE TITLE
[Bug]: BrowserView not rendering after WebContentsView PR got merged

### ISSUE THREAD

**Issue by andreasdj** [electron/electron#40792]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0-nightly.20231218

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise version 22H2

### What arch are you using?

x64

### Last Known Working Electron version

30.0.0-nightly.20231213

### Expected Behavior

When adding a BrowserView as a sub view to the main application window then renders the BrowserView correctly.

Also:
When adding a WebContentsView as a child to the contents view of the main application window then renders the WebContentsView correctly.

### Actual Behavior

The sub view is not rendered when using the old (deprecated) BrowserView or when using the new WebContentsView.

### Testcase Gist URL

https://gist.github.com/andreasdj/adbc1be41092a529d4d32d70325fbe14

### Additional Information

We have tested the behavior both when using the old deprecated BrowserView api and with the new WebContentsView api. In both scenarios the sub view is not rendered. It stopped working in the first nightly build after the WebContentsView PR (https://github.com/electron/electron/pull/35658) got merged.

The provided gist uses the old api. Here is another gist using the new api:
https://gist.github.com/andreasdj/780542e8a439ab71c1f7e98693b02dc4

There might be something we have missed that causes this. If so it would be good if that can be clarified in the docs.

**Comment by codebytere** [comment]
cc @nornagon

**Comment by nornagon** [comment]
Hm, this seems to be working on macOS. I guess the behavior must be different on Windows :/

<img width="912" alt="Screenshot 2024-01-02 at 11 27 13 AM" src="https://github.com/electron/electron/assets/172800/97bc8b84-139e-4bf5-94a6-200e6beb8c43">

**Comment by t57ser** [comment]
Also stopped working in v29.0.0-alpha.9

**Comment by nornagon** [comment]
Possibly fixed by #41256

**Comment by Kilian** [comment]
Reported this in the issue above. The issue persists in 30.

Relevant change where it stops working:

**Comment by nornagon** [comment]
Confirmed that #41256 fixes this.
