### ISSUE TITLE
[Bug]: GNU/Linux/Fedora/KDE: file selection dialog doesn't work

### ISSUE THREAD

**Issue by RES-1** [electron/electron#42250]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.4.0

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 38

### What arch are you using?

x64

### Expected Behavior

The file(s) highlighted in a file selection dialog should be communicated to the application.

### Actual Behavior

The file(s) marked in a file selection dialog are not communicated to the application.

### Additional Information

When under GNU/Linux/Fedora/KDE, for example, "electron https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file" is executed and the file selection dialog is started, the file selection is not reported back to the application. When the file selection dialog is confirmed, it appears as if no file has been selected. This prevents, for example, files from being selected or saved in "Signal Desktop".

Used software versions:
KDE Plasma: 5.27.11
KDE Frameworks: 5.115.0
Qt: 5.15.12

Some analyses on this issue were conducted under "https://bugzilla.suse.com/show_bug.cgi?id=1224940".

**Comment by RES-1** [comment]
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue?

Unfortunately I couldn't reproduce the problem with "Electron Fiddle".

I used the following code:

```
const { app, BrowserWindow, ipcMain, dialog } = require('electron');

let mainWindow;

app.on('ready', () => {
  mainWindow = new BrowserWindow({ width: 800, height: 600, webPreferences: { nodeIntegration: true, contextIsolation: false } });

  mainWindow.loadURL('data:text/html,<html><body><button id="open-dialog">Open Dialog</button><script>const { ipcRenderer } = require("electron");document.getElementById("open-dialog").onclick = () => { ipcRenderer.send("open-dialog"); };</script></body></html>');

  ipcMain.on('open-dialog', (event) => {
    dialog.showOpenDialog(mainWindow, {
      properties: ['openFile']
    }).then(result => {
      console.log(result.filePaths);
    }).catch(err => {
      console.log(err);
    });
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
```

```
<html>
<body>
  <button id="open-dialog">Open Dialog</button>
  <script>
    const { ipcRenderer } = require("electron");
    document.getElementById("open-dialog").onclick = () => {
      ipcRenderer.send("open-dialog");
    };
  </script>
</body>
</html>
```

The file selection dialog appears and after a file is selected, the file name appears in the console.

**Comment by RES-1** [comment]
I also noticed something else:

I noticed the problem when using "Signal Desktop".

When I restart the KDE session it is suddenly possible to add files to messages in "Signal Desktop". But as soon as I try to save a file attachment from a message, it doesn't work. From this point on it is no longer possible to attach files to messages until the KDE session is restarted.

However, the file selection still works in other applications.

**Comment by ayumi-signal** [comment]
We've received reports of this issue and @palant has a test fiddle to repro the issue on Fedora + KDE + Wayland: https://gist.github.com/palant/a2f96efd6019f2e989d8ae8fb7e17901

Details: https://github.com/signalapp/Signal-Desktop/issues/6912#issuecomment-2186223376

@RES-1 Could you try to repro using this fiddle?

They hypothesize it's related to the recent Linux shell dialog refactor: https://github.com/electron/electron/pull/42045

**Comment by palant** [comment]
@RES-1 It’s also obvious from my testing that this is an issue with the initial path displayed in the file selection dialog. While for me the dialog displays the contents of the home directory, it is actually initialized with some invalid path (indicated by “/” as title of the file list and missing icon on the Desktop folder). If I select my home directory explicitly, the file name is returned correctly. It’s only when I attempt to select a file within that initial invalid path that no file name is produced.

**Comment by RES-1** [comment]
> @RES-1 It’s also obvious from my testing that this is an issue with the initial path displayed in the file selection dialog. While for me the dialog displays the contents of the home directory, it is actually initialized with some invalid path (indicated by “/” as title of the file list and missing icon on the Desktop folder). If I select my home directory explicitly, the file name is returned correctly. It’s only when I attempt to select a file within that initial invalid path that no file name is produced.

I can confirm that. So it seems that the file path is initialized incorrectly in the file selection dialog. Are the tests with "Fiddle" still needed? If so, could someone else please run this test with GNU/Linux/Wayland/KDE (I unfortunately won't be able to run the test in the next few days)?

**Comment by palant** [comment]
Well, my gist should do: https://gist.github.com/palant/a2f96efd6019f2e989d8ae8fb7e17901

It shows the “Save File” dialog. When a file name is chosen, it’s supposed to display it in an alert message. But unless I change to a different (valid) directory, `dialog.showSaveDialog` doesn’t return anything – even if I choose an existing file. Worked correctly with Electron 30.0.3, broken on the 30.x branch starting with Electron 30.0.4 (31.0.2 also affected). Given how the look of the dialog changes as well, this is clearly a regression from #42045.

**Comment by mlaurencin** [comment]
@palant Are you saying that the refactor in https://github.com/electron/electron/pull/42045 caused a Signal specific regression or an overall regression in Electron? If the former, then I will go ahead and close this issue, but if the provided gist is still reproducing the issue, I can go ahead and update the labels accordingly. 

I'm going to add the `blocked\need-info` label for now. This issue will be closed in 10 days if the above is not addressed.

**Comment by palant** [comment]
@mlaurencin I am saying that the issue is generic, it is reproducible with the gist I provided. I’m merely adding that there is a factor making reproducing more difficult – last selected directory is being remembered somewhere, and I don’t know where. When the last selected directory isn’t remembered, the dialog is broken.

**Comment by RES-1** [comment]
https://github.com/electron/electron/pull/42685

**Comment by mlaurencin** [comment]
@RES-1 does the PR you linked above fix this issue for you? If so, I will go ahead and close this issue.

**Comment by RES-1** [comment]
> @RES-1 does the PR you linked above fix this issue for you? If so, I will go ahead and close this issue.

I have just updated to "nodejs-electron-30.3.0-2.2.x86_64". The problem still exists. Unfortunately, I cannot determine which version contains the referenced change. I may have to wait for the test until the change arrives via "https://download.opensuse.org/repositories/network:/im:/signal/Fedora_40/".

**Comment by brjsp** [comment]
@RES-1 That's because i have not merged that change yet. I'll try to push a build you can check tomorrow.

**Comment by brjsp** [comment]
@RES-1 @mlaurencin I just checked and 30.3.0 already has that commit merged — so the answer must be “no, it does not fix”

**Comment by RES-1** [comment]
> @RES-1 @mlaurencin I just checked and 30.3.0 already has that commit merged — so the answer must be “no, it does not fix”

@trevor-signal says that the problem will only be fixed with version "31.2.0":

https://github.com/signalapp/Signal-Desktop/issues/6912#issuecomment-2243081065

**Comment by RES-1** [comment]
https://github.com/microsoft/vscode/issues/213780#event-13826392891

I am now waiting for "30.3.1" from "https://download.opensuse.org/repositories/network:/im:/signal/Fedora_40/".

**Comment by brjsp** [comment]
> I am now waiting for "30.3.1" from "https://download.opensuse.org/repositories/network:/im:/signal/Fedora_40/".

I have already published 30.3.0 when it got released.
There are zero changes in 30.3.1 compared to 30.3.0: https://github.com/electron/electron/compare/v30.3.0...v30.3.1

**Comment by RES-1** [comment]
> I have already published 30.3.0 when it got released. There are zero changes in 30.3.1 compared to 30.3.0: [v30.3.0...v30.3.1](https://github.com/electron/electron/compare/v30.3.0...v30.3.1)

In "nodejs-electron-30.3.0-2.15.x86_64" the problem is not yet fixed.

**Comment by RES-1** [comment]
bump

**Comment by RES-1** [comment]
bump

**Comment by RES-1** [comment]
https://github.com/signalapp/Signal-Desktop/issues/6912#issuecomment-2619654543

**Comment by basil** [comment]
I can reproduce https://github.com/electron/electron/issues/42250#issuecomment-2187274111 consistently with `xdg-desktop-portal-kde`, but not with any other portal (e.g., `xdg-desktop-portal-gtk` works fine). Also, `xdg-desktop-portal-kde` works fine on KDE 5 (Ubuntu 20.04), but it consistently exhibits this bug on KDE 6 (Fedora 42).

**Comment by basil** [comment]
After reading the Chromium sources, I can see that this is implemented with IPC (D-Bus) which makes it pretty easy to observe with `dbus-monitor 'interface=org.freedesktop.impl.portal.FileChooser'`. For reference the docs are [here](https://libportal.org/method.Portal.save_file.html). I tried saving a page in Google Chrome, and I saw this:

```
method call time=1746306573.769490 sender=:1.28 -> destination=:1.50 serial=4081 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.impl.portal.FileChooser; member=SaveFile
   object path "/org/freedesktop/portal/desktop/request/1_217/66321DC30320F56BACD61F39CF39F14C"
   […]
   string "All Files"
   array [
      dict entry(
         string "modal"
         variant             boolean true
      )
      dict entry(
         string "filters"
         […]
      )
      dict entry(
         string "current_filter"
         […]
      )
      dict entry(
         string "current_name"
         variant             string "New Tab.html"
      )
      dict entry(
         string "current_folder"
         variant             array of bytes "/home/basil/Downloads" + \0
      )
   ]
```

So the D-Bus API has `current_name` (Suggested filename), `current_folder` (suggested folder to save the file in), and `current_file` (when saving an existing file), and Google Chrome is setting `current_name` to a relative name but `current_folder` to an absolute path.

---

In my Fiddle test, with `defaultPath` I see:

```
method call time=1746307101.121485 sender=:1.28 -> destination=:1.50 serial=4310 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.impl.portal.FileChooser; member=SaveFile
   object path "/org/freedesktop/portal/desktop/request/1_236/38ECEED33679B29B3384B2CA8005CD88"
   string "x11:0x3600004"
   string "Save File"
   array [
      dict entry(
         string "modal"
         variant             boolean true
      )
      dict entry(
         string "filters"
         […]
      )
   ]
```

With `defaultPath` set to `myfile.txt` I see:

```
method call time=1746307156.758538 sender=:1.28 -> destination=:1.50 serial=4363 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.impl.portal.FileChooser; member=SaveFile
   object path "/org/freedesktop/portal/desktop/request/1_243/44DBEF88A06AE7AAA55EFA4313A92C7E"

   string "x11:0x3600004"
   string "Save File"
   array [
      dict entry(
         string "modal"
         variant             boolean true
      )
      dict entry(
         […]
      )
      dict entry(
         string "current_name"
         variant             string "myfile.txt"
      )
      dict entry(
         string "current_folder"
         variant             array of bytes "." + \0
      )
   ]
```

So here Electron is passing to D-Bus a `current_folder` of "."

---

This issue only seems to affect `xdg-portal-kde`. Debug input can be found by running `QT_LOGGING_RULES='xdp*.debug=true' /usr/libexec/xdg-desktop-portal-kde`. From Google Chrome:

```
xdp-kde-file-chooser: SaveFile called with parameters:
xdp-kde-file-chooser:     handle:  "/org/freedesktop/portal/desktop/request/1_284/7624560164309A83EFD185A8205D9DE7"
xdp-kde-file-chooser:     parent_window:  "x11:0x2a00004"
xdp-kde-file-chooser:     title:  "All Files"
xdp-kde-file-chooser:     options:  QMap(("current_filter", QVariant(QDBusArgument, ))("current_folder", QVariant(QByteArray, "/home/basil/Downloads\x00"))("current_name", QVariant(QString, "New Tab.html"))("filters", QVariant(QDBusArgument, ))("modal", QVariant(bool, true)))
```

From my Electron app:

```
xdp-kde-file-chooser: SaveFile called with parameters:
xdp-kde-file-chooser:     handle:  "/org/freedesktop/portal/desktop/request/1_279/9FB3243269595A687B01988F4EAB98CA"
xdp-kde-file-chooser:     parent_window:  "x11:0x1000004"
xdp-kde-file-chooser:     title:  "Save Score"
xdp-kde-file-chooser:     options:  QMap(("current_folder", QVariant(QByteArray, ".\x00"))("current_name", QVariant(QString, "Untitled-1"))("filters", QVariant(QDBusArgument, ))("modal", QVariant(bool, true)))
```

**Comment by basil** [comment]
From the above analysis it is clear that there is a bad interaction between Chromium/Electron and `xdg-desktop-portal-kde` when relative paths are used in the save file chooser. When Chromium/Electron sets `current_folder=.` then `xdg-desktop-portal-kde` (but not any of the other portals) exhibits the behavior shown in https://github.com/electron/electron/issues/42250#issuecomment-2187274111 and then save fails. This is affecting at least two open-source Electron-based applications. When an absolute path is used, the issue does not occur. This issue started occurring with `xdg-desktop-portal-kde` sometime in the past few years, as the version in Ubuntu 20.04 LTS worked fine.

What's not clear to me is whether this is a bug in `xdg-desktop-portal-kde` or a bug in Chromium/Electron. The documentation [here](https://libportal.org/method.Portal.save_file.html) does not mention anything about relative vs absolute paths. That, combined with the fact that older versions of `xdg-desktop-portal-kde` worked (and other portals also work) leads me to suspect an `xdg-desktop-portal-kde` bug. That having been said, it also seems unnecessary for Chromium/Electron to be passing `current_folder=.` in this case when the parameter is optional and the user likely meant to save the file in the "default" (current? last?) directory here.

@hsitter @codebytere Could you take a look at the above analysis and let me know your initial thoughts? I am happy to file an `xdg-desktop-portal-kde` bug if the issue truly lies there.

**Comment by basil** [comment]
Here is a minimal reproducible example that shows the issue with `xdg-desktop-portal-kde` without using Chromium/Electron:

```python
import dbus
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib

DBusGMainLoop(set_as_default=True)
loop = GLib.MainLoop()
bus = dbus.SessionBus()
portal = bus.get_object(
    "org.freedesktop.portal.Desktop", "/org/freedesktop/portal/desktop"
)
file_chooser = dbus.Interface(portal, "org.freedesktop.portal.FileChooser")


def response_handler(response, results):
    if response == 0:
        uris = results["uris"]
        print("Selected files:")
        for uri in uris:
            print(uri)
    else:
        print("File selection canceled or failed")
    loop.quit()


options = {
    "current_name": "suggested_filename.txt",
    "current_folder": dbus.ByteArray(b".\0"),
}
request_path = file_chooser.SaveFile("", "Save a file", options)
request = bus.get_object("org.freedesktop.portal.Desktop", request_path)
request.connect_to_signal(
    "Response", response_handler, dbus_interface="org.freedesktop.portal.Request"
)
loop.run()
```

This mimics Chromium/Electron by setting `current_folder=.` When run against `xdg-desktop-portal-kde`, this reproduces the issue mentioned in https://github.com/electron/electron/issues/42250#issuecomment-2187274111, and no file selection is returned unless the user first navigates to their home directory in **Places** before selecting the file. My question is: is this valid input (in which case this would be an `xdg-desktop-portal-kde` bug), or should Chromium/Electron be sending a different value for `current_folder` here?

**Comment by RES-1** [comment]
The problem no longer occurs on "Fedora 41" with "signal-desktop-7.54.0-1.1.x86_64" and "nodejs-electron-35.4.0-1.1.x86_64".
