### ISSUE TITLE
[Bug]:  error 'eglQueryDeviceAttributeXT: Bad attribute'

### ISSUE THREAD

**Issue by geedys** [electron/electron#43415]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0 & 32.0.1

### Build Tool
electron-vite: 2.3.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sonoma 14.6.1

### What arch are you using?

x64

### Last Known Working Electron version

31.4.0

### Expected Behavior

I don't want to encounter the error 'eglQueryDeviceAttributeXT: Bad attribute

### Actual Behavior

When I started the development environment (npm run dev), the console reported the following error, and it was continuously outputting this error:
```bash
[18489:0822/130231.159571:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[18489:0822/130231.525693:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[18489:0822/130231.758610:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[18489:0822/130232.026468:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[18489:0822/130232.358755:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[18489:0822/130232.526215:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[18489:0822/130232.966085:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
```

**Comment by test001qwerty** [comment]
same issue.
macOS 11.7.7
electron v32.0.1
node v20.16.0

**Comment by benoitwerner** [comment]
same issue.
macOS 13.6.9
electron v32.0.1
node v16.17.0

**Comment by nvxtien** [comment]
same issue
macOS 10.15.6
electron v32.0.1
node v16.20.0

**Comment by geedys** [comment]
> same issue macOS 10.15.6 electron v32.0.1 node v16.20.0
> 
> [This](https://github.com/electron/electron/issues/28164) works for me.

Thank you very much for your reply. I am using app. disableHardwareAcceleration(); Then the console indeed stopped reporting errors. But is this just a temporary solution?

**Comment by nvxtien** [comment]
> > same issue macOS 10.15.6 electron v32.0.1 node v16.20.0
> > [This](https://github.com/electron/electron/issues/28164) works for me.
> 
> Thanks for your reply! I am using app. disableHardwareAcceleration(); Then the console indeed stopped reporting errors. But is this just a temporary solution?

I'm not sure. However, I think this is a Chromium implementation detail and not a bug in Electron.

**Comment by thegnuu** [comment]
Some of our devs have the same issue since we updated to electron 32, but it looks like the error only occurs on intel based macs, no issues on my apple silicon so far.

**Comment by liangskyli** [comment]
I also encountered the same problem

**Comment by marc-schieferdecker** [comment]
> I had the same issue when I updated from electron31.4.0 to 32.0.1 My configuration: macOS 14.2.1 intel electron v32.0.1 node v22.6.0

I'm also developing on an Intel MacBook (macOS 14.6.1) and can confirm the bug exists also with electron v32.0.2. My node version is 20.17.0.

**Comment by doctorXWrites** [comment]
Same issue V 32.0.2
`[5001:0915/173427.791920:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.`

**Comment by scottnonnenberg-signal** [comment]
I get thesee log lines at a very fast rate on an Intel Mac with _AMD Radeon Pro 5500M 4 GB/Intel UHD Graphics 630 1536 MB_ on Electron v32.1.0:

```
[65342:0913/162256.369523:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[65342:0913/162256.388282:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[65342:0913/162256.405696:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[65342:0913/162256.423287:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[65342:0913/162256.441106:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[65342:0913/162256.460208:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
```

**Comment by danielweck** [comment]
`app.commandLine.appendSwitch("disable-gpu")` works for me, but not `--disable-gpu` on the actual Electron command line. Version `32.1.1`

**Comment by marc-schieferdecker** [comment]
> `app.commandLine.appendSwitch("disable-gpu")` works for me, but not `--disable-gpu` on the actual Electron command line. Version `32.1.1`. I did not use `app.disableHardwareAcceleration()` or `app.commandLine.appendSwitch("disable-software-rasterizer")`

This works also as a temporarily fix, but depending on you application the performance will be not good.

add to main js file:

```js
import os from 'os';
if (os.platform() === 'darwin' && os.arch() === 'x64') {
  app.disableHardwareAcceleration();
}
```

**Comment by danielweck** [comment]
> This works also as a temporarily fix, but depending on you application the performance will be not good.

In order to work around this problem with v32 I disable the GPU in my "headless" Electron project but in another GUI application I have no choice but to downgrade to v31 which doesn't seem to exhibit the bug.

**Comment by danielweck** [comment]
Ah, this seems fixed in v33 :)
https://github.com/electron/electron/releases/tag/v33.0.0-beta.1

**Comment by Kresilas** [comment]
**Context**:
Mac Mini Intel 2012
macOS 12.7.6 Monterey
node v20.17.0
electron v32.2.0

To avoid `EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute` in my electron project, main.js starts with:
```
const { app, BrowserWindow } = require('electron')
if (process.platform === 'darwin' && process.arch === 'x64') {
	app.disableHardwareAcceleration()
}
```

**Comment by geedys** [comment]
This issue has been resolved in version 33.0.0

**Comment by trinitronx** [comment]
Issue still present in Electron `33.0.0` with Chromium `v130.0.6723.59` on macOS `12.7.6` Monterey.  Can reproduce also in Google Chrome version `130.0.6723.59`:

```console
[32323:259:1018/011918.672903:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#141 is a dynamic-sized tensor).
[32323:259:1018/011919.174036:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[32323:259:1018/011919.672593:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
```

Seems that this should be a bug filed against Chromium instead? 🤷

**Comment by Schneegans** [comment]
@geedys Has this really been solved for you? For me (macOS 11.7.10, Electron 33.0.1) the issue is still present.

**Comment by efrechette-rga** [comment]
This just started occurring for me with Slack 4.40.133, which is an Electron app. Not sure what Electron version is being used, but I'm on macOS 14.7.

**Comment by Schneegans** [comment]
Can we reopen this?

**Comment by ccrvlh** [comment]
Getting the same issue with VSCode (1.95.2), Electron (32.2.1) while trying to run tests for a custom Extension (macOS Intel). Haven't been able to try 33.x yet. Any other info that can be useful for debugging?

**Comment by a10036gt** [comment]
@ccrvlh seems the issues is from chromium project, although that info will not cause problem but annoying.

**Comment by geedys** [comment]
@Schneegans @a10036gt 
My system is currently Intel MacOS 15.1.1, and the Electron version is 33.2. It is true that this error has not occurred again. I'm not sure if it's related to the system upgrade.

**Comment by Schneegans** [comment]
I still see the issue with Electron 33.2.1 / Chrome 130.0.6723.137.

**Comment by hovancik** [comment]
Please reopen, still issue in electron 34.

**Comment by andyImatest** [comment]
This appears to be fixed on Electron v34.0.2, I was able to remove my workaround call to "app.disableHardwareAcceleration()" on mac, and no longer see all of the error messages on the console. I'm running macOS Sonoma 14.7.2.

**Comment by a10036gt** [comment]
It seems that this issue depends on the OS version and hardware. Some people use OpenCore to run newer macOS versions on old MacBooks, which appears to cause this problem.

**Comment by Schneegans** [comment]
Still an issue for me on macOS 11.7.10 and Electron 34.1.0.

**Comment by danielweck** [comment]
I am still experiencing this issue, which seems to be dependent on hardware and operating system details (on random occasions the error didn't occur, but most of the time it does). Where needed I used the `--disable-gpu` command line argument, or equivalent Javascript Electron API. This seems to stop the console error messages which indicate a crash of the GPU process.

**Comment by zhenhuacai** [comment]
same issue
macOS Sequoia 15.3.1
electron v32.2.3
node v20.18.1

**Comment by trinitronx** [comment]
> It seems that this issue depends on the OS version and hardware. Some people use OpenCore to run newer macOS versions on old MacBooks, which appears to cause this problem.

While it _may_ be dependent on OS version and hardware (likely due to GPU hw specifically), it's not true to assume that only OpenCore running unsupported newer OS on older Apple hardware is the culprit.

Case in point:

[Reproduced on macOS Monterey `12.7.6`][1], which is the last official Apple-supported OS version for a MacBook Pro (`Retina, 13-inch, Early 2015`).  (This hardware has GPU: `Intel Iris Graphics 6100 1536 MB`)

[1]: https://github.com/electron/electron/issues/43415#issuecomment-2421635097

**Comment by Schneegans** [comment]
Still an issue with Electron 35.1.2 / Chrome 134.0.6998.178.

**Comment by D3vil0p3r** [comment]
@ckerr please can you reopen the issue? It is still present on newer version and make "supported" Electron versions almost unusable on macOS due to rendering performance issue. This bug is alive for half year.

**Comment by Sogl** [comment]
Still an issue with Electron 35.1.5, latest Chrome (tested on iMac late 2013)
