### ISSUE TITLE
desktopCapturer.getSources got error appIcon

### ISSUE THREAD

**Issue by wanghanzhen** [electron/electron#48063]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

36.5.0

### What operating system(s) are you using?

macOS

### Operating System Version

macOS26 beta

### What arch are you using?

arm64 (including Apple Silicon)

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

invoking appIcon.toDataURL() should get a normal url.

<img width="515" height="133" alt="Image" src="https://github.com/user-attachments/assets/0e09488c-2759-4e3f-8d95-30d0bb47578f" />

### Actual Behavior

got a error url

<img width="1497" height="934" alt="Image" src="https://github.com/user-attachments/assets/b799da4a-baff-4918-9bd3-00473c047bc0" />

### Testcase Gist URL

https://gist.github.com/wanghanzhen/bac0d6782ce8c995293d86375263545b

**Comment by nikwen** [comment]
Thanks for reporting! Does this still happen on Electron v37?

**Comment by wanghanzhen** [comment]
> Thanks for reporting! Does this still happen on Electron v37?

yeah

**Comment by codebytere** [comment]
> macOS26 beta

does this happen on stable versions? I can't reproduce this on macOS 15.6

**Comment by wanghanzhen** [comment]
> > macOS26 beta
> 
> does this happen on stable versions? I can't reproduce this on macOS 15.6 

No,only macOS26 Beta 🥹

**Comment by codebytere** [comment]
@wanghanzhen thanks - that's helpful! We'll look into it :)

**Comment by wanghanzhen** [comment]
> [@wanghanzhen](https://github.com/wanghanzhen) thanks - that's helpful! We'll look into it :)

Is there any progress here?🤔

**Comment by nikwen** [comment]
People have tried to look into it, but we're all pretty busy. PRs welcome if you have time to look into it yourself. :)

**Comment by KanishkRanjan** [comment]
I have looked into this issue, I think this is fixed as I got expected behavior. 

<img width="1189" height="301" alt="Image" src="https://github.com/user-attachments/assets/bb15fcf4-5380-4f67-99e1-de9f4f464c1a" />

**Comment by nikwen** [comment]
Not fixed for me on macOS 26.1:

<img width="515" height="251" alt="Image" src="https://github.com/user-attachments/assets/694f69d9-bde1-42e8-a8ec-5d2f9a08f812" />

**Comment by KanishkRanjan** [comment]
@nikwen 

Sorry for wrong report,
When I tried to reproduce this, the very application ( ARC browser ) I chose to  worked well.

After a lot of digging I found the root cause of the bug, it's in chromium code

chrome/browser/media/webrtc/window_icon_util_mac.mm.

I noticed that window_icon_util_mac.mm has very strict validation checks. Specifically, this condition was causing early returns for valid icons:

```
if (CGImageGetBitsPerPixel(cg_icon_image) != 32 ||
    CGImageGetBitsPerComponent(cg_icon_image) != 8) {
  return gfx::ImageSkia();
}
```

I have the patched and have tested it's work build but I am unable to push it, I am new to OSS but have contribute to org like vscode 

I read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md)

I am so sry for asking but could you guide me 


[chromium code which is root cause of this error](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/window_icon_util_mac.mm;l=1?q=window_icon_util_mac.mm&sq=&ss=chromium%2Fchromium%2Fsrc)

**Comment by KanishkRanjan** [comment]
Could I do contribution in chromium org and tag it here ?

**Comment by nikwen** [comment]
@KanishkRanjan Thank you for looking into it!

If the issue is in Chromium, please submit the patch to Chromium. Here are Chromium's guides for contributing code: https://chromium.googlesource.com/chromium/src/+/main/docs/contributing.md

After the fix is merged into Chromium, Electron will pick it up, too, when we bump our Chromium version.

Appreciate you doing this work! 🙏

**Comment by nikwen** [comment]
(And yes, please share the link to it here.)

**Comment by KanishkRanjan** [comment]
I will be linking it soon. ( my mac storage ran out 😅, waiting for ssd to arrive )

**Comment by KanishkRanjan** [comment]
@nikwen 

I have raised the issue and committed the fix. Here are the links:

- Chromium Issue: https://issues.chromium.org/issues/465028835
- CL (Review): https://chromium-review.googlesource.com/c/chromium/src/+/7206079

I had fun while fixing and learned quite a bit in the process . Would you please suggest me some more issues work upon

**Comment by nikwen** [comment]
@KanishkRanjan Congrats! That's not an easy issue to fix, especially as your first contribution. Good job!

In general, feel free to pick any issue from our issues backlog that sounds interesting to you.

I think the following two issues could be worth exploring:

- https://github.com/electron/electron/issues/46493
- https://github.com/electron/electron/issues/43531

**Comment by ManavJain709** [comment]
@KanishkRanjan do you have any idea which version of chromium will this fix be in?

**Comment by KanishkRanjan** [comment]
@ManavJain709, the patch is still under review by the Chromium team

If this is necessary for your project, share the details and I will try to find a workaround.
One option that comes to mind is to manually scan the /Applications folder and extract the icons.

**Comment by ManavJain709** [comment]
I think we can wait for it to be resolved thanks.

**Comment by nikwen** [comment]
[Kanishk's patch](https://chromium-review.googlesource.com/c/chromium/src/+/7239386) has made it into Chromium! :tada:

Unfortunately, the reviewers [insisted](https://chromium-review.googlesource.com/c/chromium/src/+/7239386/comment/284cc0dc_fb06554b/) on reducing the icon size to 32x32 pixels. This is because Chromium only ever shows the icon as 32x32px and Chromium wants all code in the Chromium repo to be in service of Chromium only.

In Electron, we probably want to return higher-quality icons (as before this patch).

I see two options to get higher-quality icons back:

1. Introduce Electron’s own logic for obtaining the icon instead of relying on Chrome. Pro: doesn’t require a patch.
2. Patch Chromium in `patches/chromium` in the Electron project. Con: requires a patch.

The patch would be to add `[icon_image setSize:NSMakeSize(128, 128)];` [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/window_icon_util_mac.mm;l=55;drc=bc5394765e49981ab69c744240cc5fb68f4b2a99).

If we introduce logic in Electron, we could copy [this upstream code](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/window_icon_util_mac.mm;l=25-57;drc=bc5394765e49981ab69c744240cc5fb68f4b2a99) and call it on macOS instead of the upstream function.

A third option would be to accept the lower resolution. (This might require app developers to adjust how they render the icons.)

@VerteDinde @dsanders11 What do you think?

**Comment by nikwen** [comment]
The more I think about it and especially after rereading our [patch policy](https://github.com/electron/electron/blob/main/docs/development/patches.md#patch-justification), I believe the following is the best path forward:

Introducing a function like this:

```cpp
gfx::ImageSkia DoGetWindowIcon(content::DesktopMediaID id) {
#if BUILDFLAG(IS_MAC)
  // TODO: Implement GetWindowIconMac to contain this code but set a higher icon size: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/window_icon_util_mac.mm;l=25-57;drc=bc5394765e49981ab69c744240cc5fb68f4b2a99
  return GetWindowIconMac(id);
#else
  return GetWindowIcon(id);
#endif
}
```

And then calling this function wherever we currently call `GetWindowIcon`.

Copying code is not great, but if we have the choice between copying and patching, copying is probably better here.

**Comment by fanhillary** [comment]
Hi @nikwen , would you happen to have an ETA on the DoGetWindowIcon solution you mentioned above?
Looking for a long-term solution for Electron outside of the Chromium patch!

**Comment by nikwen** [comment]
@fanhillary I don't have an ETA. Most maintainers are [off for the holidays](https://www.electronjs.org/blog/dec-quiet-period-25).

However, @KanishkRanjan has a [PR](https://github.com/electron/electron/pull/49219) up that will solve the issue. A realistic timeline to have it released would be some time in January.

**Comment by nikwen** [comment]
Fixed in v40 via https://github.com/electron/electron/pull/50188 and v41+ via https://chromium-review.googlesource.com/c/chromium/src/+/7239386.

Thanks, @KanishkRanjan.
