### ISSUE TITLE
Audio stream from Electron applications is named "Chromium"

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7470]
- Electron version: `1.4.1`
- Operating system: `Linux`

> In pavucontrol the stream from gpmdp is listed as Chromium. Because of this, I can't permanently move Chromium (e.g. Youtube) audio and Google Play audio to different sinks.
> 
> It would be nice if the stream had a more unique name.

I have no idea where this is set, but it would be nice to either be able to change this at build time or have an API to change it at run time.

:link: [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1720](https://www.github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1720)

**Comment by deepak1556** [comment]
setting `media::AudioManager::SetGlobalAppName` should fix the name problem, but the pulse application.icon_name property is hardcoded [here](https://cs.chromium.org/chromium/src/media/audio/pulse/pulse_util.cc?l=306), we have to patch libchromiumcontent to expose `kBrowserDisplayName`.

**Comment by kevinsawicki** [comment]
Including the upstream issue link here in case people want to track it:

https://bugs.chromium.org/p/chromium/issues/detail?id=653828

**Comment by codebytere** [comment]
Closing this as it appears to have been resolved by above linked PRs.

**Comment by Araxeus** [comment]
This issue should probably;y be reopened as it seems this hasn't been fixed...

**Comment by TheInfamousAlk** [comment]
This is still an issue, I struggle every day with several apps all being called "chromium", and me not being able to set their default audio outputs correctly.

**Comment by TheInfamousAlk** [comment]
There is another feature request open for this. Linking so anyone who found their way here from a search engine like I did can see: https://github.com/electron/electron/issues/27581
