### ISSUE TITLE
Frameless windows get problem with the new "Tabs everywhere" system in macOS Sierra

### ISSUE THREAD

**Issue by pmkary** [electron/electron#7726]
I have a frameless window as such: (traffic lights are also handmade)

<img width="1045" alt="screen shot 2016-10-25 at 2 49 46 pm" src="https://cloud.githubusercontent.com/assets/2157285/19684154/8ea5a54a-9ac2-11e6-80e5-674e004eee6f.png">

After the Sierra my app gets these menus in the Window menu:

<img width="260" alt="screen shot 2016-10-25 at 2 49 26 pm" src="https://cloud.githubusercontent.com/assets/2157285/19684188/ba0b2dae-9ac2-11e6-8d38-25213a3b99e6.png">

And the button adds a tab bar in somewhere that no one expects:

<img width="1068" alt="screen shot 2016-10-25 at 2 49 33 pm" src="https://cloud.githubusercontent.com/assets/2157285/19684214/e29e6934-9ac2-11e6-94a2-d44638459747.png">

I think in the first place a frameless window should not be able to have these tabs. And then a question brings that how do other Electron apps handle this? what should I do?

**Comment by MarshallOfSound** [comment]
What version of Electron are you using?  *The issue template asks this for a reason)*

This was fixed in a recent version of Electron

**Comment by pmkary** [comment]
Ah that's very true. Sorry for that. I used the latest version 1.4.4 but when I checked the version internally I saw that it was 1.4.2, Still don't know how that happened but yes it was fixed with re-downloading the bundle. thanks for your time 👍
