### ISSUE TITLE
app.relaunch crashes under sandboxed environment

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#7738]
- Electron version: 1.3.7+
- Operating system: macOS

When your entitlements are set to run from the sandbox, code like this:

``` js
app.relaunch();
app.exit(0);
process.exit(0);
```

Will trigger the following crash:

```
Could not set sandbox profile data: Operation not permitted (1)
```

[crash-report.txt](https://github.com/electron/electron/files/551738/-.txt)

**Comment by lipis** [comment]
Anything new with this one?! No pressure.. just curious :)

**Comment by oldj** [comment]
I got the same error, and found something [here](https://docs.google.com/document/d/108sr6gBxqdrnzVPsb_4_JbDyW1V4-DRQUC4R8YvM40M/edit):

> It is also not possible to call sandbox_init() more than once. If you attempt this, the kernel will report a sandbox violation "deny forbidden-sandbox-reinit" and kill the process. It is not possible to avoid this error; if a Sandbox MAC label has been applied to the process, and another one is attempted, then it reports the violation:

I do not know if this related?

**Comment by herrmannplatz** [comment]
Still present in 1.6.3

**Comment by mat1th** [comment]
Maybe this issue is related #8957. And this issue is fixed in the latest release with pull request 8957.

**Comment by zcbenz** [comment]
I'm closing this issue since it is reported to have been fixed by #8971.

**Comment by atomrc** [comment]
Hey guys. 

I am still experiencing this issue with electron v`1.7.4` when calling `app.relaunch(); app.exit();`.
@CharlieHess Can you confirm that `v1.6.4` fixed the issue for you? 
(since #8971 is supposed to be in `v1.6.4`).

Here is my crash log 
[crashlog.wire.txt](https://github.com/electron/electron/files/2197939/crashlog.wire.txt)
