### ISSUE TITLE
Spawn/ENOENT thrown if the app is moved while it is open

### ISSUE THREAD

**Issue by petrbrzek** [electron/electron#8272]
We're seeing this (https://github.com/avocode/avocode/issues/1081) error occurs quite often to our users, but we are not sure how to fix it. Atom also has this issue (https://github.com/atom/atom/issues/10774). 
My question is should Electron handle this somehow or should we?

**Comment by kevinsawicki** [comment]
> My question is should Electron handle this somehow or should we?

The one in https://github.com/avocode/avocode/issues/1081 should be fixed in Electron.

**Comment by petrbrzek** [comment]
We still got this error in Sentry for the newest app version we released yesterday with Electron v1.4.12.

**Comment by petrbrzek** [comment]
@kevinsawicki Any idea what we can do to avoid this? It's still happening with the latest Electron.

**Comment by kevinsawicki** [comment]
> Any idea what we can do to avoid this?

Perhaps you could prompt to move the application to  `/Applications` on first run before opening any windows? Then relaunch it after the move completes.

I don't know of any other ways to avoid this.

> It's still happening with the latest Electron.

Yes, this is expected, no fixes have been made to address it yet.

**Comment by petrbrzek** [comment]
Ok, will try something like this https://github.com/tommoor/electron-lets-move/
