### ISSUE TITLE
BrowserWindow vibrancy is lost after reload

### ISSUE THREAD

**Issue by jmshal** [electron/electron#8310]
* Electron version: 1.4.13 (currently the latest)
* Operating system: OS X El Capitan (10.11.4)

### Expected behavior

When the web page reloads the vibrancy set on the `BrowserWindow` should remain active.

### Actual behavior

When the web page reloads (either using `[Cmd+R]`, or in my case, due to Create React App) the vibrancy which was active prior to the reload is lost.

### How to reproduce

If you use the sample code on the [Quick Start](http://electron.atom.io/docs/tutorial/quick-start/#write-your-first-electron-app) page, and replace the `BrowserWindow` creation code with the following...

```js
// ...

win = new BrowserWindow({
  width: 800,
  height: 600,
  vibrancy: 'light'
});

// ...
```

Then load up the app and press `[Cmd+R]` on your keyboard. The vibrancy is lost, and the page background goes back to white (web page default).

**Comment by jacobmarshall** [comment]
Just wanted to add - calling `BrowserWindow.setVibrancy` prior to the reload, regardless of whether it's passed the same type or a different type, does nothing either.

**Comment by Bartozzz** [comment]
Same happens when using live-reloads plugins (ex. [electron-reload](https://github.com/yan-foto/electron-reload)).

**Comment by kevinsawicki** [comment]
@gerhardberger would you have time to look into this one?

**Comment by gerhardberger** [comment]
@kevinsawicki sure, will take a look tomorrow.

**Comment by gerhardberger** [comment]
I tracked down and it turns out [this `return`](https://github.com/electron/electron/blob/df179ed28d6e84cae8de3e24594f44e59924cd52/atom/browser/native_window.cc#L580) causes the issue, but I think this is necessary, because if it doesn't return when the background is set, the background color wouldn't be preserved and it will be transparent. So I think the expected behavior in the current state is the white background, because you didn't specify the window transparency.

Though we could force the window to be transparent by default, when vibrancy is set. Thoughts?

**Comment by jacobmarshall** [comment]
> I tracked down and it turns out this return causes the issue, but I think this is necessary, because if it doesn't return when the background is set, the background color wouldn't be preserved and it will be transparent. So I think the expected behavior in the current state is the white background, because you didn't specify the window transparency.

Thanks for tracking it down @gerhardberger. I can confirm that setting the `BrowserWindow` `transparent` option fixes the current behavior.

> Though we could force the window to be transparent by default, when vibrancy is set. Thoughts?

I couldn't seem to see a documented `setTransparent` method on the `BrowserWindow`, does this mean it's currently not possible to change that property after the window has been created?

If it is possible (but there's just no current API for it), I think it would make sense to set the window to transparent if there's a vibrancy set.

**Comment by jacobmarshall** [comment]
From playing around a little bit I've noticed that setting transparent on a window with vibrancy causes the shadow to be temporarily inactive when switching from space to space on OS X. This does not happen otherwise.

**Comment by tommoor** [comment]
This appears to have been fixed, I'm able to reload multiple times without the vibrancy being lost.

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.6x. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by marcj** [comment]
This bug is still in ^4.0.5 and 5.0.0-beta.3. I tried by setting the `win.setVibrancy` in `did-finish-load`, but no luck.

3.1.4 still works, which means reloading the window does not result in a disabled vibrancy.

**Comment by marcj** [comment]
More information: the bug appears also when you open the devtool inside the window. It won't recover when you close the devtools again. If you call `win.webContents.openDevTools` before the window appeared, it works, but only if you place the devtools outside of the window. Once you close the devtools, the bug appears again.

I'm on macOS `10.14.3` using electron `4.0.5` with `vibrancy: 'appearance-based'`. 

Reproduction via https://github.com/marcj/angular-desktop-ui

```bash 
git clone git@github.com:marcj/angular-desktop-ui.git
cd angular-desktop-ui
npm run bootstrap
packages/angular-test/node_modules/.bin/npm-local-development lerna --no-watcher
cd packages/angular-test
ng build
npm run electron:build
npm run electron:start
# wait for electron app
# press CMD+r to see how it breaks
```

Before reload:

![screenshot 2019-02-23 at 19 37 42](https://user-images.githubusercontent.com/450980/53290314-82c9be80-37a2-11e9-9d3a-559b01114612.png)

After reload:

![screenshot 2019-02-23 at 19 37 47](https://user-images.githubusercontent.com/450980/53290317-88bf9f80-37a2-11e9-857e-c137131e4be8.png)

**Comment by marcj** [comment]
@sofianguy can you please reopen? It seem it worked for v3, but broke in v4 and up.

**Comment by wilg** [comment]
I can't get the `transparent: true` workaround to fix this either.

**Comment by alicerunsonfedora** [comment]
Hey folks,

I managed to get a workaround going for this on Electron 5.0.0 since I'm working on something that needs the vibrancy, too. I've discovered that, after fiddling around with settings, you need both the transparency and background color:

```
        vibrancy: systemPreferences.isDarkMode()? "ultra-dark": "light",
        transparent: true,
        backgroundColor: "#80FFFFFF"
```

I also had to add some extra checks to make sure that this only happens in macOS and nowhere else to prevent possible transparency issues with Windows/Linux.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by cramatt** [comment]
@alicerunsonfedora 's suggestion worked for a bug where the background would turn white after a webpage reload.
