### ISSUE TITLE
desktopCapturer does not include mouse cursor on Mac OSX

### ISSUE THREAD

**Issue by demian85** [electron/electron#8325]
Please see #8278 for further details.

Somehow, [this guys](https://www.hyfy.io/) created a Chrome extension that successfully captures screen including mouse on Mac and I can't figure out how they managed that.
My app uses desktopCapturer and mouse does not appear in the stream!

Is this bug related to Electron or Chromium? Why Chrome extensions API works and Electron API doesn't?

**Comment by hokein** [comment]
I can't reproduce the issue with [electron-screen-recorder](https://github.com/hokein/electron-screen-recorder). The mouse cursor is visible, you can see it  from my [recorded file](https://drive.google.com/file/d/0Bx5px5HgHtBxOFVmenVWSDRMQVE/view?usp=sharing).

**Comment by demian85** [comment]
This must be some kind of joke. I still cannot see the mouse cursor...
I've tried with and without sound, screen and window capture. Even tried Electron 1.4.12 and 1.4.13
Which OSX version are you using?

**Comment by hokein** [comment]
I'm testing with electron 1.4.12 on OS X 10.11.6.

**Comment by demian85** [comment]
Ok so the problem is OSX 10.12? Please can you confirm that?

**Comment by MarshallOfSound** [comment]
@hokein I'm on 10.12 and with `electron-screen-recorder` my cursor does not appear.  Would appear to be an issue with `10.12`.

**Comment by demian85** [comment]
At last! Could someone please tell me how to test on Chromium to report the
bug? When I try to download Chromium for Mac it redirects me to the Chrome
download page, it's confusing.
Thanks!

**Comment by MarshallOfSound** [comment]
@demian85 Chrome ~= Chromium, test in either

**Comment by demian85** [comment]
The thing is that I'll need to make an extension if I'm not mistaken, and really I don't have time for now. I'm delayed with my project because of this damn bug and I need a workaround ASAP.
Thanks for your help.

**Comment by hokein** [comment]
This is a bug of Chromium, and is fixed in chrome 55, see https://codereview.chromium.org/2350743003/. The latest Electron is based chrome 53, and we are fighting on Chrome 54 upgrade.

You could fix that by check-pick the chromium upstream fix and built your own libchromiumcontent and electron, otherwise, you need to wait until electron gets upgrade to chrome 55.

**Comment by demian85** [comment]
Great. Can you please provide a link to a guide that would help me to achieve that?
When do you estimate Electron release based on Chrome 55?

**Comment by demian85** [comment]
Hey, I can confirm this bug still exists in latest Electron v1.6 beta.
Chrome Canary v58 is patched and mouse is visible.
Can someone please help me find the patch so I can submit a PR to libchromiumcontent?
Thanks.

**Comment by zcbenz** [comment]
Closing since v1.7.x ships with Chrome 58.
