### ISSUE TITLE
win.webContents.printToPDF() - thead elements rendering issue (@electron v1.4.x)

### ISSUE THREAD

**Issue by MJones87** [electron/electron#8386]
### Environment

* Electron version: 1.4.14 (seems to be 1.4.x inclusive - therefore probably chrome version specific)
* Operating system: Windows 7 64bit (VMWare)

### Expected behavior

Using `window.webContents.printToPDF()`, should result in faithful representation of window html content in PDF.
 
### Actual behavior

There seems to be a 'painting' issue where thead elements are rendered at the top of the page, in addition to their proper place. Example - see screen capture from PDF below:

![screen shot 2017-01-11 at 13 22 10](https://cloud.githubusercontent.com/assets/5662346/21850395/50aea2b4-d802-11e6-8895-bbaf8c5aa78e.png)

This seems to occur independent of window configuration (e.g. show/hide, onscreen/offscreen, etc.).

### Workaround

The following workaround seems to work for this issue:
Apply CSS property:
`thead {
    display: table-row-group;
}`
See: http://stackoverflow.com/questions/39516885/workaround-for-chrome-53-printing-table-header-twice-on-2nd-and-later-pages

## Notes
I presume this will only be fixed by the next version that incorporates a newer chrome (>= 54). But it might be worth mentioning on the docs for the `printToPDF` method in the meantime?

**Comment by astoilkov** [comment]
This is fixed in the latest version of Electron 1.6.0. This was a Chromium issue which they resolved.

**Comment by kevinsawicki** [comment]
> This is fixed in the latest version of Electron 1.6.0. This was a Chromium issue which they resolved.

@astoilkov thanks for checking, closing this out

**Comment by frivoal** [comment]
I'm using electron via electron-pdf. I am not that familiar with npm, so I may be confused about what version I have running, but I believe it is 1.6.2, and this bug still reproduces.

**Comment by frivoal** [comment]
nevermind, that was using an old version. Upgrading fixes it.

**Comment by dropmann** [comment]
I am running the latest version 1.6.7 and i seem to be having the same issue. Any thoughts?

![image](https://cloud.githubusercontent.com/assets/11178513/26040071/278aba70-3965-11e7-807a-ae6aa70660ae.png)
