### ISSUE TITLE
DOM Element Highlighter stopped working

### ISSUE THREAD

**Issue by 45kb** [electron/electron#8876]
* Electron version: 1.6.2
* Operating system: OSX Sierra
* npm -v : 4.3.0
* node -v : 6.9.5

### Expected behavior

Be able to select elements/DOM from the DevTools inside the electron app
### Actual behavior
Unable to select elements from the DevTools extension

DevTools elements highlighter stopped working
-  i run `electron .` in app root folder
- use the OS menu option to open DevTools
- DevTools show up inside the app window
- Click to go highlight some DOM element with the element picker
- i receive this error in terminal (where i run `electron .`)  
**[3932:0309/103839.903432:ERROR:CONSOLE(3203)] "Protocol Error: the message without method: {"error":{"code":-32700,"message":"Message must be a valid JSON"}}", source: chrome-devtools://devtools/bundled/inspector.js (3203)**

- All the other DevTools features work perfectly.

### How to reproduce

1 - Add this OS menu item https://github.com/720kb/ndm/blob/master/menu.js#L91
2 - Open the app and click it

If still unable to reproduce it, just clone https://github.com/720kb/ndm.git and run `npm i && npm run mac` on MacOS. Then just go to open DevTools by the app OS menu `View -> developer -> open devtools`.

Sorry for the issue but i really wasn't able to figure out what's happening, it could be some problem with the app code but i swear i have actually no ideas, any advice is appreciated!

Thanks

**Comment by 45kb** [comment]
fixed i don't know how, i had problem to fix on my package json cause of deprecated items such as "directories" in the root which had to go inside "build" field.

sorry and thanks anyway.

**Comment by TIM0N** [comment]
I have the same Problem. Just updated electron again and noticed that its still not solved. So im happy to see the issue is tracked now. Can't work without inspector running so i always switch back to previous electron version for developing and hope this will be fixed soon.

**Comment by 45kb** [comment]
@TIM0N Do you experience this problem also when you install your electron app? Because when i build and install it everything seems to work... weird..

**Comment by TIM0N** [comment]
Yes it's  like you described. It's working after i build it.  But running from command line with v1.6.2 throws this error.

**Comment by futjikato** [comment]
Have the same issue here. Developing on linux and OSX and this happens only on OSX for me. So might be something platform specific

**Comment by futjikato** [comment]
Just a heads up. Updated to 1.6.3.
Issue is still present. No change

**Comment by phplabser** [comment]
Hi! Have the sam issue.

- macOS sierra
- electron 1.6.3
- node 7.7.2 
- npm 4.1.2

When I run `electron .` in terminal and then I am trying to inspect some elements always receive error as below: 

`[38951:0314/143735.852491:ERROR:CONSOLE(3203)] "Protocol Error: the message without method: {"error":{"code":-32700,"message":"Message must be a valid JSON"}}", source: chrome-devtools://devtools/bundled/inspector.js (3203)`

**Comment by JoschuaSchneider** [comment]
Got the same issue.

 - macOS Sierra
 - electron 1.6.2
 - node 7.6.0
 - npm 4.1.2

The basic setup is based on `electron-react-boilerplate`, I'm not 100% sure whether the issue appeared after an `yarn upgrade electron` or just started happening.

Same error:
`[34466:0316/121026.995527:ERROR:CONSOLE(3203)] "Protocol Error: the message without method: {"error":{"code":-32700,"message":"Message must be a valid JSON"}}", source: chrome-devtools://devtools/bundled/inspector.js (3203)`

**Comment by kevinsawicki** [comment]
> If still unable to reproduce it, just clone https://github.com/720kb/ndm.git and run npm i && npm run mac on MacOS. Then just go to open devtools from the OS menu.

I tried this and it appeared to work for me, am I missing something? Here is a screencap:

![dom-highlight](https://cloud.githubusercontent.com/assets/671378/24018354/ced33e04-0a50-11e7-8a3f-c942cd45ac90.gif)

**Comment by 45kb** [comment]
@kevinsawicki so weird 😄 
I really don't know what is causing this but also re-cloning the repo doesn't fix it for me unfortunately. 

I will try on a clean VM and let you know, do you know if the npm version could be involved in any way? I will try maybe with some different setups i really have no idea what this could depend on, sorry for that.

**Comment by kevinsawicki** [comment]
> I will try on a clean VM and let you know, do you know if the npm version could be involved in any way?

I don't think it is.

**Comment by 45kb** [comment]
@kevinsawicki on a linux VM i see it works.
On mac  i downgraded to an older electron version and it works (i tried with 1.3.10).

 Really don't know how to help on this, if you want me to do some specific test let me know.

**Comment by kevinsawicki** [comment]
@45kb do you have any dev tools extensions installed in Electron?

**Comment by 45kb** [comment]
none @kevinsawicki but if you know how to check this i do, i never installed anything really...

**Comment by kevinsawicki** [comment]
> but if you know how to check this for sure i do, i never installed anything really...

From the dev tools console:

```js
Object.keys(require('electron').remote.BrowserWindow.getDevToolsExtensions())
```

**Comment by correnson** [comment]
Got exactly the same behaviour starting _after_ electron 1.4.15.

Notice the element selection is blocked in DevTools because an error is raised about an incorrectly formatted JSON message somewhere. Although, `yarn` (an `npm` clone) reports an inconsistent version constraint on package `ajv`, which is actually a JSON validator...

```
$ yarn install
...
warning "ajv-keywords@2.0.1-beta.1" has incorrect peer dependency "ajv@>=5.0.3-beta.0".
...
$ yarn why acv-keywords
...
info This module exists because "webpack" depends on it.
...
$ yarn list ajv
...
├─ ajv@4.11.5
...
└─ electron-builder@15.5.1
│  └─ ajv@5.0.4-beta.0
...
$ yarn why ajv
...
info Has been hoisted to "ajv"
info Reasons this module exists
   - "webpack" depends on it
   - "electron#electron-download#nugget#request#har-validator" depends on it
...
```

**Comment by nicolas-van** [comment]
I have the same problem on Mac OS X with electron 1.4.15 and electron 1.6.4 . Strange thing is that it just appeared one day without reason. I tried to update electron to latest version (1.6.4) but nothing changed. Maybe a Mac OS X update that changed something ?

**Comment by dotEuphoria** [comment]
Same Issue on

- OSX Sierra ( Windows working perfectly ) 
- Since Electron Version 1.4.5 ( Still not working on 1.6.4 )

**Comment by MaThGo** [comment]
+1

OS: OSX Sierra 10.12.3
Electron Version: 1.6.4 (1.4.13 works, dunno about versions in between)

**Comment by loramt** [comment]
I noticed that if i switch my OSX system language from Italian to English the problem goes away. Maybe it's a problem with non-english versions? I'm on OSX Sierra 10.12.4, Electron 1.6.2

**Comment by 45kb** [comment]
@kevinsawicki i really think @loramt is right, i also switched my Os language from ita to english and now it works perfectly.

**Comment by popod** [comment]
Same for me. With macOS Sierra in French it doesn't work. If I switch to english it works fine !

**Comment by MaThGo** [comment]
I'll try this asap, I dont have my machine at hand right now, but system
language is german, so thats probably it.

Am 01.04.2017 8:53 nachm. schrieb "popod" <notifications@github.com>:

**Comment by nicolas-van** [comment]
I'm usually using French for my system. I tried to switch to English but the problem still occurs (didn't tried to restart the system, tough)

**Comment by iw2rmb** [comment]
Latest nwjs — same error and behaviour .

**Comment by MaThGo** [comment]
Tried it, setting System language to Englisch (UK/US, doesn't matter) fixes it.

Note: You've to restart your shell/Terminal to make it work.

**Comment by nicolas-van** [comment]
Yes, by restarting Terminal it works fine. Thanks for the workaround.

**Comment by folkrav** [comment]
@MaThGo My system language was already on English, but Region was on `French - Canada`. Switching it to `United States` solved the issue. Thanks!

**Comment by lostdesign** [comment]
Thanks for the workaround. Even if i'd like to see that fixed soon 😄

**Comment by pokusew** [comment]
Hi everyone,

I figured out another, possibly better workaround.
I have the same problem on OS X (with Czech language and Czech Republic region) with Electron 1.6.5. Changing the locale to English fixes it.

**But if you don't want to change the system locale, you can do this:**
If you use Apple Terminal, in Preferences -> Profiles, on Advanced tab of your default profile, in International section (at the bottom), there is an option called _Set locale environment variables on startup_. **Uncheck the option and restart the terminal.**

Here is a screenshot of setting the option (in Czech locale):
<img width="673" alt="cs-terminal-preferences-fix" src="https://cloud.githubusercontent.com/assets/5508040/25314093/5bcba54e-283d-11e7-88f9-4da98b742364.png">

Hope it helps.

**Comment by lostdesign** [comment]
@pokusew worked for me! Thanks a lot. It is 'Set the local environment variable at startup' in english.

**Comment by oThams** [comment]
Even simpler workaround: simply prefix your command with "LANG=en_US.UTF-8"

**Comment by kevinsawicki** [comment]
I could reproduce this in standalone chrome when using a `LANG` value of `de_DE.UTF-8`, reported upstream at https://bugs.chromium.org/p/chromium/issues/detail?id=715313

**Comment by kevinsawicki** [comment]
This has been fixed upstream via https://codereview.chromium.org/2843223005/

**Comment by kevinsawicki** [comment]
This will be fixed in the next Electron release, 1.7.2

**Comment by tangb** [comment]
I'm running version 1.7.6 (chrome 58.0.3029.110) and I'm still facing the same problem.
Prefixing with LANG=en_US.UTF-8 like explained fix the problem but for me it's only a workaround.

I'm running MacOs 10.11.6 with French install.
The problem do not appear running the same application under Linux64/32 and Windows64.
