### ISSUE TITLE
Can't make Materialize CSS to Work

### ISSUE THREAD

**Issue by orien2k** [electron/electron#8964]
Hello,

I have tried different ways searched the whole internet.
I can't find a way to use Materialize CSS on Electron.

*Electron version: All
*Operating system: W10

### Expected behavior

Materialize should work.

### Actual behavior

It doesn't work.

**Comment by MarshallOfSound** [comment]
As materialzecss uses jQuery you need to initialize your browser window with nodeIntegration disabled

**Comment by orien2k** [comment]
And what is the disadvantage of doing that?

**Comment by MarshallOfSound** [comment]
I mean, you lose `nodeIntegration` in anything that isn't a preload script.

The alternative is to do something like `window.$ = window.jQuery = require('jquery')`

I take it your issue is solved?

**Comment by orien2k** [comment]
I have used that line of code but the problem still continues.
But i will try other way. Gonna try and remove jquery from materialize.

**Comment by natearmagost** [comment]
materialize.js tries to require('hammerjs'). That will throw an error.

If the nodeIntegration thing isn't working, you could do something like below. It works for me...

```html
<script>
  // You can also require other files to run in this process
  require('./renderer.js')
</script>
<script type="text/javascript" src="node_modules/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="node_modules/hammerjs/hammer.min.js"></script>
<script type="text/javascript" src="node_modules/materialize-css/dist/js/materialize.js"></script>
````

**Comment by kevinsawicki** [comment]
@natearmagost thanks for the solution, closing this out 👍
