### ISSUE TITLE
Crashes on webview.loadURL()

### ISSUE THREAD

**Issue by S--Minecraft** [electron/electron#9231]
* Electron version: 1.6.5
* Operating system: Windows 10 64bit

### Actual behavior

Crashes

### How to reproduce
```
git clone https://github.com/S--Minecraft/Electron-Webview-Bug.git
npm install
npm start
```

1. click "change" button
1. click "hide" button
1. click "change" button

https://github.com/S--Minecraft/Electron-Webview-Bug

**Comment by S--Minecraft** [comment]
It happens with Electron **1.6.7**
It doesnt happen when using **1.6.2**

**Comment by kevinsawicki** [comment]
The stack for this crash is:


```
electron.exe!content::WebContentsViewGuest::CreateViewForWidget(class content::RenderWidgetHost *,bool)	Unknown
electron.exe!content::WebContentsImpl::CreateRenderWidgetHostViewForRenderManager(class content::RenderViewHost *)	Unknown
electron.exe!content::WebContentsImpl::CreateRenderViewForRenderManager(class content::RenderViewHost *,int,int,struct content::FrameReplicationState const &)	Unknown
electron.exe!content::RenderFrameHostManager::InitRenderView(class content::RenderViewHostImpl *,class content::RenderFrameProxyHost *)	Unknown
electron.exe!content::RenderFrameHostManager::CreateRenderFrame(class content::SiteInstance *,bool,int *)	Unknown
electron.exe!content::RenderFrameHostManager::CreatePendingRenderFrameHost(class content::SiteInstance *,class content::SiteInstance *)	Unknown
electron.exe!content::RenderFrameHostManager::UpdateStateForNavigate(class GURL const &,class content::SiteInstance *,class content::SiteInstance *,enum ui::PageTransition,bool,bool,struct content::GlobalRequestID const &,int,bool)	Unknown
electron.exe!content::RenderFrameHostManager::Navigate(class GURL const &,class content::FrameNavigationEntry const &,class content::NavigationEntryImpl const &,bool)	Unknown
electron.exe!content::NavigatorImpl::NavigateToEntry(class content::FrameTreeNode *,class content::FrameNavigationEntry const &,class content::NavigationEntryImpl const &,enum content::ReloadType,bool,bool,bool,class scoped_refptr<class content::ResourceRequestBodyImpl> const &)	Unknown
electron.exe!content::NavigatorImpl::NavigateToPendingEntry(class content::FrameTreeNode *,class content::FrameNavigationEntry const &,enum content::ReloadType,bool)	Unknown
electron.exe!content::NavigationControllerImpl::NavigateToPendingEntryInternal(enum content::ReloadType)	Unknown
electron.exe!content::NavigationControllerImpl::NavigateToPendingEntry(enum content::ReloadType)	Unknown
electron.exe!content::NavigationControllerImpl::LoadEntry(class std::unique_ptr<class content::NavigationEntryImpl,struct std::default_delete<class content::NavigationEntryImpl> >)	Unknown
electron.exe!content::NavigationControllerImpl::LoadURLWithParams(struct content::NavigationController::LoadURLParams const &)	Unknown
electron.exe!atom::api::WebContents::LoadURL(const GURL & url, const mate::Dictionary & options) Line 1014	C++
```

@deepak1556 anything jump out to you on this one?

**Comment by kevinsawicki** [comment]
@deepak1556 think it might be related to https://github.com/electron/electron/pull/8724 ?

**Comment by alexk111** [comment]
Hope this will help to reproduce the issue https://forum.freeter.io/topic/168/unexpected-crashes Started crashing after 1.6.2 (1.6.5 or 1.6.6).

**Comment by lukeapage** [comment]
I had a similiar bug and it seems fixed in 1.7.2

**Comment by mkazlauskas** [comment]
Still happening using 1.7.3

Doesn't happen on Linux, only on Windows

**Comment by ferreus** [comment]
It looks like when "hidden" class is removed from webview, it is not become ready immediately on windows.
if i add a small timeout, for the second change click, as in:
1.   $webview.classList.remove("hidden");
2.     setTimeout(() => {
      $webview.loadURL(LINKS[1]);
    },100);

Then, there is no crash.

**Comment by mkazlauskas** [comment]
Not sure if my issue is the same issue, but I'm getting a similar stacktrace. I'm only getting the error when I change src or loadURL the 2nd time (after it has loaded some page already).

**Comment by S--Minecraft** [comment]
It happened in 1.7.3, too.

@ferreus 's code worked with mine. (`setTimeout(func, 0)` was also acceptable)
So it seems calling `webview.loadURL()` synchronously occurs the crash.

**Comment by ferreus** [comment]
I tracked down this crash to https://chromium.googlesource.com/experimental/chromium/src/+/58.0.3029.110/content/browser/browser_plugin/browser_plugin_guest.h#153

WebContentsImpl* embedder_web_contents() const {
    return attached_ ? owner_web_contents_ : nullptr;
}
Which results in null pointer access on LoadURL when the view is hidden (Because it's detached).
This is actually not a matter of race condition. As it's simply enough to hide the webview, then issue LoadURL to crash it.

This will avoid the crash by simply refusing to navigate when the view is not attached.

**Comment by alexey-sh** [comment]
I got the same. The webview was hidden via css.
