### ISSUE TITLE
Flicker with high DPI resolutions

### ISSUE THREAD

**Issue by bpasero** [electron/electron#9413]
* Electron version: >= 1.6.x
* Operating system: macOS

Electron applications on macOS have a chance to exhibit very bad flickering depending on the environment:
* OS is low on memory
* lots of pixels are being drawn and updated (e.g. VS Code and scrolling the editor)
* high DPI resolutions (e.g. external 4k or 5k monitor)

This is tracking Chromes bug https://bugs.chromium.org/p/chromium/issues/detail?id=719938 (which got merged into: https://bugs.chromium.org/p/chromium/issues/detail?id=631485). It reproduces in Chrome Stable 58. It does not reproduce in Electron 1.4.x.

Some animations how this looks like for VS Code:

![flicker1](https://cloud.githubusercontent.com/assets/900690/25853213/4e5e53f2-34cc-11e7-85a4-e2d57da4a468.gif)
![flicker2](https://cloud.githubusercontent.com/assets/900690/25853212/4e5ddb0c-34cc-11e7-8f25-286daf1d9a0c.gif)

**Comment by bpasero** [comment]
It looks like a patch landed in Chrome for this: https://chromium.googlesource.com/chromium/src.git/+/0375ae80fe1d94e9d0fc175ce4312d1b3a6bc168

Could this (simple looking) patch be backported on a 1.7.x release? @cifratila fyi

**Comment by MarshallOfSound** [comment]
If this is fixed can this be closed @jkleinsc

**Comment by bpasero** [comment]
Thanks a lot for backporting this fix I am getting confirmation from some insiders testers that the flickering is indeed fixed 👍

**Comment by jkleinsc** [comment]
Closing as this was fixed via #10390

**Comment by happypoulp** [comment]
I am also reproducing this flickering issue in Electron 2.0.2. Since Electron 2.0.2 embeds Chromium 61 I also tried in "official" Chrome 61 and the issue is also present. I do not reproduce it in Chrome 62 and above.

**Comment by pshirshov** [comment]
Still happens. VsCode and other electron apps are flickering on Mojave.

**Comment by xaviervilla** [comment]
I've consistently had this identical issue. List of apps effected for me:
Chrome, Opera, Chromium, VSCode, Atom, Signal. (Probably others I can't remember). It's really annoying and I have had this problem since I switched to linux in Janurary, and it happens on every version of linux I've tried. I have an i5 Surface Book w/ 8GB ram, (non-performance base/no dedicated GPU). My surface book uses 3,000x2,000 resolution. 

My OS of choice right now is Ubuntu 16.04. I've tried different drivers, different kernels, etc. There are things that I can do to minimize this issue like going in and changing the chromium flags to --disable-gpu, or disabling hardware acceleration, but then I notice my fans kick on because of over stressing, and my battery drains much faster so I'd rather deal with the constant flickering every second.

I don't know what logs would be necessary to help with debugging but I'm happy to provide whatever.

**Comment by schnittchen** [comment]
I experience the same with Rambox v0.6.1-1 (and older), which seems to use Electron 2.0.8 (https://github.com/ramboxapp/community-edition/blob/0.6.1/package.json#L176), on Linux.

The severity of the problem depends on the website displayed in Rambox. Trello is almost not usable. When moving the mouse, there is flickering, but there are also severe mispaints such that user interface elements are not visible.

I have a 3840x2160 screen resolution, scaled at 2x.

The problem goes away when I either
* choose half the resolution, scaled at 1x
* launch Rambox with "Disable Hardware Accelleration"

I am using the Intel HD 530 (Skylake GT2) onboard card with Xorg.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by bpasero** [comment]
This actually came back (probably for other reasons) up to Electron 6: https://github.com/microsoft/vscode/issues/74098

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by nkuehn** [comment]
Did someone ever open a new issue with the same topic since the arrogant triage bot closed this?   

The [matching Issue in the VSCode repo](https://github.com/microsoft/vscode/issues/74098) still sees a constant inflow of confirmations that the problem occurs also in current versions, is labeled "urgent" and "upstream" but nothing seems to happen.

**Comment by ioridev** [comment]
I think this issue still exists.
I am having this problem with Discord and Vscode.

https://github.com/microsoft/vscode/issues/74098#issuecomment-1236091984
