### ISSUE TITLE
"backgroundThrottling: false" no longer affects requestAnimationFrame() in background applications

### ISSUE THREAD

**Issue by stickywes** [electron/electron#9567]
* Electron version: 1.5.0 thru 1.7.1
* Operating system: Mac OS Sierra 10.12.4, [El Capitan 10.11.6](https://github.com/electron/electron/issues/9567#issuecomment-318158844)

### Expected behavior
Disabling background throttling should prevent the slowdowns/pausing of both animation frames and intervals/timeouts when the window is in the background.

For instance, 
```  // Create the browser window.
  mainWindow = new BrowserWindow({
   ...
    webPreferences: {
      pageVisibility: true,
      backgroundThrottling: false,
    },
    ...
  })
```
... should allow RAF to run without getting stopped or otherwise throttled when the window is in the background (minimized or completely obscured by other windows).  Behavior specific to RAF on this issue was added in 0.37.6 (https://github.com/electron/electron/issues/4925)

### Actual behavior

Behavior that depends on RAF calls will slow to a crawl when the window becomes obscured by other windows or is otherwise made a "background" window, behaving no differently whether `backgroundThrottling` is set to true or false.  It reverts to normal behavior as soon as it becomes a foreground window again.

### How to reproduce
Easiest to just use the [test repo](https://github.com/stickywes/test-electron-background-throttle) I put together.
```
git clone https://github.com/stickywes/test-electron-background-throttle.git
npm install
npm start
```

#### Use an older version of electron.
Versions below 1.5.0, such as 1.4.16, do not have this issue.  The regression on this issue appears to begin with 1.5.0 onward.

#### Use setInterval()
[westoncbb says](https://github.com/electron/electron/issues/9567#issuecomment-312919665): "setInterval() does work in the background with backgroundThrottling: false —so that may be a workaround for some."

**Comment by LukePulverenti** [comment]
@stickywes do you mean to say that behavior depending on RAF will slow to a crawl even when the application is running in the foreground? Or is this issue only experienced when in the background? Thanks.

**Comment by stickywes** [comment]
Things are great if it's in the foreground.  This issue only arises when the application window becomes obscured or minimized.  RAF calls resume their normal rate as soon as the application is visible again.

I've updated the issue description for clarity.

**Comment by georgewoo-nsuslab** [comment]
Are there any progress in this issue? I'm facing exactly the same problem in
electron version: 1.6.10
OS: macOS Sierra 10.12.5

Even if the backgroundThrottling option of BrowserWindow was set to false, animation stops when the application window runs in the background. On the other hand, this seems to work fine in Windows 10.

**Comment by westoncb** [comment]
Same problem here: 

I have tried the webPreferences option 'backgroundThrottling: false', app.commandLine.appendSwitch('disable-renderer-backgrounding'),
and win.setMinimizable(true) —in all cases requestAnimationFrame stops getting called when the window is inactive.

electron version: 1.6.11
OS: macOS El Capitan 10.11.6

**Comment by neurosnap** [comment]
Any updates on this issue?

**Comment by StevenEBarbaro** [comment]
Can't reproduce on Windows 8
**Can** reproduce on El Capitan 10.11.6

**Comment by stephenou** [comment]
After doing some research:

In commit https://github.com/electron/electron/commit/497f5a11994a1c9858afd6ab04ea3ae9b3b77b34 (a part of v1.5.0), [osr_render_widget_host_view_mac.mm](https://github.com/electron/electron/blob/497f5a11994a1c9858afd6ab04ea3ae9b3b77b34/atom/browser/osr/osr_render_widget_host_view_mac.mm) was changed to reflect Chromium API changes. It could be related.

[This](This is the associated Chromium change: https://chromium.googlesource.com/experimental/chromium/src/+/b62b78229e838b0140af7973e83ada9fcce28a19%5E%21/) is the associated Chromium change.

Additionally, the member variable `disable_hidden_` set in [here](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_web_contents.cc#L726) is not found in the corresponding [Chromium class] (https://chromium.googlesource.com/experimental/chromium/src/+/master/content/browser/renderer_host/render_widget_host_impl.cc) or any class it inherits from, which is a little mind boggling.

**Comment by stickywes** [comment]
Updating the description to call out known workarounds, since that was kind of buried in my original description.  Also adding westoncb's setInterval() comment.

**Comment by prixe** [comment]
Any news of this issue? I currently still using electron 1.4.x but my user encounter some cpu/ram problem with webGL, wich are better managed in the 1.7/8. 
However my app has to still working during a workspace change or when it is minimized, i can't sacrifice this feature for mac users.

I have tried :
```js
app.commandLine.appendSwitch("disable-renderer-backgrounding");
app.commandLine.appendSwitch("disable-background-timer-throttling");
```
without success.

It's really annoying and this regression was introduced a long time ago. So if you can fix it ❤️

**Comment by REBELinBLUE** [comment]
Any news on a fix for this issue?

**Comment by nornagon** [comment]
Confirmed to reproduce on 2.0.x and 3.0.x, and `disable-background-timer-throttling` doesn't work around the issue.

**Comment by nornagon** [comment]
`requestAnimationFrame` is designed to run animations on screen, and as such is heavily linked to on-screen behaviour in chromium code (e.g. being tied to the refresh rate of the display that the frame is currently displayed on). If you need timers to run unthrottled in the background, use `setTimeout` or `setInterval`, with the `disable-background-timer-throttling` switch. `requestAnimationFrame` is not a timer.

**Comment by stickywes** [comment]
So this wasn't a regression but a deliberate reversal of a previous decision?

**Comment by nornagon** [comment]
My understanding is that RAF was always designed to be an API that was for _requesting animation frames_, i.e. for timers that needed to be synchronized with the display. I'm not aware of any effort on part of Chromium to deliberately make RAF fire when there's no animation frame to be shown.

**Comment by stickywes** [comment]
Just to re-iterate, being able to disable the RAF throttle was added to Electron at one point.
https://github.com/electron/electron/issues/4925

Certainly, throttling RAF 
I'm using Chromium to render frames.  Those frames are sent via a socket to a LED display.

**Comment by nornagon** [comment]
Ah, it looks like in #4925, the intention was that `backgroundThrottling: false` would also disable throttling of RAF. It seems that Chromium's implementation of RAF has changed since then, and the patch that Electron applied no longer has the desired effect.

**Comment by nornagon** [comment]
It also seems that the docs at `docs/api/browser-window.md` claim that the `backgroundThrottling` setting affects animations, which is no longer the case.

**Comment by stickywes** [comment]
I see, so it's a Chromium-side change.

Well, that's too bad but not completely unexpected. :/

My use case for this using electron to render animations and visualizations to an HTML Canvas and then sending those rasterized bytes to LED displays [like this clock](https://player.vimeo.com/video/23660159).  Using requestAnimationFrame() seemed like the natural API to use in this case; setInterval() with extremely interval times feels kinda "hacky."

**Comment by nornagon** [comment]
setInterval is an appropriate function to use for that use case; there's nothing tying your LED display to the refresh rate of your monitor. `rAF` is for when you want to be embedded in the browser's paint cycle, which is irrelevant for your use case.

**Comment by pedromcunha** [comment]
Hey, although @stickywes case may be more on the fringe I think my case is actually legitimate. I'm using captureStream to send a canvas through a WebRTC peer connection, which is blending some videos together to send it to the other peers. Previously I used backgroundThrottling set to false and a RAF loop to update the canvas. This no longer works and breaks my implementation. I would really prefer not to use an interval as it wouldn't match the display refresh rate. Is there any alternative here?

**Comment by ptrwtts** [comment]
I tried switching to setInterval, and although the function continues to run in the background, the rendering and animations do not. So as has been mentioned above, use cases that involve drawing to a canvas and then capturing the output (e.g. live streaming after applying filters/masks) pause when the window is moved to the background. I tried every combination of flags, setInterval vs rAF, etc and nothing would get it to work.

This was an issue in the past, and successfully fixed (#4925). Hopefully there's a way to fix it again.

**Comment by maxfadeev** [comment]
Has anyone tried this in 4.x.x ? It looks like nothing has changed 😞.

**Comment by intrueder** [comment]
Nothing helps in 4.0.2, even `webContents.setBackgroundThrottling(false)`

**Comment by shlajin** [comment]
My app captures animation from screen which is based on RAF, like a screen recording thingy. User may want to start capturing the video and then alt+tab to do other tasks. This "optimization" makes this virtually impossible now.

**Comment by 2xAA** [comment]
@nornagon `setTimeout` isn't a good enough workaround for this. `requestAnimationFrame` is designed to sync to screen refresh rates (source: [article from 2012](https://developers.google.com/web/updates/2012/05/requestAnimationFrame-API-now-with-sub-millisecond-precision)). `setTimeout` does not have this ability.

For applications which deal with realtime graphic rendering or @pedromcunha's WebRTC case, `setTimeout` is not "appropriate" and that suggestion completely nerfs the point of having rAF in the first place.

I'm in the process of porting my application [modV](https://github.com/vcync/modV) from NW.js to Electron - I was really enjoying the Electron experience until I encountered this road bump.

My application runs an rAF loop in the main Window and draws to Canvas Elements in child Windows. If the main Window becomes obscured on macOS the main rAF loop is halted and output is not drawn to the child Windows.

Two potential solutions which are a little less than ideal (may help others):
* Making the child Windows have their own rAF loop
  * Impractical in my use-case because of the variable nature of what the child Windows are drawing. I'd have to maintain a loop in each Window and instances of the draw code for each also

* Moving the draw loop to a Worker then using OffscreenCanvas to keep the loop running regardless of Window visibility
  * This is a solution, though one which is much further down the line for me

As you've said this was intended behaviour, would this be better off as a feature request (NW.js has a `--disable-raf-throttling` flag, for example) rather than an issue?

**Comment by maxfadeev** [comment]
My team run into the same problem and decided to [build](https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md) Electron with customisation. It happened to be quite simple though(but it requires much time and free space on disk). 
NW.js came to the rescue with its --disable-raf-throttling in the chromium's fork. We [find all places](https://github.com/nwjs/chromium.src/search?q=kDisableRAFThrottling&unscoped_q=kDisableRAFThrottling) where kDisableRAFThrottling is used and applied a similar solution to the chromium fetched using depot_tools from the build instruction. Not perfect solution for sure but we had to.

**Comment by 2xAA** [comment]
@maxfadeev Is your modification something that could be merged into Electron as a PR? This feature would be invaluable

**Comment by 2xAA** [comment]
Thanks @maxfadeev - I'm gonna give this a go.
I really need rAF in the background right now, until I can implement using OffscreenCanvas for rAF in a Worker instead.

Would the same approach be PR-able into Electron?
This seems like a sought-after feature.

**Comment by maxfadeev** [comment]
As far as I know that is not possible now since Electron doesn't use a forked chromium version. The problem is in chromium itself, unfortunately.

**Comment by 2xAA** [comment]
Hm. Just looking into this and this seems to be the same compositor line that the NW.js modifications prevent for macOS.

I'll see if I can modify what is needed here.

https://github.com/electron/electron/blob/590454423599b5be7c6afd5076b0340d886808d2/atom/browser/osr/osr_render_widget_host_view.cc#L502

**Comment by Littlebigdondon** [comment]
@2xAA Did that end up fixing the problem? I'm going to have to tackle this problem in the next few days, so just wondering if that flag in the browser_compositor is all that needs to be changed.

**Comment by 2xAA** [comment]
@Littlebigdondon Not sure, I never got round to making a patch file.

Will need to fork Electron, create the patch, push that to the fork and then follow the build instructions but pull from your fork instead.

I got busy between then and now with moving house so I haven't had time to properly check this.

**Comment by bluebrown** [comment]
Why is every second feature of electron not working properly? Its so annoying. Better not read the docs and get exited about features which don't even exist.

And I don't read any statement that the team is intending to fix this.

**Comment by peererror** [comment]
is this problem fixed ... I am also facing this in 6.1.11 I am capturing my app screen when its minimize the animation paused any way to fix this

**Comment by ericblade** [comment]
Looks like this is still a problem in the modern era, i'm wrapping a web app that i don't have control over, and sound and animations are getting significantly throttled even with the command line switches in here and the backgroundThrottling: false setting in the web options.  I can't say for sure the app is using requestAnimationFrame or some other timer that is being throttled still, but... looks like RAF to me.

**Comment by nuthinking** [comment]
I'm using 9.4.3 and `backgroundThrottling` seems to be working fine for me.

**Comment by WesWedding** [comment]
Future commenters:  please provide a sandbox or some other source code that can allow someone to reproduce this issue.  Or maybe create a whole new Issue.

As far as I can tell with my testing, the original issue is very much resolved.  I have tested a few random versions of Electron and any version above 5.x has been fine.  When I update my demo repo to support Electron API changes and`backgroundThrottling` is set to true, it slows down.  When it's set to false, it doesn't.

**Comment by WesWedding** [comment]
I pushed several updates and new releases of the demo project today, in order to support more modern Electron APIs since the original issue was posted.

I incremented major versions (eg. `npm install --save-dev electron@v^7.0.0`) several steps and tested at each step, and the issue appears to have stopped at electron@^8.0.0 and above.  I am not able to reproduce the issue from that point on (and when throttling is enabled, I get the expected error result).

**Comment by iamisti** [comment]
It's still not fixed! Using latest electron. This issue is so annoying. Aslo the lack of ownership of all the issues electron has. Literally every second feature has issues...

**Comment by WesWedding** [comment]
One step toward a solution would be to provide an example that demonstrates the issue, and provide details like the Operating System and OS version you're using.

**Comment by jrj2211** [comment]
Also need this. I have an older app thats on Electron 9.0.3 and disabling background throttling just fine. Now I've started a new app and version 14.X doesn't work.

We do robotics and our application streams positional data to our controller. When the app goes into the background this means our robotic kinematics stops even though in previous electron versions it would continue running. We cannot have it stop just because the window becomes hidden. Sticking to electron 9.X until this is resolved. 

I always used the app.commandLine.appendSwitch('disable-renderer-backgrounding') but the backgroundThrottling flag also does not work for me. Can this issue get reopened as its not fixed?

OS: Windows 10 (19043)

**Comment by ericblade** [comment]
@jrj2211 might be worth opening a new issue, this one is 4.5 years old now, but you might be well equipped to provide a proper test case that could prove out that it's broken (or at least find out what is needed to make the test case work properly in modern)

if you do, make sure you tag back here :)

**Comment by jrj2211** [comment]
I spoke too soon, it is in fact working for me on v14.X. I forgot that changing main.js requires a full app restart and not just a page refresh... 

The command line option for background rendering still exists in Chrome. I was looking through the available command line arguments and found another that might be useful for anyone that is having throttling issues: disable-backgrounding-occluded-windows. Here's all the options I'm now using:

app.commandLine.appendSwitch('disable-renderer-backgrounding');
app.commandLine.appendSwitch('disable-background-timer-throttling');
app.commandLine.appendSwitch('disable-backgrounding-occluded-windows');

**Comment by jrj2211** [comment]
@ericblade I'm working on creating test apps and I'll start a new issue if I get a better idea of whats going on. I am perplexed though because I can't get consistent results. I created a fresh electron project with just this:

**renderer.js**
```
function update() {
  requestAnimationFrame(() => {
    update();
    console.log('update');
  });
}
update();
```

**main.js**
```
app.commandLine.appendSwitch('disable-renderer-backgrounding');
app.commandLine.appendSwitch('disable-background-timer-throttling');
app.commandLine.appendSwitch('disable-backgrounding-occluded-windows');

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    ...
    webPreferences: {
      backgroundThrottling: false,
    },
  });
```

I started with Electron V14 and it was getting throttled. I've stepped back through each version of electron down to V7 at which point it stopped throttling. I changed back to V12 and V14, and its no longer throttling there either. No code changes, just did "npm install electron@12.0.0" to change versions. I'm printing out the electron version on start to ensure its actually switching electron versions. Now I can't get it to throttle in my test example... I do not have electron installed globally so not sure whats going on there. I did also see a few times where the loop was just reduced speed (once per second) and sometimes it wouldn't start the loop until the window was visible but then was fine to minimize.

I'm also trying this with a fresh electron-forge app and the same settings/code as above. Turns out I can't get it to stop throttling with any version of electron. I believe this might be an issue with electron forge and not electron though as I can get it to work with just a simple electron app (despite being inconsistent). My actual app is using electron-forge so I'm most interested in figuring out if these are separate issues. 

There's definitely more testing to be done here, but I just wanted to log my current finding as I need to move onto other stuff. Using a normal setInterval loop will work for me for the time being.

**Comment by ericblade** [comment]
> a normal setInterval loop will work for me for the time being.

Aren't Interval timers also throttled by Chrome?  or is that something that I remember from one of the many customized versions i've worked on in the past...

**Comment by iamisti** [comment]
finally some happenings here. Looking forward the solution. It's been years and it's still not working properly. For me it's on windows 10, i have an invisible window that is getting throttled as soon as the gaming application is in focus.

**Comment by James-AltaML** [comment]
[https://developer.chrome.com/blog/timer-throttling-in-chrome-88/#javascript-timers](url)

I am not sure if this will resolve the issues with requestAnimationFrame, but for setInterval the below worked.
A bunch of code omitted, but this worked for our project.  I explicitly set throttling to false on Main and all Render processes.   
Built as Windows 10 executable 

package.json
``` 
"devDependencies": {
    "electron": "^13.0.0",
  } 
```

background.ts
```
app.commandLine.appendSwitch("disable-background-timer-throttling");
```

```
function createWindow(): BrowserWindow {
  const mainWin = new BrowserWindow({
    webPreferences: {
      backgroundThrottling: false,
    },
  });

    createProtocol("app");
    mainWin.webContents.setBackgroundThrottling(false);

  return mainWin;
}
```
[https://www.electronjs.org/docs/latest/api/browser-window#page-visibility](url)
It seems that any property/function that affects visibility will enable background throttling.
At the time of posting this, I haven't had time to fully test whether all the functions called / properties set affect throttling, so I may have went overboard. 
```
function createWorkerWindows(title: string): BrowserWindow {
  const workerWindow = new BrowserWindow({
    webPreferences: {
      backgroundThrottling: false,
    },
  });

    createProtocol("app");
    workerWindow.hide();
    workerWindow.minimize();
    workerWindow.setMovable(false);
    workerWindow.setFocusable(false);
    workerWindow.setEnabled(false);
    //the above seem to set throttling to true so call this last to set back to false
    workerWindow.webContents.setBackgroundThrottling(false);

  return workerWindow;
}
```

**Comment by Aaqu** [comment]
I have similar problem, steps:
 - first open app app work perfectly (fiddle start)
 - close app (fiddle stop)
 - again open (fiddle start)
 - app lagging, dev tools lagging
 - minimize to bar, and open
 - app work

Platform:
Electron 16.0.7
MacOs Monterey
 
I write simple fiddle
https://gist.github.com/f813a71d185cf5b0f16baf4155c9f74d

App works when I add to BrowserWindow ```alwaysOnTop: true```, it is not a good solution

main.js
```
const {app, BrowserWindow} = require('electron')

function createWindow () {

  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  })

  mainWindow.loadFile('index.html')

  mainWindow.webContents.openDevTools()
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'">
    <title>Hello World!</title>
  </head>
  <body>

    <select>
     <option>AAAAAA</option>  
     <option>BBBBBB</option>
     <option>CCCCCC</option>
     <option>DDDDDD</option>
     <option>EEEEEE</option>
    </select>  
  
  </body>
</html>
```

**Comment by c0re100** [comment]
If you're facing `requestAnimationFrame()` isn't working in background, you may try to comment [that line](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/content/browser/renderer_host/render_widget_host_view_child_frame.cc#232) before [compile electron](https://www.electronjs.org/docs/latest/development/build-instructions-gn).

Just trial and error way, so I can't promise it works :')
Well, I am not familiar electron and chromium codebase, but It works for my use case currently(at least).

**Comment by GrzesiekKozdroj** [comment]
I'd like to develop html canvas game. Multiplayer one at it too. Turn based. 
While opponents will wait for each others move, they will surely like to do a quick peek, into someone else's websites. 
This breaks animation. 
Breaks my game too!
And this bug is closed!? Oh no, it is alive, well, kicking and breaking peoples dreams!

**Comment by GGAlanSmithee** [comment]
Is there any known solution to this problem? I am in the same boat as @GrzesiekKozdroj - I am developing a game using electron, and having RAF stop when the game is not in focus is more or less a show stopper for me.

**Comment by ProdigyView** [comment]
I'm doing game as well. It does not work for me. When my canvas is in the current screen which is the main application, everything runs smoothly. If I switch to another application which put the screen in the background, the animation gets noticeably choppier.

**Comment by iamisti** [comment]
> I'm doing game as well. It does not work for me. When my canvas is in the current screen which is the main application, everything runs smoothly. If I switch to another application which put the screen in the background, the animation gets noticeably choppier. But when I click back into my app, it fixes itself. I am testing this on two separate monitors. I'm developing for Windows. This bug is not fixed.
> 
> I've also done the following "hacks", which do not work:
> 
> * Silent audio track that is loop
> * Have a setInterval function
> * Have the animation being processed in worker threads
> * Background throttling is false in the switches and setting it in the BrowserWindow
> * Sacrificed a Zebra to the Chromium gods
> 
> nada works.

good luck brother. 

This ticket is 7 years old. I suggest you creating a new ticket. Noone will check old tockets from the team.
Give yourself a better chance with a new ticket.

**Comment by ilyasa1211** [comment]
This still not working, reopen this issue!
setInterval is not a great solution here since it doesn't adapt with user's frame rate
